"use client";

import { PRE_SALES_CHALLENGES, PRE_SALES_OBJECTIONS } from "@/data/pre-sales-studio-catalog";
import { applyChallenge, removeChallenge } from "@/lib/pre-sales-studio/engine";
import type { OpportunityState } from "@/types/pre-sales-studio";
import { Panel, StatusBadge, preSalesButton, preSalesPrimaryButton } from "@/components/pre-sales-studio/PreSalesPrimitives";

export function ChallengeConsole({ opportunity, onChange, onClose }: { opportunity: OpportunityState; onChange: (next: OpportunityState) => void; onClose: () => void }) {
  const active = PRE_SALES_CHALLENGES.filter((item) => opportunity.activeChallengeIds.includes(item.id));
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#020608]/90 p-3 backdrop-blur-md sm:p-6" role="dialog" aria-modal="true" aria-labelledby="challenge-title"><div className="mx-auto max-w-6xl"><Panel className="overflow-hidden"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/[0.08] p-5 sm:p-6"><div><StatusBadge tone="violet">Interactive objection lab</StatusBadge><h2 id="challenge-title" className="mt-3 text-2xl font-semibold text-white">Challenge the Solution</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Inject a new constraint. The gaps, architecture, POC, dataset plan, business assumptions, and next question update together.</p></div><button type="button" className={preSalesButton} onClick={onClose}>Close</button></header>
        <div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[1.3fr_.7fr]"><div><h3 className="text-sm font-semibold text-white">Customer challenges</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{PRE_SALES_CHALLENGES.map((challenge) => { const enabled = opportunity.activeChallengeIds.includes(challenge.id); return <article key={challenge.id} className={`rounded-xl border p-4 ${enabled ? "border-violet-200/35 bg-violet-200/[0.08]" : "border-white/[0.08] bg-black/15"}`}><div className="flex items-start justify-between gap-2"><h4 className="text-sm font-semibold text-white">“{challenge.title}”</h4>{enabled ? <StatusBadge tone="violet">Injected</StatusBadge> : null}</div><p className="mt-2 text-xs leading-5 text-slate-400">{challenge.recommendationImpact}</p><button type="button" className={`${enabled ? preSalesButton : preSalesPrimaryButton} mt-4`} onClick={() => onChange(enabled ? removeChallenge(opportunity, challenge.id) : applyChallenge(opportunity, challenge.id))}>{enabled ? "Remove challenge" : "Inject challenge"}</button></article>; })}</div></div>
          <div className="space-y-4"><Panel className="p-4"><h3 className="text-sm font-semibold text-white">What changed and why</h3>{active.length ? <div className="mt-4 space-y-4">{active.map((challenge) => <div key={challenge.id} className="border-l border-violet-200/30 pl-3"><p className="text-xs font-semibold text-violet-100">{challenge.title}</p><ul className="mt-2 space-y-1 text-[11px] leading-4 text-slate-400"><li>Architecture: {challenge.architectureImpact}</li><li>POC: {challenge.pocImpact}</li><li>Dataset: {challenge.datasetImpact}</li><li>Business case: {challenge.businessImpact}</li></ul><p className="mt-2 text-xs font-semibold text-cyan-100">Ask next: {challenge.nextQuestion}</p></div>)}</div> : <p className="mt-3 text-xs text-slate-500">Inject a challenge to create a visible change explanation.</p>}</Panel>
          <details className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><summary className="cursor-pointer text-sm font-semibold text-white">Objection handling console</summary><div className="mt-4 space-y-3">{PRE_SALES_OBJECTIONS.map((objection) => <details key={objection.id} className="rounded-lg border border-white/[0.07] p-3"><summary className="cursor-pointer text-xs font-semibold text-slate-200">{objection.title}</summary><ol className="mt-3 space-y-2 text-[11px] leading-4 text-slate-400"><li><strong className="text-slate-300">Acknowledge:</strong> {objection.acknowledge}</li><li><strong className="text-slate-300">Underlying requirement:</strong> {objection.underlyingRequirement}</li><li><strong className="text-slate-300">Ask:</strong> {objection.clarifyingQuestion}</li><li><strong className="text-slate-300">Validate:</strong> {objection.technicalValidation}</li><li><strong className="text-slate-300">Evidence:</strong> {objection.measurableEvidence}</li><li><strong className="text-amber-100">Do not promise:</strong> {objection.doNotPromise}</li></ol></details>)}</div></details></div></div>
      </Panel></div></div>;
}
