"use client";

import { buildPocPlan, updateCriterion } from "@/lib/pre-sales-studio/engine";
import type { OpportunityState } from "@/types/pre-sales-studio";
import { Panel, SectionHeading, StatusBadge, preSalesButton, preSalesInput, preSalesPrimaryButton, preSalesTextarea } from "@/components/pre-sales-studio/PreSalesPrimitives";

export function PocBuilder({ opportunity, onChange, onNext }: { opportunity: OpportunityState; onChange: (next: OpportunityState) => void; onNext: () => void }) {
  const plan = buildPocPlan(opportunity);
  const updateDataset = (id: string, update: { selected?: boolean; sampleCount?: number }) => onChange({ ...opportunity, datasetSegments: opportunity.datasetSegments.map((item) => item.id === id ? { ...item, ...update } : item), updatedAt: new Date().toISOString() });
  return <div className="space-y-6">
    <SectionHeading eyebrow="04 · Proof of concept" title="Turn a promising architecture into a falsifiable decision." detail="Illustrative targets remain suggestions until someone explicitly adopts or edits them." actions={<button type="button" className={preSalesPrimaryButton} onClick={onNext}>Open technical demo →</button>} />
    <div className="grid gap-4 lg:grid-cols-2"><Hypothesis title="Business hypothesis" text={plan.businessHypothesis} /><Hypothesis title="Technical hypothesis" text={plan.technicalHypothesis} /></div>
    <Panel className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">Measurable success criteria</h3><p className="mt-2 text-xs leading-5 text-slate-400">No baseline or target is invented. Adopt an illustrative definition only after it matches the customer decision.</p></div><StatusBadge tone={opportunity.criteria.some((item) => item.targetSource === "customer-adopted" || item.targetSource === "customer-provided") ? "green" : "amber"}>{opportunity.criteria.length} criteria</StatusBadge></div><div className="mt-5 space-y-4">{opportunity.criteria.map((item) => <article key={item.id} className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-sm font-semibold text-white">{item.label}</h4><p className="mt-1 text-[11px] leading-4 text-slate-500">Illustrative prompt: {item.illustrativeTarget}</p></div><StatusBadge tone={item.targetSource === "unknown" ? "amber" : "green"}>{item.targetSource.replaceAll("-", " ")}</StatusBadge></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><CriterionInput label="Current baseline" value={item.baseline} onChange={(baseline) => onChange(updateCriterion(opportunity, item.id, { baseline }))} /><CriterionInput label="Target" value={item.target} onChange={(target) => onChange(updateCriterion(opportunity, item.id, { target, targetSource: target ? "customer-provided" : "unknown" }))} /><CriterionInput label="Owner" value={item.owner} onChange={(owner) => onChange(updateCriterion(opportunity, item.id, { owner }))} /><CriterionInput label="Measurement method" value={item.measurementMethod} area onChange={(measurementMethod) => onChange(updateCriterion(opportunity, item.id, { measurementMethod }))} /><CriterionInput label="Dataset" value={item.dataset} area onChange={(dataset) => onChange(updateCriterion(opportunity, item.id, { dataset }))} /><CriterionInput label="Notes" value={item.notes} area onChange={(notes) => onChange(updateCriterion(opportunity, item.id, { notes }))} /></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" className={preSalesButton} onClick={() => onChange(updateCriterion(opportunity, item.id, { target: item.illustrativeTarget, targetSource: "customer-adopted", status: "adopted" }))}>Adopt illustrative definition</button><select aria-label={`${item.label} status`} className={`${preSalesInput} max-w-52`} value={item.status} onChange={(event) => onChange(updateCriterion(opportunity, item.id, { status: event.target.value as typeof item.status }))}><option value="draft">Draft</option><option value="adopted">Adopted</option><option value="measuring">Measuring</option><option value="met">Met</option><option value="not-met">Not met</option></select></div></article>)}</div></Panel>
    <Panel className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">Evaluation dataset planner</h3><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">Stratify the corpus so clean averages cannot hide high-risk production slices.</p></div><StatusBadge tone={plan.datasetWarnings.length ? "rose" : "green"}>{plan.datasetWarnings.length ? `${plan.datasetWarnings.length} coverage warnings` : "Coverage reviewed"}</StatusBadge></div>{plan.datasetWarnings.length ? <ul className="mt-4 grid gap-2 md:grid-cols-2">{plan.datasetWarnings.map((warning) => <li key={warning} className="rounded-lg border border-rose-200/15 bg-rose-200/[0.05] p-3 text-xs leading-5 text-rose-50/80">{warning}</li>)}</ul> : null}<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{opportunity.datasetSegments.map((segment) => <label key={segment.id} className={`rounded-xl border p-4 ${segment.selected ? "border-cyan-200/25 bg-cyan-200/[0.06]" : "border-white/[0.08] bg-black/15"}`}><span className="flex items-start gap-3"><input type="checkbox" className="mt-1 accent-cyan-200" checked={segment.selected} onChange={(event) => updateDataset(segment.id, { selected: event.target.checked })} /><span><span className="block text-sm font-semibold text-white">{segment.label}</span><span className="mt-1 block text-[11px] leading-4 text-slate-500">{segment.reason}</span></span></span>{segment.selected ? <span className="mt-3 block"><span className="mb-1 block text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">Planned samples</span><input type="number" min="0" className={preSalesInput} value={segment.sampleCount} onChange={(event) => updateDataset(segment.id, { sampleCount: Math.max(0, Number(event.target.value)) })} /></span> : null}</label>)}</div></Panel>
    <div className="grid gap-4 lg:grid-cols-3"><ListPanel title="Agreed scope" items={plan.agreedScope} /><ListPanel title="Excluded scope" items={plan.excludedScope} /><ListPanel title="Exit criteria" items={plan.exitCriteria} /></div>
  </div>;
}

function Hypothesis({ title, text }: { title: string; text: string }) { return <Panel className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-100/60">{title}</p><p className="mt-3 text-sm leading-6 text-slate-200">{text}</p></Panel>; }
function CriterionInput({ label, value, onChange, area = false }: { label: string; value: string; onChange: (value: string) => void; area?: boolean }) { return <label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</span>{area ? <textarea className={preSalesTextarea} value={value} onChange={(event) => onChange(event.target.value)} /> : <input className={preSalesInput} value={value} onChange={(event) => onChange(event.target.value)} />}</label>; }
function ListPanel({ title, items }: { title: string; items: string[] }) { return <Panel className="p-5"><h3 className="text-sm font-semibold text-white">{title}</h3><ul className="mt-3 space-y-2">{items.map((item) => <li key={item} className="border-l border-white/10 pl-3 text-xs leading-5 text-slate-400">{item}</li>)}</ul></Panel>; }
