"use client";

import { useMemo, useState } from "react";

import { buildPocPlan, buildPreSalesExport, calculateBusinessCase, computeDiscoveryInsight, deriveReadouts, executiveReadoutMarkdown, technicalReadoutMarkdown } from "@/lib/pre-sales-studio/engine";
import type { BusinessCaseInputs, OpportunityState } from "@/types/pre-sales-studio";
import { Panel, SectionHeading, StatusBadge, preSalesButton, preSalesInput, preSalesPrimaryButton } from "@/components/pre-sales-studio/PreSalesPrimitives";

const BUSINESS_INPUTS: Array<{ key: keyof BusinessCaseInputs; label: string; suffix?: string }> = [
  { key: "monthlyCallCount", label: "Monthly call count" }, { key: "averageCallDuration", label: "Average call duration", suffix: "minutes" },
  { key: "currentTranscriptionCost", label: "Current transcription cost", suffix: "$/minute" }, { key: "proposedTranscriptionCost", label: "Proposed scenario cost", suffix: "$/minute" },
  { key: "humanQaPercent", label: "Human QA sample", suffix: "%" }, { key: "qaReviewMinutes", label: "QA review time", suffix: "minutes/call" },
  { key: "loadedLaborCost", label: "Loaded QA labor", suffix: "$/hour" }, { key: "currentContainment", label: "Current containment", suffix: "%" },
  { key: "proposedContainment", label: "Proposed containment", suffix: "%" }, { key: "transferRate", label: "Transfer rate", suffix: "%" },
  { key: "averageHandlingMinutes", label: "Average handle time", suffix: "minutes" }, { key: "abandonment", label: "Abandonment", suffix: "%" },
  { key: "currentConversion", label: "Current conversion", suffix: "%" }, { key: "proposedConversion", label: "Proposed conversion", suffix: "%" },
  { key: "averageTransactionValue", label: "Average transaction value", suffix: "$" }, { key: "implementationCost", label: "Illustrative implementation cost", suffix: "$" },
];

export function ReadoutWorkspace({ opportunity, onChange }: { opportunity: OpportunityState; onChange: (next: OpportunityState) => void }) {
  const [view, setView] = useState<"executive" | "engineering">("executive"); const [copied, setCopied] = useState("");
  const readouts = useMemo(() => deriveReadouts(opportunity), [opportunity]); const poc = useMemo(() => buildPocPlan(opportunity), [opportunity]); const insight = useMemo(() => computeDiscoveryInsight(opportunity), [opportunity]); const business = useMemo(() => calculateBusinessCase(opportunity.businessCaseInputs), [opportunity.businessCaseInputs]);
  const updateBusiness = (key: keyof BusinessCaseInputs, value: string) => onChange({ ...opportunity, businessCaseInputs: { ...opportunity.businessCaseInputs, [key]: value }, updatedAt: new Date().toISOString() });
  const copy = async (kind: "executive" | "engineering") => { const text = kind === "executive" ? executiveReadoutMarkdown(opportunity) : technicalReadoutMarkdown(opportunity); await navigator.clipboard.writeText(text); setCopied(kind); window.setTimeout(() => setCopied(""), 1800); };
  const exportJson = () => download(`pre-sales-studio-${safeName(opportunity.name)}.json`, JSON.stringify(buildPreSalesExport(opportunity), null, 2), "application/json");
  return <div className="space-y-6">
    <SectionHeading eyebrow="06 · Executive and technical alignment" title="Close on a decision, not another diagram." detail="Both readouts use the same session facts. Unknowns remain visible, and all financial outputs are scenario estimates." actions={<><button type="button" className={preSalesButton} onClick={() => copy(view)}>{copied === view ? "Copied" : `Copy ${view} Markdown`}</button><button type="button" className={preSalesPrimaryButton} onClick={exportJson}>Export session JSON</button></>} />
    <div className="flex flex-wrap gap-2" role="group" aria-label="Readout audience"><button type="button" className={view === "executive" ? preSalesPrimaryButton : preSalesButton} aria-pressed={view === "executive"} onClick={() => setView("executive")}>Executive View</button><button type="button" className={view === "engineering" ? preSalesPrimaryButton : preSalesButton} aria-pressed={view === "engineering"} onClick={() => setView("engineering")}>Engineering View</button></div>
    {view === "executive" ? <ExecutiveView readout={readouts.executive} confidence={insight.confidence} /> : <EngineeringView readout={readouts.technical} />}
    <Panel className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">Transparent business-value scenario</h3><p className="mt-2 text-xs leading-5 text-slate-400">Supply comparable inputs. Blank inputs stay blank; no price, improvement, or benchmark is assumed.</p></div><StatusBadge tone="amber">Scenario estimates—not guaranteed outcomes</StatusBadge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{BUSINESS_INPUTS.map((field) => <label key={field.key}><span className="mb-1.5 flex justify-between gap-2 text-[10px] font-bold uppercase tracking-[.1em] text-slate-500"><span>{field.label}</span><span>{field.suffix}</span></span><input inputMode="decimal" className={preSalesInput} value={opportunity.businessCaseInputs[field.key]} onChange={(event) => updateBusiness(field.key, event.target.value)} /></label>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Value label="Monthly platform cost" value={moneyOrUnknown(business.monthlyPlatformCost)} /><Value label="Monthly scenario savings" value={moneyOrUnknown(business.monthlySavings)} /><Value label="QA hours recovered" value={numberOrUnknown(business.qaHoursRecovered)} /><Value label="Cost / interaction" value={moneyOrUnknown(business.costPerInteraction)} /><Value label="Cost / completed task" value={moneyOrUnknown(business.costPerCompletedTask)} /><Value label="Incremental conversions" value={numberOrUnknown(business.incrementalConversions)} /><Value label="Potential annual value" value={moneyOrUnknown(business.potentialAnnualValue)} /><Value label="Estimated payback" value={business.paybackMonths === null ? "Inputs required" : `${business.paybackMonths.toFixed(1)} months`} /></div><details className="mt-5 rounded-xl border border-white/[0.08] bg-black/15 p-4"><summary className="cursor-pointer text-xs font-semibold text-white">Show formulas and assumptions</summary><div className="mt-4 grid gap-5 md:grid-cols-2"><ul className="space-y-2">{business.formulas.map((formula) => <li key={formula} className="text-xs leading-5 text-slate-400">{formula}</li>)}</ul><ul className="space-y-2">{business.assumptions.map((assumption) => <li key={assumption} className="text-xs leading-5 text-amber-50/70">{assumption}</li>)}</ul></div></details></Panel>
    <div className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><Panel className="p-5 sm:p-6"><h3 className="text-lg font-semibold text-white">Production handoff</h3><p className="mt-2 text-xs text-slate-400">Continuity checklist—not a production readiness certification.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{opportunity.productionHandoff.map((item) => <label key={item.id} className="flex items-start gap-3 rounded-lg border border-white/[0.07] bg-black/15 p-3 text-xs text-slate-300"><input type="checkbox" className="mt-0.5 accent-cyan-200" checked={item.complete} onChange={(event) => onChange({ ...opportunity, productionHandoff: opportunity.productionHandoff.map((current) => current.id === item.id ? { ...current, complete: event.target.checked } : current), updatedAt: new Date().toISOString() })} />{item.label}</label>)}</div></Panel><Panel className="p-5 sm:p-6"><h3 className="text-lg font-semibold text-white">Proof-of-concept decision path</h3><ol className="mt-4 space-y-3">{poc.milestones.map((milestone, index) => <li key={milestone} className="flex gap-3 text-xs leading-5 text-slate-400"><span className="font-mono text-cyan-100/60">{String(index + 1).padStart(2, "0")}</span>{milestone}</li>)}</ol><div className="mt-5 rounded-xl border border-amber-200/15 bg-amber-200/[0.04] p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-amber-100/70">Decision required</p><p className="mt-2 text-sm leading-6 text-white">{readouts.executive.recommendedDecision}</p></div></Panel></div>
  </div>;
}

function ExecutiveView({ readout, confidence }: { readout: ReturnType<typeof deriveReadouts>["executive"]; confidence: number }) { return <Panel className="p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><StatusBadge tone="cyan">Executive View</StatusBadge><h3 className="mt-4 max-w-4xl text-3xl font-semibold leading-tight text-white">{readout.proposedOutcome}</h3></div><StatusBadge tone={confidence >= 70 ? "green" : "amber"}>{confidence}% discovery confidence</StatusBadge></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><ReadoutItem label="Business problem" value={readout.businessProblem} /><ReadoutItem label="Why now" value={readout.whyNow} /><ReadoutItem label="Expected value" value={readout.expectedValue} /><ReadoutItem label="Major risk" value={readout.majorRisk} /><ReadoutItem label="Recommended decision" value={readout.recommendedDecision} /><ReadoutItem label="Next milestone" value={readout.nextMilestone} /></div></Panel>; }
function EngineeringView({ readout }: { readout: ReturnType<typeof deriveReadouts>["technical"] }) { return <Panel className="p-6 sm:p-8"><StatusBadge tone="violet">Engineering View</StatusBadge><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Object.entries(readout).map(([label, value]) => <div key={label}><h3 className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">{title(label)}</h3>{Array.isArray(value) ? <ul className="mt-3 space-y-2">{value.length ? value.map((item) => <li key={item} className="text-xs leading-5 text-slate-300">{item}</li>) : <li className="text-xs text-slate-500">Unresolved</li>}</ul> : <p className="mt-3 text-sm leading-6 text-slate-300">{value}</p>}</div>)}</div></Panel>; }
function ReadoutItem({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 text-sm leading-6 text-slate-200">{value}</p></div>; }
function Value({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-white">{value}</p></div>; }
function moneyOrUnknown(value: number | null) { return value === null ? "Inputs required" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value); }
function numberOrUnknown(value: number | null) { return value === null ? "Inputs required" : new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value); }
function download(filename: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
function safeName(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "opportunity"; }
function title(value: string) { return value.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()); }
