"use client";

import Link from "next/link";

import { buildArchitectureBlueprint, computeDiscoveryInsight, recommendApiLabPresets, recommendSolution } from "@/lib/pre-sales-studio/engine";
import type { OpportunityState, RecommendationFit } from "@/types/pre-sales-studio";
import { Panel, SectionHeading, StatusBadge, preSalesPrimaryButton } from "@/components/pre-sales-studio/PreSalesPrimitives";
import { PreSalesArchitectureDiagram } from "@/components/pre-sales-studio/PreSalesArchitectureDiagram";

const FIT: Record<RecommendationFit, { label: string; tone: "cyan" | "green" | "amber" | "rose" | "violet" }> = { confirmed: { label: "Confirmed fit", tone: "green" }, likely: { label: "Likely fit—validate during POC", tone: "cyan" }, unresolved: { label: "Unresolved requirement", tone: "amber" }, risk: { label: "Potential risk", tone: "rose" } };

export function SolutionBlueprint({ opportunity, onNext }: { opportunity: OpportunityState; onNext: () => void }) {
  const recommendations = recommendSolution(opportunity); const blueprint = buildArchitectureBlueprint(opportunity); const insight = computeDiscoveryInsight(opportunity); const apiPresets = recommendApiLabPresets(opportunity);
  return <div className="space-y-6">
    <SectionHeading eyebrow="03 · Solution blueprint" title="A recommended starting architecture, with the reasoning exposed." detail="Changing discovery inputs or injecting a challenge changes this view deterministically. No opaque model is selecting the package." actions={<button type="button" className={preSalesPrimaryButton} onClick={onNext}>Build the POC →</button>} />
    <Panel className="p-5 sm:p-6"><PreSalesArchitectureDiagram blueprint={blueprint} /></Panel>
    <div className="grid gap-4 xl:grid-cols-2">{recommendations.map((recommendation) => <Panel key={recommendation.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-100/55">{recommendation.capability}</p><h3 className="mt-2 text-lg font-semibold text-white">{recommendation.title}</h3></div><StatusBadge tone={FIT[recommendation.fit].tone}>{FIT[recommendation.fit].label}</StatusBadge></div><dl className="mt-5 grid gap-3 text-xs leading-5 sm:grid-cols-2"><Evidence label="Reason" value={recommendation.reason} /><Evidence label="Supporting requirement" value={recommendation.requirement} /><Evidence label="Working assumption" value={recommendation.assumption} /><Evidence label="Tradeoff" value={recommendation.tradeoff} /><div className="sm:col-span-2"><Evidence label="Validation step" value={recommendation.validationStep} /></div></dl><p className="mt-4 text-[10px] text-slate-600">Triggered by: {recommendation.sourceFields.join(" · ")}</p></Panel>)}</div>
    <Panel className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-violet-100/60">API Lab handoff</p><h3 className="mt-2 text-lg font-semibold text-white">Presets selected from discovery evidence</h3><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">These links open verified operations for inspection. They do not execute a request or imply production fit.</p></div><StatusBadge tone={apiPresets.length ? "violet" : "amber"}>{apiPresets.length || "No"} presets</StatusBadge></div>{apiPresets.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{apiPresets.map((preset) => <Link key={preset.endpointId} href={preset.href} className="min-h-12 rounded-xl border border-violet-200/15 bg-violet-200/[0.045] p-4 outline-none hover:border-violet-200/35 focus-visible:ring-2 focus-visible:ring-violet-200/70"><span className="text-sm font-semibold text-violet-50">{preset.title}</span><span className="mt-1 block font-mono text-[10px] text-violet-100/55">{preset.endpointId}</span><span className="mt-2 block text-xs leading-5 text-slate-400">{preset.reason}</span></Link>)}</div> : <p className="mt-4 text-xs text-slate-500">Answer the workload and interaction questions to select a relevant verified operation.</p>}</Panel>
    <Panel className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-amber-100/60">Decision confidence</p><h3 className="mt-2 text-xl font-semibold text-white">{insight.confidence}% discovery confidence</h3></div><StatusBadge tone={insight.unanswered.length ? "amber" : "green"}>{insight.unanswered.length} unresolved questions</StatusBadge></div><p className="mt-3 text-xs leading-5 text-slate-400">Confidence falls when decision-relevant information is absent. It is not a probability that the architecture will succeed.</p></Panel>
  </div>;
}

function Evidence({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/[0.07] bg-black/15 p-3"><dt className="font-bold uppercase tracking-[.12em] text-slate-500">{label}</dt><dd className="mt-1.5 text-slate-300">{value}</dd></div>; }
