"use client";

import Link from "next/link";
import { useState } from "react";

import { illustrativeDemo, recommendSolution } from "@/lib/pre-sales-studio/engine";
import type { DemoResult, OpportunityState } from "@/types/pre-sales-studio";
import { Panel, SectionHeading, StatusBadge, preSalesButton, preSalesInput, preSalesPrimaryButton } from "@/components/pre-sales-studio/PreSalesPrimitives";

type LiveEnvelope = { ok?: boolean; data?: { transcript?: string; raw?: unknown }; error?: { message?: string } };

export function TechnicalDemoConsole({ opportunity, liveApiAvailable, openLabMode = false, onNext }: { opportunity: OpportunityState; liveApiAvailable: boolean; openLabMode?: boolean; onNext: () => void }) {
  const [mode, setMode] = useState<"simulated" | "live">("simulated"); const [result, setResult] = useState<DemoResult>(() => illustrativeDemo(opportunity)); const [audioUrl, setAudioUrl] = useState("https://static.deepgram.com/examples/Bueller-Life-moves-pretty-fast.wav"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const run = async () => {
    if (mode === "simulated") { setResult(illustrativeDemo(opportunity)); setError(""); return; }
    if (!liveApiAvailable) { setError("Live API mode is unavailable because the server-side DEEPGRAM_API_KEY is not configured."); return; }
    setLoading(true); setError(""); const started = performance.now();
    try { const response = await fetch("/api/deepgram/transcribe-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: audioUrl, model: "nova-3", language: "en", smart_format: true, punctuate: true, utterances: true, diarize: false, keyterm: opportunity.discovery.specialistTerminology }) }); const payload = await response.json() as LiveEnvelope; if (!response.ok || !payload.ok) throw new Error(payload.error?.message || "The live request failed."); const duration = Math.round(performance.now() - started); const transcript = payload.data?.transcript?.trim() || "The response contained no transcript."; setResult({ label: "Live Deepgram API Response", transcript, interimTranscript: "Not applicable for this prerecorded URL route.", finalTranscript: transcript, timestamps: [`${duration} ms browser-observed request duration`], detectedLanguage: "Configured: English", speakerLabels: "Diarization not requested", redaction: "Not requested", requestDurationMs: duration, firstResultLatencyMs: null, finalResultLatencyMs: duration, model: "nova-3", options: ["smart_format", "punctuate", "utterances"], retries: 0, error: "" }); } catch (caught) { setError(caught instanceof Error ? caught.message : "The live request failed."); } finally { setLoading(false); }
  };
  return <div className="space-y-6"><SectionHeading eyebrow="05 · Technical demo" title="Show the workflow without confusing simulation for evidence." detail="Safe Demonstration Mode is deterministic and works without credentials. Live mode calls the existing server route; the API key never reaches the browser." actions={<button type="button" className={preSalesPrimaryButton} onClick={onNext}>Generate readouts →</button>} />
    <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Panel className="p-5"><fieldset><legend className="text-sm font-semibold text-white">Demonstration mode</legend><div className="mt-3 grid gap-2"><ModeButton active={mode === "simulated"} title="Safe Demonstration Mode" detail="Deterministic illustrative transcript and timings." onClick={() => setMode("simulated")} /><ModeButton active={mode === "live"} disabled={!liveApiAvailable} title="Live API Mode" detail={liveApiAvailable ? "Uses the configured server-side Deepgram key." : "Server key not configured; safe mode remains available."} onClick={() => setMode("live")} /></div></fieldset>{mode === "live" ? openLabMode ? <p className="mt-5 rounded-lg border border-cyan-200/15 bg-cyan-200/[0.04] p-3 text-xs leading-5 text-cyan-50/70">Open Lab runs the bundled audio sample. Custom public URLs are available only in local/operator mode.</p> : <label className="mt-5 block"><span className="mb-2 block text-xs font-semibold text-slate-200">Public audio URL</span><input className={preSalesInput} value={audioUrl} onChange={(event) => setAudioUrl(event.target.value)} /></label> : null}<button type="button" className={`${preSalesPrimaryButton} mt-5 w-full`} disabled={loading} onClick={run}>{loading ? "Running…" : mode === "live" ? "Run live transcription" : "Run illustrative demonstration"}</button>{error ? <p role="alert" className="mt-3 rounded-lg border border-rose-200/15 bg-rose-200/[0.05] p-3 text-xs text-rose-100">{error}</p> : null}<div className="mt-5 border-t border-white/[0.08] pt-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Existing Learning Lab paths</p><div className="mt-3 flex flex-wrap gap-2"><Link href="/?module=live-mic&from=pre-sales-studio" className={preSalesButton}>Open Live Mic Lab</Link><Link href="/?module=upload-audio&from=pre-sales-studio" className={preSalesButton}>Open Upload Lab</Link></div><p className="mt-3 text-[11px] leading-4 text-slate-500">Microphone and upload behavior stay in the existing, purpose-built labs. This console stores no audio or raw transcript.</p></div></Panel>
      <Panel className="p-5 sm:p-6" aria-live="polite"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge tone={result.label === "Illustrative Demo Data" ? "amber" : "green"}>{result.label}</StatusBadge><span className="text-[11px] text-slate-500">{result.model} · {result.requestDurationMs} ms</span></div><h3 className="mt-5 text-sm font-semibold text-white">Final transcript</h3><blockquote className="mt-3 rounded-xl border border-white/[0.08] bg-black/25 p-5 text-lg leading-8 text-slate-100">{result.finalTranscript}</blockquote><h3 className="mt-5 text-sm font-semibold text-white">Interim result</h3><p className="mt-2 rounded-lg border border-white/[0.06] p-3 text-sm text-slate-400">{result.interimTranscript}</p><dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Metric label="First result" value={result.firstResultLatencyMs === null ? "N/A" : `${result.firstResultLatencyMs} ms`} /><Metric label="Final result" value={`${result.finalResultLatencyMs} ms`} /><Metric label="Language" value={result.detectedLanguage} /><Metric label="Speakers" value={result.speakerLabels} /><Metric label="Redaction" value={result.redaction} /><Metric label="Retries" value={String(result.retries)} /></dl><p className="mt-4 text-[11px] leading-4 text-amber-100/70">{result.label === "Illustrative Demo Data" ? "These values are fabricated for interaction design and are not Deepgram benchmarks." : "Timing is browser-observed for this single request and is not a benchmark."}</p></Panel></div>
    <Panel className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-100/60">Configuration rationale</p><ul className="mt-3 grid gap-2 md:grid-cols-2">{recommendSolution(opportunity).slice(0, 4).map((item) => <li key={item.id} className="text-xs leading-5 text-slate-400"><strong className="text-slate-200">{item.capability}:</strong> {item.validationStep}</li>)}</ul></Panel>
  </div>;
}

function ModeButton({ active, disabled = false, title, detail, onClick }: { active: boolean; disabled?: boolean; title: string; detail: string; onClick: () => void }) { return <button type="button" aria-pressed={active} disabled={disabled} onClick={onClick} className={`rounded-xl border p-4 text-left focus-visible:outline-2 focus-visible:outline-cyan-200 disabled:cursor-not-allowed disabled:opacity-45 ${active ? "border-cyan-200/35 bg-cyan-200/[0.08]" : "border-white/[0.08] bg-black/15"}`}><span className="block text-sm font-semibold text-white">{title}</span><span className="mt-1 block text-[11px] leading-4 text-slate-500">{detail}</span></button>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/[0.07] bg-black/15 p-3"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</dt><dd className="mt-1.5 text-xs text-slate-200">{value}</dd></div>; }
