import type {
  ApiCategory,
  ApiChainPreset,
  ApiOperation,
  ApiParameterDefinition,
} from "@/types/deepgram-api-studio";

const DOCS_ROOT = "https://developers.deepgram.com";

const STT_BASE_PARAMETERS: ApiParameterDefinition[] = [
  {
    name: "model",
    label: "Model",
    location: "query",
    control: "select",
    defaultValue: "nova-3",
    help: "Selects the speech recognition model. Nova-3 is the lab default.",
    options: [
      { label: "Nova-3", value: "nova-3" },
      { label: "Nova-2", value: "nova-2" },
    ],
  },
  {
    name: "language",
    label: "Language",
    location: "query",
    control: "select",
    defaultValue: "en",
    help: "Provides an expected language or multilingual mode for recognition.",
    options: [
      { label: "English", value: "en" },
      { label: "Spanish", value: "es" },
      { label: "French", value: "fr" },
      { label: "German", value: "de" },
      { label: "Italian", value: "it" },
      { label: "Japanese", value: "ja" },
      { label: "Dutch", value: "nl" },
      { label: "Multilingual", value: "multi" },
    ],
  },
  {
    name: "smart_format",
    label: "Smart formatting",
    location: "query",
    control: "toggle",
    defaultValue: true,
    help: "Formats dates, numbers, currency, and other transcript patterns for readability.",
  },
  {
    name: "diarize",
    label: "Speaker diarization",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Legacy boolean diarization control retained for the existing lab route. Deepgram now recommends diarize_model.",
  },
  {
    name: "diarize_model",
    label: "Diarization model",
    location: "query",
    control: "select",
    defaultValue: "none",
    help: "Current speaker-diarization selector. Streaming supports latest/v1; prerecorded also documents v2.",
    options: [
      { label: "Off", value: "none" },
      { label: "Latest", value: "latest" },
      { label: "v1", value: "v1" },
      { label: "v2 · prerecorded", value: "v2" },
    ],
  },
  {
    name: "punctuate",
    label: "Punctuation",
    location: "query",
    control: "toggle",
    defaultValue: true,
    help: "Adds punctuation and casing to make transcript text easier to consume.",
  },
  {
    name: "utterances",
    label: "Utterances",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Segments the transcript into spoken utterances for conversational workflows.",
  },
  {
    name: "paragraphs",
    label: "Paragraphs",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Structures longer transcripts into readable paragraphs.",
  },
  {
    name: "numerals",
    label: "Numerals",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Uses Arabic numerals where supported instead of spelling numbers as words.",
  },
  {
    name: "detect_language",
    label: "Detect language",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Asks Deepgram to detect the source language. Confirm compatibility with any explicit language selection.",
  },
  {
    name: "multichannel",
    label: "Multichannel",
    location: "query",
    control: "toggle",
    defaultValue: false,
    help: "Transcribes independent audio channels separately when the source contains multiple channels.",
  },
  {
    name: "keyterm",
    label: "Keyterms",
    location: "query",
    control: "text",
    defaultValue: "",
    placeholder: "Deepgram, Omni Neural Engine",
    help: "Boosts important domain terms on Nova-3. Repeated keyterm parameters may be required in production requests.",
  },
];

const STT_RESPONSE_PATHS = [
  "results.channels[0].alternatives[0].transcript",
  "results.channels[0].alternatives[0].words",
  "metadata.request_id",
];

const SERVER_KEY_NOTES = [
  "DEEPGRAM_API_KEY is read only inside the local server route.",
  "Authorization must be redacted from previews, logs, and exported examples.",
];

function docsOnlyOperation(
  operation: Omit<ApiOperation, "transport" | "auth" | "status" | "executable" | "parameters"> & {
    parameters?: ApiParameterDefinition[];
    capabilityStatus?: Exclude<ApiOperation["status"], "available">;
  },
): ApiOperation {
  const { capabilityStatus = "manual-verification-required", parameters = [], ...definition } = operation;
  return {
    ...definition,
    transport: "Concept/docs-only",
    auth: "Disabled/docs-only",
    status: capabilityStatus,
    executable: false,
    parameters,
  };
}

export const DEEPGRAM_API_CATALOG: ApiCategory[] = [
  {
    id: "voice-agent",
    name: "Voice Agent",
    short: "AGENT",
    goal: "Listen, think, and speak in one realtime session.",
    description: "Explore the WebSocket lifecycle and messages behind an end-to-end conversational voice agent.",
    unlocks: [
      "Realtime phone agents",
      "Agent assist",
      "Appointment scheduling",
      "Support triage",
      "Conversational IVR replacement",
    ],
    chainIdeas: [
      "Voice Agent + CRM lookup",
      "Voice Agent + Text Intelligence summary",
      "Voice Agent + TTS brand voice",
      "Twilio or telephony + Voice Agent",
    ],
    checkpoint: [
      "Why is this endpoint a WebSocket instead of a single REST request?",
      "Which settings describe listen, think, and speak behavior?",
      "Where should tool results be validated before returning to the session?",
    ],
    operations: [
      {
        id: "voice-agent-converse",
        categoryId: "voice-agent",
        name: "Agent Converse lifecycle",
        summary: "Build the initial settings message and study conversation, function-call, audio-input, and audio-output events.",
        endpoint: "wss://agent.deepgram.com/v1/agent/converse",
        method: "WebSocket",
        transport: "WebSocket",
        auth: "Temporary browser token",
        status: "manual-verification-required",
        executable: false,
        docsUrl: `${DOCS_ROOT}/reference/voice-agent/voice-agent`,
        parameters: [
          {
            name: "settings",
            label: "Settings message",
            location: "stream",
            control: "json",
            defaultValue: JSON.stringify(
              {
                type: "Settings",
                audio: {
                  input: { encoding: "linear16", sample_rate: 16000 },
                  output: { encoding: "linear16", sample_rate: 24000, container: "none" },
                },
                agent: {
                  language: "en",
                  listen: { provider: { type: "deepgram", model: "nova-3", smart_format: false } },
                  think: { provider: { type: "nvidia", model: "nvidia/nemotron-3-nano-30b-a3b" } },
                  speak: { provider: { type: "deepgram", model: "aura-2-asteria-en" } },
                },
              },
              null,
              2,
            ),
            help: "The first configuration message defines audio formats plus listen, think, and speak behavior. Verify provider settings in current docs.",
          },
        ],
        exampleBody: {
          messages: [
            { type: "Settings", purpose: "Configure audio and agent behavior." },
            { type: "UpdatePrompt", purpose: "Update conversation context." },
            { type: "FunctionCallRequest", purpose: "Ask your trusted tool layer to perform work." },
            { type: "binary audio", purpose: "Stream microphone or telephony audio into the socket." },
          ],
        },
        exampleResponse: {
          type: "Welcome | SettingsApplied | ConversationText | FunctionCallRequest | AgentAudioDone | binary audio",
          note: "Example response shape only. No live agent request was run.",
        },
        responsePaths: ["type", "role", "content", "functions[].id", "binary audio frames"],
        whenToUse: ["You need a low-latency conversational loop.", "The agent must hear, reason, use tools, and speak in one session."],
        whenNotToUse: ["A one-shot transcript or one-shot TTS response is enough.", "You cannot safely host tool execution and session policy."],
        commonMistakes: ["Sending audio before settings are accepted.", "Treating example event names as stable without checking current docs.", "Running tools without validation or timeouts."],
        securityNotes: ["Never place the permanent API key in browser WebSocket code.", "Constrain tools with schemas, allowlists, timeouts, and least privilege."],
        learningNotes: ["A Voice Agent is a stateful event stream: wait for Welcome, send Settings, wait for SettingsApplied, then stream audio.", "Audio input and output may be binary frames while control messages are JSON.", "Some official custom-endpoint guidance still shows api.deepgram.com; verify the production hostname against the current Voice Agent reference."],
        chainIdeas: ["Customer lookup tool", "Summary after session", "Telephony transport", "Approved TTS voice"],
        codeLabWorkflow: "voice-agent",
        relatedModule: "Code Lab",
        verifyInDocs: true,
      },
    ],
  },
  {
    id: "speech-to-text",
    name: "Speech to Text",
    short: "STT",
    goal: "Turn audio into structured transcript data.",
    description: "Compare hosted URL, uploaded file, realtime, and conversational transcription payload shapes.",
    unlocks: ["Searchable recordings", "Call analytics", "Captions", "Meeting notes", "Voice commands"],
    chainIdeas: ["STT → Text Intelligence", "STT → CRM ticket", "STT → searchable transcript"],
    checkpoint: [
      "Which fields belong in query parameters rather than the request body?",
      "Which response path contains the transcript?",
      "When should you upload audio bytes instead of sending a hosted URL?",
    ],
    operations: [
      {
        id: "stt-url",
        categoryId: "speech-to-text",
        name: "Pre-recorded URL transcription",
        summary: "Send Deepgram a public audio URL and receive transcript JSON.",
        endpoint: "https://api.deepgram.com/v1/listen",
        method: "POST",
        transport: "REST JSON",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/transcribe-url",
        docsUrl: `${DOCS_ROOT}/reference/speech-to-text/listen-pre-recorded`,
        parameters: [
          {
            name: "url",
            label: "Hosted audio URL",
            location: "body",
            control: "text",
            defaultValue: "https://static.deepgram.com/examples/Bueller-Life-moves-pretty-fast.wav",
            placeholder: "https://example.com/audio.wav",
            help: "Deepgram fetches this reachable HTTP(S) audio URL. The URL belongs in JSON, while recognition options belong in the query string.",
          },
          ...STT_BASE_PARAMETERS,
        ],
        exampleBody: { url: "https://example.com/audio.wav" },
        exampleResponse: { metadata: { request_id: "…" }, results: { channels: [{ alternatives: [{ transcript: "…", words: [] }] }] } },
        responsePaths: STT_RESPONSE_PATHS,
        whenToUse: ["Audio is already hosted at a URL Deepgram can reach.", "You want the simplest prerecorded integration."],
        whenNotToUse: ["The media is private and cannot be exposed through a signed or reachable URL.", "You need interim realtime results."],
        commonMistakes: ["Putting model options in the JSON body.", "Using a localhost or inaccessible URL.", "Expecting transcript text at the top level."],
        securityNotes: SERVER_KEY_NOTES,
        learningNotes: ["Query string: recognition configuration.", "JSON body: { url }.", "Response: JSON transcript, words, and metadata."],
        chainIdeas: ["Transcript → summary", "Transcript → sentiment", "Transcript → support ticket"],
        codeLabWorkflow: "transcribe-url",
        relatedModule: "Transcribe URL",
      },
      {
        id: "stt-file",
        categoryId: "speech-to-text",
        name: "Pre-recorded file transcription",
        summary: "Upload audio bytes through the local server boundary and receive transcript JSON.",
        endpoint: "https://api.deepgram.com/v1/listen",
        method: "POST",
        transport: "REST file upload",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/transcribe-file",
        docsUrl: `${DOCS_ROOT}/docs/pre-recorded-audio`,
        parameters: [
          {
            name: "file",
            label: "Audio file",
            location: "body",
            control: "file",
            defaultValue: "",
            help: "The browser posts multipart form data to the local route. The server forwards raw bytes; previews show file metadata only.",
          },
          ...STT_BASE_PARAMETERS,
        ],
        exampleBody: { binaryAudio: "***not included***", contentType: "audio/wav" },
        exampleResponse: { metadata: { request_id: "…" }, results: { channels: [{ alternatives: [{ transcript: "…", words: [] }] }] } },
        responsePaths: STT_RESPONSE_PATHS,
        whenToUse: ["Audio is on the user's device or inside a trusted system.", "You need to forward bytes without hosting the file first."],
        whenNotToUse: ["The file is too large for your application boundary.", "A realtime stream is required."],
        commonMistakes: ["Forwarding browser multipart boundaries directly to Deepgram.", "Logging raw audio.", "Omitting the audio content type."],
        securityNotes: [...SERVER_KEY_NOTES, "Treat recordings as sensitive data and define retention explicitly."],
        learningNotes: ["The local route receives multipart form data; Deepgram receives audio bytes.", "Binary bodies are represented only as metadata in the inspector."],
        chainIdeas: ["Recorded-session upload → diarized transcript", "Recording → compliance review"],
        codeLabWorkflow: "upload-audio",
        relatedModule: "Upload Audio",
      },
      {
        id: "stt-live",
        categoryId: "speech-to-text",
        name: "Live streaming STT",
        summary: "Stream microphone audio and receive interim and final transcript events.",
        endpoint: "wss://api.deepgram.com/v1/listen",
        method: "WebSocket",
        transport: "WebSocket",
        auth: "Temporary browser token",
        status: "available",
        executable: false,
        docsUrl: `${DOCS_ROOT}/reference/speech-to-text/listen-streaming`,
        parameters: [
          ...STT_BASE_PARAMETERS.slice(0, 5).map((parameter) => ({
            ...parameter,
            location: "query" as const,
            options: parameter.name === "diarize_model"
              ? parameter.options?.filter((option) => option.value !== "v2")
              : parameter.options,
          })),
          { name: "interim_results", label: "Interim results", location: "query", control: "toggle", defaultValue: true, help: "Emits changing partial hypotheses before a final segment." },
          { name: "endpointing", label: "Endpointing (ms)", location: "query", control: "number", defaultValue: 300, help: "Controls silence duration used to detect the end of speech." },
          { name: "vad_events", label: "VAD events", location: "query", control: "toggle", defaultValue: true, help: "Requests voice-activity lifecycle events when supported." },
        ],
        exampleResponse: { channel: { alternatives: [{ transcript: "…" }] }, is_final: false, speech_final: false },
        responsePaths: ["channel.alternatives[0].transcript", "is_final", "speech_final", "metadata.request_id"],
        whenToUse: ["You need captions or commands while someone is speaking.", "Latency matters more than batching."],
        whenNotToUse: ["You already have a complete file.", "The browser cannot safely obtain a temporary token."],
        commonMistakes: ["Starting MediaRecorder before the socket opens.", "Adding raw encoding or sample-rate parameters to containerized MediaRecorder audio.", "Persisting interim transcript fragments as final text."],
        securityNotes: ["Open the browser socket with a short-lived token from the local token route.", "Never cache tokens in localStorage."],
        learningNotes: ["This operation opens the existing Live Mic module rather than running inside the REST builder.", "The Live Mic sends browser MediaRecorder container audio, so Deepgram reads format metadata from the container and the request omits raw encoding and sample-rate parameters.", "Raw or headerless frame clients must instead supply an accurate encoding and sample rate.", "A WebSocket produces many events over one connection."],
        chainIdeas: ["Live transcript → agent assist", "Final utterance → intent router"],
        codeLabWorkflow: "live-mic",
        relatedModule: "Live Mic",
      },
      {
        id: "stt-flux",
        categoryId: "speech-to-text",
        name: "Flux conversational STT",
        summary: "Study turn-aware conversational transcription on the v2 listen surface.",
        endpoint: "wss://api.deepgram.com/v2/listen",
        method: "WebSocket",
        transport: "WebSocket",
        auth: "Temporary browser token",
        status: "manual-verification-required",
        executable: false,
        docsUrl: `${DOCS_ROOT}/reference/speech-to-text/listen-flux`,
        parameters: [
          { name: "model", label: "Model", location: "query", control: "text", defaultValue: "flux-general-en", help: "Flux model name; verify current availability and language support in official docs." },
        ],
        exampleResponse: { type: "TurnInfo", event: "StartOfTurn | EndOfTurn", transcript: "…", words: [], note: "Example response shape only." },
        responsePaths: ["event", "transcript", "words", "turn_index"],
        whenToUse: ["Turn boundaries are central to a conversational application."],
        whenNotToUse: ["Standard live transcription already meets the interaction model."],
        commonMistakes: ["Assuming v1 live event names and v2 Flux events are interchangeable."],
        securityNotes: ["Use a temporary credential for any browser connection."],
        learningNotes: ["This legacy payload-builder entry remains non-executing by design. Use Flux Conversation Observatory for the guarded /v2/listen browser workflow, shared synthetic replay, event inspection, configuration acknowledgements, metrics, and sanitized evidence exports.", "Repository tests verify the implementation boundary; an actual microphone/provider run remains manual-validation-required."],
        relatedModule: "Flux Conversation Observatory",
        chainIdeas: ["End of turn → agent decision", "Turn transcript → tool selection"],
        verifyInDocs: true,
      },
    ],
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    short: "TTS",
    goal: "Turn text into playable audio.",
    description: "Build one-shot or streaming speech synthesis requests and understand binary audio responses.",
    unlocks: ["Voice notifications", "Conversational responses", "Accessibility playback", "Approved brand voices"],
    chainIdeas: ["Customer context → response text → TTS", "LLM output → approved voice", "Event → notification audio"],
    checkpoint: ["Why is the response not transcript JSON?", "Which part of the request selects a voice?", "How does the browser play returned bytes?"],
    operations: [
      {
        id: "tts-single",
        categoryId: "text-to-speech",
        name: "Single request TTS",
        summary: "Send text and receive playable audio through the existing local route.",
        endpoint: "https://api.deepgram.com/v1/speak",
        method: "POST",
        transport: "REST JSON",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/tts",
        docsUrl: `${DOCS_ROOT}/reference/text-to-speech/speak-request`,
        parameters: [
          { name: "model", label: "Voice model", location: "query", control: "select", defaultValue: "aura-2-thalia-en", help: "Selects the voice and its language family.", options: [{ label: "Thalia · English", value: "aura-2-thalia-en" }, { label: "Helena · English", value: "aura-2-helena-en" }, { label: "Apollo · English", value: "aura-2-apollo-en" }, { label: "Nestor · Spanish", value: "aura-2-nestor-es" }, { label: "Agathe · French", value: "aura-2-agathe-fr" }, { label: "Julius · German", value: "aura-2-julius-de" }] },
          { name: "encoding", label: "Encoding", location: "query", control: "select", defaultValue: "mp3", help: "Controls the returned audio representation. The current local route returns a browser-playable format.", options: [{ label: "MP3", value: "mp3" }, { label: "Linear16", value: "linear16" }, { label: "Opus", value: "opus" }] },
          { name: "container", label: "Container", location: "query", control: "select", defaultValue: "none", help: "Some encoding/container combinations have compatibility constraints; verify production combinations in docs.", options: [{ label: "None / model default", value: "none" }, { label: "WAV", value: "wav" }, { label: "Ogg", value: "ogg" }] },
          { name: "sample_rate", label: "Sample rate", location: "query", control: "number", defaultValue: 24000, help: "Relevant for raw or specific encoded outputs. The executable lab route currently uses its tested defaults." },
          { name: "text", label: "Text", location: "body", control: "textarea", defaultValue: "API Studio turns a payload into clear, playable speech.", help: "TTS receives already-written text in a JSON body." },
        ],
        exampleBody: { text: "Hello from Deepgram." },
        exampleResponse: { content_type: "audio/*", body: "binary audio bytes" },
        responsePaths: ["response headers.content-type", "audio byte length", "local audioUrl used for browser playback"],
        whenToUse: ["You already have response text and need audio.", "A single bounded generation is enough."],
        whenNotToUse: ["You need transcription from audio.", "The response must begin before the complete text is available."],
        commonMistakes: ["Parsing the response as JSON.", "Using a voice that does not match the text language.", "Leaking the key in generated browser code."],
        securityNotes: SERVER_KEY_NOTES,
        learningNotes: ["Request body: { text }.", "Response: audio bytes, content type, and metadata.", "A direct browser-safe response is commonly converted from Blob to an object URL for playback; this lab instead returns a short-lived local playback URL so the permanent key remains server-side."],
        chainIdeas: ["LLM/customer context → TTS", "Support update → voice notification"],
        codeLabWorkflow: "tts",
        relatedModule: "Text to Speech",
      },
      {
        id: "tts-streaming",
        categoryId: "text-to-speech",
        name: "Streaming TTS",
        summary: "Explore the WebSocket control and audio event lifecycle for incremental speech output.",
        endpoint: "wss://api.deepgram.com/v1/speak",
        method: "WebSocket",
        transport: "WebSocket",
        auth: "Temporary browser token",
        status: "manual-verification-required",
        executable: false,
        docsUrl: `${DOCS_ROOT}/reference/text-to-speech/speak-streaming`,
        parameters: [
          { name: "model", label: "Voice model", location: "query", control: "text", defaultValue: "aura-2-thalia-en", help: "Selects the streaming voice." },
          { name: "text_event", label: "Text event", location: "stream", control: "json", defaultValue: JSON.stringify({ type: "Speak", text: "Stream this sentence." }, null, 2), help: "Text arrives as control messages; audio returns incrementally." },
        ],
        exampleResponse: { type: "binary audio | metadata | flushed", note: "Example response shape only." },
        responsePaths: ["binary audio frames", "control event type", "request metadata"],
        whenToUse: ["You want audio to begin while text is still being generated."],
        whenNotToUse: ["A simple one-shot response is sufficient."],
        commonMistakes: ["Failing to flush or close the stream cleanly.", "Treating audio frames as JSON."],
        securityNotes: ["Keep permanent credentials out of browser WebSocket code."],
        learningNotes: ["This is payload-building only until the streaming lifecycle is implemented and tested."],
        chainIdeas: ["Streaming LLM output → streaming TTS"],
        verifyInDocs: true,
      },
    ],
  },
  {
    id: "text-intelligence",
    name: "Text Intelligence",
    short: "READ",
    goal: "Turn existing text into business context.",
    description: "Analyze transcripts, support conversations, and notes after speech has already become text.",
    unlocks: ["Conversation summaries", "Topic routing", "Intent-aware automation", "Sentiment signals"],
    chainIdeas: ["STT transcript → summary", "Support notes → topics", "Conversation → intent + sentiment"],
    checkpoint: ["What makes this different from transcription?", "Which STT field should become the text input?", "Which signals still need human review?"],
    operations: [
      {
        id: "text-intelligence-analyze",
        categoryId: "text-intelligence",
        name: "Analyze text",
        summary: "Build a /v1/read request for summarization, topics, intents, and sentiment.",
        endpoint: "https://api.deepgram.com/v1/read",
        method: "POST",
        transport: "REST JSON",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/text-intelligence",
        docsUrl: `${DOCS_ROOT}/reference/text-intelligence/analyze-text`,
        parameters: [
          { name: "text", label: "Source text", location: "body", control: "textarea", defaultValue: "The customer called because delivery was late. They accepted a replacement and asked for an email confirmation.", help: "The input is already text: a transcript, support case, note, or conversation." },
          { name: "language", label: "Analysis language", location: "query", control: "select", defaultValue: "en", help: "The currently documented summary, topic, intent, and sentiment features are supported for English text.", options: [{ label: "English", value: "en" }] },
          { name: "summarize", label: "Summarization", location: "query", control: "toggle", defaultValue: true, help: "Requests a concise representation of the source text. Verify the current model/version value in official docs." },
          { name: "topics", label: "Topic detection", location: "query", control: "toggle", defaultValue: true, help: "Finds important subject areas in the text." },
          { name: "intents", label: "Intent recognition", location: "query", control: "toggle", defaultValue: true, help: "Identifies the action or goal expressed by the speaker." },
          { name: "sentiment", label: "Sentiment analysis", location: "query", control: "toggle", defaultValue: true, help: "Adds sentiment signals that should inform, not replace, human judgment." },
        ],
        exampleBody: { text: "Already-transcribed or source text." },
        exampleResponse: { results: { summary: { results: { summary: { text: "…" } } }, topics: { results: { topics: { segments: [] } } }, intents: { results: { intents: { segments: [] } } }, sentiments: { segments: [], average: { sentiment: "neutral" } } }, note: "Example response shape only; verify current schema." },
        responsePaths: ["metadata.request_id", "results.summary.results.summary.text", "results.topics.results.topics.segments", "results.intents.results.intents.segments", "results.sentiments.segments", "results.sentiments.average"],
        whenToUse: ["Your input is already text.", "You want structured signals after STT."],
        whenNotToUse: ["You still need to convert audio into text.", "A high-stakes decision would rely only on automated sentiment or intent."],
        commonMistakes: ["Sending audio instead of text.", "Assuming action items are a guaranteed native field.", "Treating probabilistic signals as facts."],
        securityNotes: [...SERVER_KEY_NOTES, "Minimize, redact, and bound retained conversation text."],
        learningNotes: ["Text Intelligence begins where transcription ends.", "The four exposed analysis features are documented for prerecorded English text; action items remain a downstream concept, not a native /v1/read field.", "The official Read reference currently shows unusually nested summary/topic/intent result objects. Parse defensively and verify live response shape before production use."],
        chainIdeas: ["STT transcript → analysis → CRM payload", "Support case → intent routing"],
        codeLabWorkflow: "text-intelligence",
        relatedModule: "Code Lab",
      },
    ],
  },
  {
    id: "manage",
    name: "Manage",
    short: "MGMT",
    goal: "Understand account, project, model, and usage APIs without risky mutations.",
    description: "Read-only and docs-mode management maps use stronger guardrails because these APIs can affect accounts and credentials.",
    unlocks: ["Model discovery", "Usage visibility", "Project-aware tooling", "Operational diagnostics"],
    chainIdeas: ["Model catalog → deployment selector", "Usage data → budget alert", "Project metadata → admin dashboard"],
    checkpoint: ["Why are management mutations disabled?", "Which calls are safely read-only?", "What extra authorization should an admin surface require?"],
    operations: [
      {
        id: "manage-models",
        categoryId: "manage",
        name: "List models",
        summary: "Inspect the read-only model catalog through a guarded local route.",
        endpoint: "https://api.deepgram.com/v1/models?include_outdated=false",
        method: "GET",
        transport: "REST JSON",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/models",
        docsUrl: `${DOCS_ROOT}/reference/manage/models/list`,
        parameters: [],
        exampleResponse: { stt: [], tts: [], note: "Example response shape only; the lab does not synthesize a successful Manage response." },
        responsePaths: ["models[]", "models[].name", "models[].version"],
        whenToUse: ["You need to discover currently available models."],
        whenNotToUse: ["A hard-coded, validated production model is already appropriate."],
        commonMistakes: ["Assuming every model supports every language or feature."],
        securityNotes: [...SERVER_KEY_NOTES, "Protect management routes with application-level admin authorization in production."],
        learningNotes: ["This is the only executable Manage operation in API Studio because it is documented, read-only, and does not expose account mutations."],
        chainIdeas: ["Model list → safe configuration picker"],
      },
      docsOnlyOperation({
        id: "manage-model-metadata",
        categoryId: "manage",
        name: "Get model metadata",
        summary: "Study model capability and version metadata without mutating anything.",
        endpoint: "Deepgram model metadata endpoint",
        method: "GET",
        docsUrl: `${DOCS_ROOT}/reference`,
        verifyInDocs: true,
        responsePaths: ["model identity", "languages", "capabilities", "version"],
        whenToUse: ["Validating a model before exposing it in a product."],
        whenNotToUse: ["The model contract is already fixed and tested."],
        commonMistakes: ["Inventing an ID-based endpoint without checking current reference docs."],
        securityNotes: ["Keep account-level credentials server-side."],
        learningNotes: ["Endpoint is intentionally not guessed. Verify the official reference before implementation."],
        chainIdeas: ["Metadata → compatibility warning"],
      }),
      docsOnlyOperation({
        id: "manage-projects",
        categoryId: "manage",
        name: "Projects and accounts",
        summary: "Learn how project/account scopes organize keys, usage, and access.",
        endpoint: "Deepgram Manage API",
        method: "GET",
        docsUrl: `${DOCS_ROOT}/reference`,
        responsePaths: ["projects[]", "project_id", "name"],
        whenToUse: ["Building an authenticated internal admin view."],
        whenNotToUse: ["A browser-only learning surface without admin authorization."],
        commonMistakes: ["Exposing project identifiers or management data unnecessarily."],
        securityNotes: ["Require explicit admin authorization and audit reads in production."],
        learningNotes: ["Read-only concept; no project create/update/delete route exists in this lab."],
        chainIdeas: ["Project scope → usage query"],
      }),
      docsOnlyOperation({
        id: "manage-api-keys",
        categoryId: "manage",
        name: "API key management",
        summary: "Understand key lifecycle concepts with all create, update, and delete actions disabled.",
        endpoint: "Deepgram Manage API",
        method: "Concept",
        capabilityStatus: "locked-by-design",
        docsUrl: `${DOCS_ROOT}/reference`,
        responsePaths: ["key metadata only", "scopes", "created_at"],
        whenToUse: ["Designing a privileged, audited secret-management workflow."],
        whenNotToUse: ["Any client-side UI or unauthenticated route."],
        commonMistakes: ["Returning raw keys after creation.", "Logging secrets.", "Allowing deletion without confirmation and audit."],
        securityNotes: ["Create/delete/update is disabled in API Studio.", "Use a dedicated secret manager and least-privilege roles."],
        learningNotes: ["Docs only / disabled for safety."],
        chainIdeas: ["Key metadata → rotation reminder"],
      }),
      docsOnlyOperation({
        id: "manage-usage",
        categoryId: "manage",
        name: "Usage and billing concepts",
        summary: "Map read-only operational usage and cost visibility.",
        endpoint: "Deepgram Manage API",
        method: "GET",
        docsUrl: `${DOCS_ROOT}/reference`,
        responsePaths: ["usage ranges", "request counts", "duration or cost fields"],
        whenToUse: ["Budgeting and operational monitoring."],
        whenNotToUse: ["Displaying sensitive billing context to general users."],
        commonMistakes: ["Assuming response units or billing dimensions without checking docs."],
        securityNotes: ["Limit usage/billing reads to authorized staff."],
        learningNotes: ["Endpoint and units must be verified before implementation."],
        chainIdeas: ["Usage → budget alert"],
      }),
      docsOnlyOperation({
        id: "manage-rate-limits",
        categoryId: "manage",
        name: "Rate limits",
        summary: "Plan bounded clients, backoff, and quota-aware UX using official rate-limit guidance.",
        endpoint: "Official rate limits documentation",
        method: "Concept",
        docsUrl: `${DOCS_ROOT}/docs/rate-limits`,
        responsePaths: ["HTTP status", "response headers", "retry guidance"],
        whenToUse: ["Sizing retries, concurrency, and user feedback."],
        whenNotToUse: ["As a substitute for app-level quotas and abuse protection."],
        commonMistakes: ["Retrying without jitter or a cap."],
        securityNotes: ["Rate-limit local proxy routes as well as upstream calls."],
        learningNotes: ["Docs concept; API Studio never changes account limits."],
        chainIdeas: ["429 response → bounded retry policy"],
      }),
    ],
  },
  {
    id: "self-hosted",
    name: "Self-Hosted",
    short: "SH",
    goal: "Understand enterprise deployment and control-plane choices.",
    description: "Explore why data residency, regulated workloads, latency, and operational control can justify self-hosting.",
    unlocks: ["Private-cloud deployment", "Regional data control", "Enterprise observability", "Custom operational posture"],
    chainIdeas: ["Private audio ingress → self-hosted STT → private analytics", "Regional workload → local audit pipeline"],
    conceptCards: [
      { title: "Data residency", detail: "Define where audio, transcripts, logs, and backups may live." },
      { title: "Private cloud / VPC", detail: "Place workloads within enterprise network and access boundaries." },
      { title: "Regulated industries", detail: "Map compliance, consent, retention, and audit responsibilities." },
      { title: "Latency and control", detail: "Balance proximity, capacity planning, availability, and operational ownership." },
      { title: "Model deployment", detail: "Plan approved model versions, upgrades, capacity, and rollback." },
      { title: "Observability", detail: "Keep secrets and sensitive payloads out of metrics and logs." },
      { title: "Support and operations", detail: "Clarify patching, incident response, SLAs, and escalation ownership." },
    ],
    checkpoint: ["Where does audio data live?", "Who manages upgrades?", "Which region, compliance, latency, and SLA constraints matter?", "How are secrets and logs handled?"],
    operations: [
      docsOnlyOperation({
        id: "self-hosted-architecture",
        categoryId: "self-hosted",
        name: "Deployment decision map",
        summary: "Compare familiar speech workloads with a different deployment and control plane.",
        endpoint: "Enterprise deployment",
        method: "Concept",
        docsUrl: `${DOCS_ROOT}/docs/on-prem-introduction`,
        responsePaths: ["deployment topology", "data boundary", "model/runtime version", "observability signals"],
        whenToUse: ["Residency, control, compliance, or workload scale justifies operational ownership."],
        whenNotToUse: ["A managed API already satisfies requirements with less operational burden."],
        commonMistakes: ["Assuming API compatibility guarantees identical operational behavior.", "Underestimating upgrades, capacity, and incident response."],
        securityNotes: ["Define secret distribution, network boundaries, log redaction, and operator access before deployment."],
        learningNotes: ["Think: similar speech workloads, different deployment/control plane—verify exact compatibility for the selected enterprise product."],
        chainIdeas: ["Private ingest → STT → protected business system"],
      }),
    ],
  },
  {
    id: "auth",
    name: "Auth",
    short: "AUTH",
    goal: "Authenticate safely without exposing permanent credentials.",
    description: "Learn server-side key storage, temporary token grants, and safe browser realtime authentication.",
    unlocks: ["Server API calls", "Browser realtime", "Short-lived sessions", "Redacted debugging"],
    chainIdeas: ["Server key → temporary token → Live Mic", "Admin secret store → local proxy route"],
    checkpoint: ["Where should the permanent key live?", "Why use a temporary token for browser realtime?", "Which values must the inspector redact?"],
    operations: [
      docsOnlyOperation({
        id: "auth-api-key",
        categoryId: "auth",
        name: "API key authentication",
        summary: "Use a permanent API key only inside a trusted server or local runtime.",
        endpoint: "Deepgram API request",
        method: "Concept",
        docsUrl: `${DOCS_ROOT}/docs/authenticating`,
        responsePaths: ["Authorization: Token [REDACTED]"],
        whenToUse: ["A trusted server calls Deepgram directly."],
        whenNotToUse: ["Browser bundles, client source, localStorage, generated docs, or payload previews."],
        commonMistakes: ["Using any public-prefixed Deepgram credential variable.", "Committing .env.local.", "Logging headers."],
        securityNotes: ["Store DEEPGRAM_API_KEY in .env.local for this lab.", "Production systems should use a managed secret store and least-privilege runtime access."],
        learningNotes: ["Generated examples use placeholders only."],
        chainIdeas: ["Trusted server route → Deepgram REST API"],
      }),
      {
        id: "auth-token",
        categoryId: "auth",
        name: "Temporary token grant",
        summary: "Exchange the server-side API key for a short-lived browser realtime credential.",
        endpoint: "https://api.deepgram.com/v1/auth/grant",
        method: "POST",
        transport: "REST JSON",
        auth: "Server API key",
        status: "available",
        executable: true,
        localRoute: "/api/deepgram/token",
        docsUrl: `${DOCS_ROOT}/reference/auth/tokens/grant`,
        parameters: [
          { name: "ttlSeconds", label: "TTL seconds", location: "body", control: "number", defaultValue: 60, help: "The local route bounds the requested lifetime. Use the shortest practical window and consume the token immediately." },
        ],
        exampleBody: { ttl_seconds: 60 },
        exampleResponse: { access_token: "***redacted***", expires_in: 60 },
        responsePaths: ["access_token (redacted in inspector)", "expires_in"],
        whenToUse: ["A browser needs to open a realtime Deepgram WebSocket."],
        whenNotToUse: ["A trusted server can call Deepgram directly.", "You intend to persist or reuse the token."],
        commonMistakes: ["Caching the temporary token in localStorage.", "Requesting it long before opening the socket.", "Showing the token in debug output."],
        securityNotes: ["The permanent key never leaves the server route.", "The live client receives the temporary token in memory; the inspector receives only a redacted preview."],
        learningNotes: ["Temporary credentials reduce exposure but still require careful handling."],
        chainIdeas: ["Token grant → Live Mic", "Token grant → Voice Agent session"],
        codeLabWorkflow: "temporary-token",
        relatedModule: "Live Mic",
      },
      docsOnlyOperation({
        id: "auth-browser-websocket",
        categoryId: "auth",
        name: "Browser WebSocket auth",
        summary: "Use a fresh temporary token in memory to establish a realtime session.",
        endpoint: "wss://api.deepgram.com/v1/listen",
        method: "WebSocket",
        docsUrl: `${DOCS_ROOT}/docs/live-streaming-audio`,
        responsePaths: ["socket open", "realtime events", "close code and reason"],
        whenToUse: ["Live audio originates in the browser."],
        whenNotToUse: ["The permanent API key would be required in client code."],
        commonMistakes: ["Storing the token beyond the session.", "Starting audio before the socket is open."],
        securityNotes: ["Keep temporary tokens in memory only."],
        learningNotes: ["Open the Live Mic module for the implemented token + WebSocket flow."],
        chainIdeas: ["Temporary token → streaming STT"],
      }),
      docsOnlyOperation({
        id: "auth-env-pattern",
        categoryId: "auth",
        name: ".env.local boundary",
        summary: "Keep DEEPGRAM_API_KEY in a server-only environment variable.",
        endpoint: ".env.local",
        method: "Concept",
        docsUrl: `${DOCS_ROOT}/docs/authenticating`,
        responsePaths: ["process.env.DEEPGRAM_API_KEY (server only)"],
        whenToUse: ["Local development in this Next.js lab."],
        whenNotToUse: ["Client components or NEXT_PUBLIC_ variables."],
        commonMistakes: ["Committing the file.", "Copying the value into sample code."],
        securityNotes: ["Never display, serialize, or export the key."],
        learningNotes: ["Restart the dev server after changing .env.local."],
        chainIdeas: ["Environment secret → local route → Deepgram"],
      }),
    ],
  },
];

export const API_CHAIN_PRESETS: ApiChainPreset[] = [
  {
    id: "support-call-crm",
    name: "Support Call → CRM Context",
    summary: "Turn a customer call into a useful, reviewable support record.",
    apiIds: ["stt-file", "text-intelligence-analyze"],
    steps: ["Audio upload or live call", "Speech to Text", "Summary + sentiment + intent", "CRM ticket payload", "Agent follow-up recommendation"],
    handoff: { transcript: "results.channels[0].alternatives[0].transcript", nextInput: { text: "$transcript" }, crm: { summary: "$summary", intent: "$intent", sentiment: "$sentiment" } },
    customerValue: "Less after-call work and faster, better-informed follow-up.",
    technicalRisk: "Schema drift and over-reliance on probabilistic signals; keep a human review step.",
    securityConcerns: ["Minimize retained audio", "Redact payloads", "Authorize CRM writes", "Define transcript retention"],
    suggestedFiles: ["src/app/api/deepgram/transcribe-file/route.ts", "src/app/api/deepgram/text-intelligence/route.ts", "src/app/api/crm/tickets/route.ts"],
    codeLabWorkflow: "text-intelligence",
  },
  {
    id: "voice-agent-concierge",
    name: "Voice Agent Concierge",
    summary: "Combine realtime conversation, customer lookup, approved speech, and a durable CRM note.",
    apiIds: ["voice-agent-converse", "tts-streaming", "text-intelligence-analyze"],
    steps: ["Voice Agent", "Customer lookup tool", "Text to Speech response", "Conversation summary", "CRM note"],
    handoff: { toolCall: { name: "lookup_customer", input: { phone: "$caller.phone" } }, responseContext: "$customer", finalTranscript: "$conversation.text" },
    customerValue: "Personalized service without forcing the caller through a rigid IVR tree.",
    technicalRisk: "Tool latency, session recovery, interruption handling, and incorrect customer matching.",
    securityConcerns: ["Authenticate caller before sensitive disclosure", "Constrain tools", "Redact session logs"],
    suggestedFiles: ["src/server/voice-agent/session.ts", "src/server/tools/customer-lookup.ts", "src/server/crm/conversation-note.ts"],
    codeLabWorkflow: "voice-agent",
  },
  {
    id: "meeting-intelligence",
    name: "Meeting Intelligence",
    summary: "Create a speaker-aware, searchable record with a human-owned action list.",
    apiIds: ["stt-live", "stt-file", "text-intelligence-analyze"],
    steps: ["Live Mic or Upload", "STT with diarization", "Text Intelligence", "Action-item extraction layer", "Searchable transcript"],
    handoff: { transcript: "$stt.results.channels[0].alternatives[0].transcript", words: "$stt.results.channels[0].alternatives[0].words", analysisInput: { text: "$transcript" } },
    customerValue: "Less note-taking and easier retrieval while keeping people in control of final actions.",
    technicalRisk: "Speaker attribution errors and concept-derived action items require review.",
    securityConcerns: ["Obtain recording consent", "Limit access", "Set a retention period"],
    suggestedFiles: ["src/app/api/deepgram/transcribe-file/route.ts", "src/lib/meeting-record.ts", "src/components/TranscriptReview.tsx"],
    codeLabWorkflow: "upload-audio",
  },
  {
    id: "multilingual-care",
    name: "Multilingual Customer Care",
    summary: "Route language-aware transcripts into analysis, escalation, translation, and an appropriate voice.",
    apiIds: ["stt-live", "text-intelligence-analyze", "tts-single"],
    steps: ["Language selection or multilingual STT", "Transcript", "Text Intelligence", "Translated or escalated workflow concept", "TTS response"],
    handoff: { detectedLanguage: "$stt.metadata.detected_language", transcript: "$stt.transcript", responseVoice: "$voiceByLanguage" },
    customerValue: "Serve more customers in their preferred language with clear escalation paths.",
    technicalRisk: "Language detection, translation, and voice availability vary by language and domain.",
    securityConcerns: ["Disclose automation", "Use human escalation for ambiguity", "Avoid exposing sensitive context to unnecessary services"],
    suggestedFiles: ["src/lib/language-routing.ts", "src/app/api/deepgram/tts/route.ts", "src/server/escalation.ts"],
    codeLabWorkflow: "live-mic",
  },
  {
    id: "compliance-audio-review",
    name: "Compliance-Friendly Audio Review",
    summary: "Keep a redacted, inspectable path from recording to human review.",
    apiIds: ["stt-file", "text-intelligence-analyze"],
    steps: ["Pre-recorded STT", "Redacted payload inspector", "Summary + topics", "Human review queue", "Audit log concept"],
    handoff: { requestId: "$stt.metadata.request_id", transcriptRef: "$protectedTranscriptId", review: { summary: "$summary", topics: "$topics", approved: false } },
    customerValue: "Faster review with transparent evidence and explicit human approval.",
    technicalRisk: "A summary can omit important nuance; retain a controlled link to source evidence.",
    securityConcerns: ["No raw credentials in logs", "Separate payload metadata from protected content", "Immutable audit events"],
    suggestedFiles: ["src/lib/inspection.ts", "src/server/review-queue.ts", "src/server/audit-log.ts"],
    codeLabWorkflow: "upload-audio",
  },
  {
    id: "voice-notification",
    name: "Voice Notification",
    summary: "Turn a customer event into an approved, playable or deliverable spoken message.",
    apiIds: ["tts-single"],
    steps: ["Customer event", "Template payload", "TTS", "Playable audio", "Outbound provider concept"],
    handoff: { event: { type: "appointment_reminder", customerId: "$id" }, template: "Your appointment is tomorrow at {{time}}.", tts: { text: "$renderedTemplate" } },
    customerValue: "Accessible, timely updates using a consistent approved voice.",
    technicalRisk: "Stale templates, wrong recipient matching, and delivery-provider failure.",
    securityConcerns: ["Use consented channels", "Minimize message details", "Never impersonate a real person"],
    suggestedFiles: ["src/server/notification-template.ts", "src/app/api/deepgram/tts/route.ts", "src/server/outbound-provider.ts"],
    codeLabWorkflow: "tts",
  },
];

export const API_OPERATIONS = DEEPGRAM_API_CATALOG.flatMap((category) => category.operations);

export function getApiCategory(categoryId: string) {
  return DEEPGRAM_API_CATALOG.find((category) => category.id === categoryId) ?? DEEPGRAM_API_CATALOG[0];
}

export function getApiOperation(operationId: string) {
  return API_OPERATIONS.find((operation) => operation.id === operationId) ?? DEEPGRAM_API_CATALOG[1].operations[0];
}
