import type { CapstoneProject } from "@/types/questline";

const DISCLAIMER = "Verify current Deepgram model, language, parameter, and event support in official documentation before production use.";

export const CAPSTONE_PROJECTS: CapstoneProject[] = [
  {
    id: "browser-voice-assistant",
    title: "Browser Voice Assistant",
    primaryLanguages: ["typescript", "react", "html-css"],
    clientBrief: "Build a consent-forward browser experience that acquires a temporary token, streams microphone audio, displays interim/final transcript evidence, handles interruption, requests TTS through a trusted route, and records a sanitized trace.",
    projectTree: ["src/components/VoiceAssistant.tsx", "src/lib/live-session.ts", "src/app/api/deepgram/token/route.ts", "src/app/api/deepgram/tts/route.ts", "src/lib/inspection.ts", "tests/live-session.fixture.ts"],
    acceptanceCriteria: ["Permanent API key never enters browser code", "Capture begins only after explicit action and socket readiness", "Tracks/socket/timers stop on cancel and unmount", "Interim and final transcript states are distinct", "Trace excludes tokens and raw audio"],
    architecture: ["Browser mic", "temporary-token route", "verified realtime listen flow", "customer orchestration", "server TTS route", "browser playback", "sanitized flight recorder"],
    deepgramApis: ["Temporary token grant", "Streaming Speech to Text", "Single-request Text to Speech"],
    audioAssumptions: ["Browser-selected MediaRecorder MIME must be observed, not guessed", "Capture settings are evidence, not guarantees of device quality", "Echo/interruption behavior needs representative testing"],
    failureInjection: ["Permission denied", "Expired token", "Send before OPEN", "WebSocket close", "TTS error", "Unmount during active capture"],
    evaluationPlan: ["Transcript correctness by audio segment", "Time to first transcript/final", "Interruption recovery", "Resource-cleanup test", "Human usability review"],
    testChecklist: ["Mock token route", "Simulate interim/final order", "Duplicate/close/error fixtures", "Verify redaction", "Manual microphone and keyboard test", DISCLAIMER],
    impact: { technicalArtifact: "Typed browser voice session with guarded routes and trace", customerExplanation: "A reproducible reference for client/server boundaries and realtime cleanup", businessValue: "Reduces browser integration and incident time", reusableLearning: "Event lifecycle, temporary auth, audio MIME, and observability", nextImprovement: "Connect measured latency and a representative evaluation set" },
    relatedCodeLabWorkflowId: "live-mic",
    status: "docs-verification-required",
  },
  {
    id: "batch-call-intelligence",
    title: "Batch Call Intelligence Service",
    primaryLanguages: ["python", "sql"],
    clientBrief: "Design a FastAPI-style upload service that transcribes bounded recordings, analyzes finalized text, stores reviewable results, and emits evaluation evidence.",
    projectTree: ["app/main.py", "app/routes/uploads.py", "app/services/deepgram.py", "app/repositories/transcripts.py", "migrations/001_transcripts.sql", "tests/fixtures/", "tests/test_transcription.py"],
    acceptanceCriteria: ["Upload and request limits are explicit", "File bytes remain binary", "Provider errors are sanitized", "Transcript and request ID are stored transactionally", "Analysis is docs-gated and human-reviewable"],
    architecture: ["Client upload", "Python API", "Deepgram prerecorded STT", "Text Intelligence", "database", "review UI"],
    deepgramApis: ["Prerecorded file Speech to Text", "Text Intelligence"],
    audioAssumptions: ["Representative call formats and channels are inventoried", "Diarization is tested only on multi-speaker audio", "Retention policy controls source audio separately"],
    failureInjection: ["Oversized upload", "Unsupported MIME", "Timeout", "Empty transcript", "Database rollback", "Analysis feature error"],
    evaluationPlan: ["WER with human reference", "Domain-term accuracy", "Speaker-label review", "Processing latency", "Summary/intent human rating"],
    testChecklist: ["Payload construction unit test", "Mocked provider integration", "File fixture matrix", "Database constraint/retention test", "Security/redaction review", DISCLAIMER],
    impact: { technicalArtifact: "Batch transcription/evaluation service skeleton", customerExplanation: "A controlled path from recording to searchable business context", businessValue: "Reduces manual after-call review", reusableLearning: "Python environments, binary uploads, evaluation, and persistence", nextImprovement: "Add background jobs and representative volume testing" },
    relatedCodeLabWorkflowId: "upload-audio",
    status: "conceptual",
  },
  {
    id: "go-streaming-gateway",
    title: "High-Concurrency Streaming Gateway",
    primaryLanguages: ["go"],
    clientBrief: "Design a Go gateway that owns many streaming sessions, isolates writes/reads, propagates cancellation, applies backpressure, records evidence, and shuts down gracefully.",
    projectTree: ["cmd/gateway/main.go", "internal/session/session.go", "internal/audio/queue.go", "internal/transport/websocket.go", "internal/trace/trace.go", "internal/session/session_test.go"],
    acceptanceCriteria: ["One owner writes each socket", "All loops observe context cancellation", "Audio buffers have explicit ownership", "Queues are bounded", "Shutdown waits for sessions without hanging"],
    architecture: ["Media ingress", "session manager", "bounded audio queues", "verified WebSocket adapter", "event router", "observability/export"],
    deepgramApis: ["Streaming Speech to Text; client library and exact auth flow require verification"],
    audioAssumptions: ["Ingress format is negotiated before streaming", "Chunk duration is bounded and measured", "Buffer reuse cannot mutate in-flight chunks"],
    failureInjection: ["Slow consumer", "Network disconnect", "Context cancellation", "Buffer reuse", "Out-of-order event", "Shutdown during load"],
    evaluationPlan: ["Concurrent session ceiling", "Goroutine/memory stability", "p50/p95 event latency", "Drop/backpressure behavior", "Trace completeness"],
    testChecklist: ["Race/cancellation tests", "httptest for REST boundaries", "Simulated WebSocket events", "Long-session soak concept", "Graceful shutdown", DISCLAIMER],
    impact: { technicalArtifact: "Session/concurrency architecture with tests", customerExplanation: "A clear ownership model for reliable high-volume streaming", businessValue: "Supports scale without hidden goroutine or buffer failures", reusableLearning: "Contexts, channels, slices, backpressure, and shutdown", nextImprovement: "Verify/select the production WebSocket library and load-test infrastructure" },
    relatedCodeLabWorkflowId: "live-mic",
    status: "docs-verification-required",
  },
  {
    id: "enterprise-dotnet-api",
    title: "Enterprise Voice API",
    primaryLanguages: ["csharp"],
    clientBrief: "Create an ASP.NET architecture for typed file transcription and TTS with configuration, dependency injection, cancellation, testing, and sanitized operational evidence.",
    projectTree: ["Program.cs", "Controllers/VoiceController.cs", "Clients/DeepgramClient.cs", "Models/", "Diagnostics/TraceSanitizer.cs", "Tests/VoiceApi.Tests/"],
    acceptanceCriteria: ["HttpClient lifetime is managed", "Configuration is environment/secret-store backed", "CancellationToken reaches every I/O call", "Streams are disposed", "Typed responses distinguish JSON from audio bytes"],
    architecture: ["Enterprise client", "ASP.NET controller", "injected provider client", "Deepgram STT/TTS", "typed response", "central diagnostics"],
    deepgramApis: ["Prerecorded Speech to Text", "Single-request Text to Speech"],
    audioAssumptions: ["Upload type/size validated", "TTS encoding requested explicitly", "Contact-center media adaptation remains customer/third-party work"],
    failureInjection: ["Missing configuration", "Cancellation", "Disposed stream", "JSON naming mismatch", "Provider non-2xx", "Dependency lifetime mismatch"],
    evaluationPlan: ["Contract tests", "Cancellation duration", "Connection reuse", "Transcript fixture checks", "TTS content type/byte count"],
    testChecklist: ["Fake HttpMessageHandler", "Controller upload test", "Binary TTS response test", "Configuration startup test", "Redaction test", DISCLAIMER],
    impact: { technicalArtifact: "Enterprise-ready typed integration skeleton", customerExplanation: "A conventional ASP.NET boundary that fits existing operational practices", businessValue: "Reduces integration risk in strongly typed enterprise stacks", reusableLearning: "DI, HttpClient, streams, cancellation, and typed JSON", nextImprovement: "Add customer-specific auth, rate limits, and deployment SLOs" },
    relatedCodeLabWorkflowId: "upload-audio",
    status: "conceptual",
  },
  {
    id: "native-audio-stream",
    title: "Native Audio Stream Prototype",
    primaryLanguages: ["cpp"],
    clientBrief: "Build a C++20 project skeleton that models device callbacks, owned PCM buffers, bounded queues, sample conversion, worker threads, and a docs-gated WebSocket boundary.",
    projectTree: ["CMakeLists.txt", "src/main.cpp", "src/audio/capture.hpp", "src/audio/ring_buffer.hpp", "src/network/stream_client.hpp", "tests/audio_buffer_tests.cpp"],
    acceptanceCriteria: ["Audio callback never blocks or allocates unboundedly", "Buffer ownership is explicit", "Shutdown order is deterministic", "Sample conversion is tested", "No unverified SDK/library method is presented as working"],
    architecture: ["Audio device callback", "owned int16 buffer", "bounded ring/queue", "network worker", "verified WebSocket adapter concept", "event consumer"],
    deepgramApis: ["Streaming Speech to Text architecture; no official C++ SDK assumed"],
    audioAssumptions: ["PCM signedness, endianness, sample rate, and channels are explicit", "Device/API selection is customer-specific", "PortAudio-style callback is an architecture concept only"],
    failureInjection: ["Dangling buffer", "Blocking callback", "Sample-rate mismatch", "Signed/unsigned conversion", "Thread race", "Linker configuration mismatch"],
    evaluationPlan: ["Callback duration", "Queue underrun/overrun", "Sample integrity", "Shutdown stability", "End-to-end latency after network implementation"],
    testChecklist: ["Clean CMake/Ninja configure/build", "Buffer conversion tests", "Repeated start/stop", "Thread ownership review", "Docs/library verification gate"],
    impact: { technicalArtifact: "Native audio ownership and build-system prototype", customerExplanation: "A safe foundation for performance-sensitive media infrastructure", businessValue: "Makes low-level latency and reliability risks visible", reusableLearning: "RAII, buffers, callbacks, queues, compilation, and linking", nextImprovement: "Select verified native dependencies and connect a controlled integration test" },
    relatedCodeLabWorkflowId: "live-mic",
    status: "conceptual",
  },
  {
    id: "diagnostic-toolkit",
    title: "Diagnostic Toolkit",
    primaryLanguages: ["powershell", "shell"],
    clientBrief: "Create clearly separated PowerShell and Bash runbooks for environment, health, auth, file transcription, audio conversion, connectivity, and sanitized evidence collection.",
    projectTree: ["diagnostics/README.md", "diagnostics/Test-VoiceEnvironment.ps1", "diagnostics/transcribe-file.ps1", "diagnostics/check-voice-env.sh", "diagnostics/transcribe-file.sh", "diagnostics/fixtures/"],
    acceptanceCriteria: ["Shell is detected/labeled", "Credential existence is checked without printing value", "Commands fail on non-2xx/exit code", "Paths are quoted and resolved", "Binary and JSON outputs are handled separately"],
    architecture: ["Operator terminal", "runtime/network checks", "raw REST request", "sanitized evidence bundle", "client-facing runbook"],
    deepgramApis: ["Health/account check through existing route", "Prerecorded Speech to Text", "Temporary token grant"],
    audioAssumptions: ["ffmpeg is optional and availability is checked", "Conversion never overwrites the source without explicit choice", "Output format metadata matches bytes"],
    failureInjection: ["Wrong shell", "Missing PATH", "Stale environment", "Wrong working directory", "Unsupported MIME", "Blocked egress"],
    evaluationPlan: ["Runbook completion rate", "Time to isolate failing layer", "Evidence completeness", "Secret-scan result", "Cross-shell repeatability"],
    testChecklist: ["Fresh terminal", "Directory with spaces", "Missing dependency", "Non-2xx response", "No secrets in output/history", DISCLAIMER],
    impact: { technicalArtifact: "Cross-shell diagnostic pack", customerExplanation: "A reproducible evidence-first checklist for common environment and connectivity issues", businessValue: "Shortens support and integration cycles", reusableLearning: "Shell semantics, PATH, files, HTTP, and client communication", nextImprovement: "Automate a sanitized incident attachment format" },
    relatedCodeLabWorkflowId: "transcribe-url",
    status: "conceptual",
  },
  {
    id: "transcript-data-model",
    title: "Transcript Data Model",
    primaryLanguages: ["sql"],
    clientBrief: "Design a queryable and retention-aware relational model for sessions, speakers, words, turns, tool calls, traces, and evaluation outcomes.",
    projectTree: ["migrations/001_sessions.sql", "migrations/002_transcript_words.sql", "migrations/003_tools_evaluations.sql", "queries/session_timeline.sql", "queries/quality_segments.sql", "tests/retention-fixture.sql"],
    acceptanceCriteria: ["Tenant/session keys are explicit", "Final versus interim data cannot silently duplicate", "Word/turn ordering is stable", "Indexes match query paths", "Retention removes dependent records safely"],
    architecture: ["Application ingestion", "transactional transcript repository", "normalized session/word/turn/tool/evaluation tables", "search/analytics queries", "retention job"],
    deepgramApis: ["Consumes finalized outputs and metadata from Speech to Text; SQL does not call Deepgram"],
    audioAssumptions: ["Raw audio storage is separate and opt-in", "Word timestamps use explicit units", "Channel/speaker meaning is preserved"],
    failureInjection: ["Duplicate final event", "Timezone mismatch", "Missing index", "JSON type mismatch", "Orphaned child rows", "Out-of-order words"],
    evaluationPlan: ["Constraint/duplicate tests", "Query plan at representative volume", "Retention correctness", "Per-segment quality queries", "Tenant isolation review"],
    testChecklist: ["Apply/rollback migrations", "Insert deterministic fixture", "Explain query plan", "Run retention fixture", "Audit child counts"],
    impact: { technicalArtifact: "Migration and query design", customerExplanation: "A durable model that keeps transcript evidence searchable and governable", businessValue: "Enables product workflows, quality analysis, and controlled retention", reusableLearning: "Schema design, indexes, transactions, JSON, and observability", nextImprovement: "Validate engine-specific search and partitioning needs" },
    relatedCodeLabWorkflowId: "transcribe-url",
    status: "conceptual",
  },
  {
    id: "legacy-php-adapter",
    title: "Legacy Customer Adapter",
    primaryLanguages: ["php", "html-css"],
    clientBrief: "Create a server-side PHP adapter for bounded uploads and raw REST transcription that works within web-server/PHP-FPM limits without exposing credentials.",
    projectTree: ["public/index.php", "src/DeepgramClient.php", "src/UploadValidator.php", "templates/transcript.php", ".env.example", "tests/fixtures/"],
    acceptanceCriteria: ["Browser posts only to the PHP server", "Upload errors/limits are clear", "Temporary file is consumed before request end", "cURL status/timeouts are checked", "Permanent key is server environment only"],
    architecture: ["Semantic upload form", "PHP upload validator", "server-side cURL adapter", "Deepgram prerecorded STT", "sanitized transcript response"],
    deepgramApis: ["Prerecorded file Speech to Text through raw REST; no PHP SDK assumed"],
    audioAssumptions: ["Server limits are discovered before POC", "MIME/content are validated", "Long recordings may require a worker/object-storage design"],
    failureInjection: ["post_max_size exceeded", "Temp file missing", "cURL certificate failure", "Double-encoded JSON", "Request timeout", "Environment unavailable to PHP-FPM"],
    evaluationPlan: ["Supported size/format matrix", "Status/error fidelity", "Transcript fixture correctness", "Worker occupancy", "Security review"],
    testChecklist: ["Small/limit/over-limit upload", "Missing cURL extension", "Non-2xx provider response", "No key in HTML/log/export", "Shared-hosting constraints documented", DISCLAIMER],
    impact: { technicalArtifact: "PHP server adapter and troubleshooting guide", customerExplanation: "A safe integration path for an existing stack without forcing a platform rewrite", businessValue: "Expands adoption and reduces migration pressure", reusableLearning: "Request lifecycle, uploads, cURL, limits, and server configuration", nextImprovement: "Move long-running work to a bounded queue when the platform supports it" },
    relatedCodeLabWorkflowId: "upload-audio",
    status: "docs-verification-required",
  },
];
