import type { ClientIncident, QuestlineLanguageId } from "@/types/questline";

type IncidentSeed = {
  id: string;
  title: string;
  language: QuestlineLanguageId;
  framework: string;
  ide: string;
  operatingSystem: string;
  symptoms: string[];
  rootCause: string;
  clue: string;
  resolution: string[];
  prevention: string[];
  classification: ClientIncident["classification"];
  difficulty?: ClientIncident["difficulty"];
  misleading?: string[];
};

const SEEDS: IncidentSeed[] = [
  { id: "python-wrong-venv", title: "Package exists, import fails", language: "python", framework: "FastAPI", ide: "VSCodium", operatingSystem: "Windows", symptoms: ["ImportError in the app", "pip reports the package is installed"], rootCause: "The integrated terminal installed into a global interpreter while the run configuration uses the project virtual environment.", clue: "sys.executable differs between the terminal and running process.", resolution: ["Select the project interpreter", "Install from the project requirements in that environment", "Restart the run/debug session"], prevention: ["Commit dependency metadata", "Document interpreter selection", "Print interpreter path in safe diagnostics"], classification: "integration-bug" },
  { id: "python-blocked-event-loop", title: "Realtime socket closes after file processing", language: "python", framework: "asyncio service", ide: "PyCharm concept", operatingSystem: "Linux", symptoms: ["WebSocket stops receiving", "Event loop lag rises during local file reads"], rootCause: "A blocking file/audio operation runs inside the asyncio event loop and prevents timely socket work.", clue: "Event-loop lag aligns with synchronous read/processing duration.", resolution: ["Use non-blocking streaming or move bounded blocking work off the event loop", "Add deadlines and cancellation", "Measure loop lag"], prevention: ["Review every call in async paths", "Test with slow fixtures", "Bound queues and worker time"], classification: "coding-bug", difficulty: "advanced" },

  { id: "typescript-client-secret", title: "API key appears in browser bundle", language: "typescript", framework: "Next.js", ide: "VSCodium", operatingSystem: "Windows", symptoms: ["Provider calls work directly from browser", "Authorization is visible in DevTools"], rootCause: "A permanent key was read by client code or exposed through a public environment variable.", clue: "The credential-bearing module is inside a client-component import graph.", resolution: ["Remove the credential from client code and rotate it", "Move provider calls to a guarded server route", "Use temporary browser tokens only for the verified realtime flow"], prevention: ["Disallow public provider-key variables", "Scan client bundles", "Review client/server boundaries"], classification: "integration-bug", difficulty: "client-impact" },
  { id: "typescript-send-before-open", title: "Audio is sent before the WebSocket opens", language: "typescript", framework: "Browser WebSocket", ide: "Browser DevTools", operatingSystem: "Windows/macOS", symptoms: ["InvalidStateError while sending", "Recorder produces chunks but no transcript events arrive"], rootCause: "MediaRecorder starts before the WebSocket OPEN event and its first chunks are sent while readyState is CONNECTING.", clue: "The first dataavailable timestamp precedes websocket_open in the trace.", resolution: ["Open the socket first", "Start capture only from the verified open callback", "Stop capture and surface a clear error if connection fails"], prevention: ["Model connection/capture as a state machine", "Test delayed-open and failed-open fixtures", "Record readyState and chunk timing"], classification: "coding-bug" },
  { id: "react-render-update", title: "State update during another component render", language: "react", framework: "React/Next.js", ide: "VSCodium", operatingSystem: "Windows", symptoms: ["React warns that one component updated while another rendered", "Mic UI becomes inconsistent"], rootCause: "A child calls a parent state setter while rendering instead of from an event, effect, or explicit callback boundary.", clue: "The stack points to a setter invoked in the component body.", resolution: ["Move the update into the originating event/effect", "Keep render pure", "Model socket/mic resources in refs and lifecycle state"], prevention: ["Treat render as calculation only", "Test mount/unmount and callbacks", "Use explicit state-machine transitions"], classification: "coding-bug" },

  { id: "go-goroutine-leak", title: "Streaming memory grows after sessions close", language: "go", framework: "Go service", ide: "GoLand concept", operatingSystem: "Linux", symptoms: ["Goroutine count rises", "Closed sessions retain buffers"], rootCause: "The receive/send goroutines ignore context cancellation and remain blocked on channels after the session exits.", clue: "A goroutine profile shows loops waiting on channels for completed session IDs.", resolution: ["Propagate one session context", "Select on ctx.Done in every loop", "Close channels from their owning sender and wait for workers"], prevention: ["Track goroutine count by session", "Test cancellation and disconnect", "Use bounded queues"], classification: "coding-bug", difficulty: "advanced" },
  { id: "go-buffer-reuse", title: "Audio chunks change after enqueue", language: "go", framework: "Streaming gateway", ide: "GoLand concept", operatingSystem: "Linux", symptoms: ["Transcripts are intermittently corrupted", "Chunk hashes change between capture and send"], rootCause: "A []byte slice references a backing array that is reused before the writer goroutine consumes it.", clue: "Copying the chunk before enqueue makes the issue disappear.", resolution: ["Transfer ownership or copy into an owned buffer", "Return buffers to a pool only after send completes"], prevention: ["Document slice ownership", "Run race tests", "Include deterministic chunk-integrity assertions"], classification: "audio-problem", difficulty: "advanced" },

  { id: "csharp-httpclient-lifetime", title: "Sockets exhaust under load", language: "csharp", framework: "ASP.NET", ide: "Visual Studio", operatingSystem: "Windows Server", symptoms: ["Requests time out under concurrency", "Many outbound connections remain in transient states"], rootCause: "A new HttpClient is created and disposed per request instead of using an injected managed lifetime.", clue: "Controller code constructs HttpClient directly on every call.", resolution: ["Use the configured HttpClient factory or a safely reused client", "Set explicit deadlines", "Measure connection reuse"], prevention: ["Centralize provider client registration", "Load test connection behavior", "Review dependency lifetimes"], classification: "integration-bug" },
  { id: "csharp-cancellation-missing", title: "Client disconnect does not stop upstream work", language: "csharp", framework: "ASP.NET", ide: "Rider concept", operatingSystem: "Linux container", symptoms: ["Deepgram and tool work continues after caller cancels", "Worker concurrency remains high"], rootCause: "The controller CancellationToken is not propagated through stream reads and outbound calls.", clue: "Nested methods accept no token or use CancellationToken.None.", resolution: ["Thread the request token through every async boundary", "Handle cancellation distinctly from failures", "Dispose streams/responses"], prevention: ["Require token parameters", "Test cancellation", "Observe canceled versus completed work"], classification: "coding-bug" },

  { id: "powershell-bash-syntax", title: "Working curl example fails in PowerShell", language: "powershell", framework: "CLI diagnostic", ide: "Windows Terminal", operatingSystem: "Windows", symptoms: ["Backslash continuation is treated as text", "Environment variable expansion fails"], rootCause: "A Bash command was pasted into PowerShell without translating quoting, continuation, and environment syntax.", clue: "The example uses backslash continuations and $DEEPGRAM_API_KEY rather than PowerShell syntax.", resolution: ["Use a PowerShell-native example or invoke curl.exe explicitly", "Use $env:DEEPGRAM_API_KEY", "Inspect status and output without printing credentials"], prevention: ["Label shell examples", "Maintain separate Bash and PowerShell snippets", "Test runbooks in the documented shell"], classification: "integration-bug" },
  { id: "powershell-stale-env", title: "Key exists in one terminal only", language: "powershell", framework: "CLI diagnostic", ide: "VSCodium", operatingSystem: "Windows", symptoms: ["Health succeeds in one terminal", "App process reports missing key"], rootCause: "The environment variable was set after the app process started or only in another process scope.", clue: "The process start time precedes the variable assignment.", resolution: ["Set configuration in the intended process/runtime", "Restart the application", "Confirm existence without printing the value"], prevention: ["Document environment scope", "Restart after config changes", "Use managed deployment configuration"], classification: "integration-bug" },

  { id: "shell-working-directory", title: "File upload runs from the wrong directory", language: "shell", framework: "Bash diagnostic", ide: "Terminal", operatingSystem: "Linux", symptoms: ["curl cannot read the audio path", "The request body is empty or command exits before sending"], rootCause: "The script assumes a working directory that differs in CI/container execution.", clue: "pwd and resolved file path do not match the runbook assumption.", resolution: ["Resolve paths relative to the script or require an absolute path", "Fail before calling the API when the file is absent"], prevention: ["Quote paths", "Print sanitized resolved path metadata", "Test from another directory"], classification: "integration-bug" },
  { id: "shell-json-pipe", title: "Pipeline changes JSON before inspection", language: "shell", framework: "curl/jq diagnostic", ide: "Terminal", operatingSystem: "Linux", symptoms: ["Raw evidence cannot be reproduced", "Downstream output omits error fields"], rootCause: "A text-processing pipeline filters or reformats the response before status and raw sanitized evidence are preserved.", clue: "Removing the pipe reveals the provider error object.", resolution: ["Capture status, headers, and sanitized raw body first", "Transform a copy", "Use pipefail and check every exit code"], prevention: ["Separate evidence capture from presentation", "Add failure fixtures", "Keep binary output out of text pipelines"], classification: "coding-bug" },

  { id: "sql-session-index", title: "Transcript lookup slows as data grows", language: "sql", framework: "PostgreSQL concept", ide: "Database client", operatingSystem: "Managed database", symptoms: ["Session timeline query performs a table scan", "Latency grows with retention volume"], rootCause: "The schema lacks an index on the tenant/session/time access path.", clue: "EXPLAIN shows a sequential scan and large row estimate.", resolution: ["Add an index matching the actual filter/order", "Re-run the query plan with representative volume", "Keep tenant boundary in the key"], prevention: ["Capture access patterns before schema finalization", "Test realistic volume", "Monitor query latency"], classification: "data-problem" },
  { id: "sql-retention-orphans", title: "Retention deletes sessions but leaves words", language: "sql", framework: "Relational schema", ide: "Migration tool", operatingSystem: "Database server", symptoms: ["Storage continues growing", "Words reference missing business context"], rootCause: "Retention removes parent records without a foreign-key cascade or explicit child deletion transaction.", clue: "Child counts remain after a retention batch.", resolution: ["Add and validate referential rules", "Delete within a bounded transaction", "Audit affected row counts"], prevention: ["Test retention as part of migrations", "Document ownership and legal policy", "Monitor orphan counts"], classification: "data-problem" },

  { id: "cpp-dangling-buffer", title: "Audio callback reads destroyed memory", language: "cpp", framework: "Native audio prototype", ide: "VSCodium/CMake", operatingSystem: "Windows", symptoms: ["Intermittent crash during shutdown", "Corrupted samples near session end"], rootCause: "A callback retains a pointer/reference to an object destroyed before the audio stream stops.", clue: "The crash disappears when shutdown order is changed or ownership is extended.", resolution: ["Stop callbacks before destroying shared state", "Use RAII ownership with explicit lifetime order", "Join worker threads"], prevention: ["Document ownership", "Use sanitizers where available", "Stress repeated start/stop"], classification: "coding-bug", difficulty: "advanced" },
  { id: "cpp-linker-audio-lib", title: "Headers compile, audio library will not link", language: "cpp", framework: "CMake/Ninja", ide: "VSCodium", operatingSystem: "Windows", symptoms: ["Compilation succeeds", "Linker reports unresolved audio symbols"], rootCause: "The target includes headers but does not link the matching library/configuration/architecture.", clue: "Verbose link command omits or mismatches the required library.", resolution: ["Inspect target_link_libraries and discovered package", "Match Debug/Release and architecture", "Reconfigure a clean build tree"], prevention: ["Use imported CMake targets", "Keep build configurations explicit", "Test clean configure/build"], classification: "integration-bug" },

  { id: "php-upload-limit", title: "Large audio never reaches PHP handler", language: "php", framework: "PHP-FPM", ide: "VS Code", operatingSystem: "Linux hosting", symptoms: ["$_FILES is empty", "Small files work", "Application logging shows no provider request"], rootCause: "Web server or php.ini upload/body limit rejects the request before application code.", clue: "Request size exceeds effective post_max_size/upload_max_filesize or proxy limit.", resolution: ["Confirm every body-size boundary", "Return a clear client error", "Prefer bounded direct object-storage workflows for large recordings where appropriate"], prevention: ["Document supported limits", "Test boundary sizes", "Monitor rejected uploads"], classification: "infrastructure" },
  { id: "php-double-json", title: "Provider receives JSON string inside JSON", language: "php", framework: "Laravel/PHP", ide: "VS Code", operatingSystem: "Linux", symptoms: ["Request is rejected or text field is missing", "Payload preview contains escaped JSON"], rootCause: "The body is JSON-encoded twice by application and HTTP wrapper.", clue: "Sanitized wire payload begins with a quoted brace instead of an object.", resolution: ["Encode exactly once", "Set Content-Type explicitly", "Assert the final sanitized request shape"], prevention: ["Unit-test payload construction", "Separate domain object from transport serialization", "Inspect request bytes"], classification: "coding-bug" },

  { id: "infra-proxy-idle-timeout", title: "Production WebSocket closes at 60 seconds", language: "typescript", framework: "Browser plus reverse proxy", ide: "Browser/operations console", operatingSystem: "Cloud deployment", symptoms: ["Local streaming remains open", "Production closes predictably at 60 seconds", "Close may appear as 1006"], rootCause: "A reverse proxy/load balancer idle or maximum-connection timeout closes the upgraded connection.", clue: "Disconnect timing is fixed and proxy logs align with it.", resolution: ["Confirm the media path and upgrade configuration", "Set supported timeout/keepalive policy", "Test through the real production path"], prevention: ["Document streaming infrastructure requirements", "Synthetic long-session test", "Alert on close-code/duration patterns"], classification: "infrastructure", difficulty: "client-impact" },
  { id: "infra-container-localhost", title: "Container cannot reach host service", language: "shell", framework: "Containerized adapter", ide: "Docker CLI", operatingSystem: "Windows/Linux", symptoms: ["Connection refused to localhost", "Host browser can reach the service"], rootCause: "localhost inside the container refers to the container, not the host or another service.", clue: "The target process is absent from the container network namespace.", resolution: ["Use the correct service DNS/host gateway for the deployment", "Publish/expose only required ports", "Verify from inside the container"], prevention: ["Architecture diagram labels namespaces", "Container integration test", "Avoid hard-coded localhost"], classification: "infrastructure" },
  { id: "infra-firewall-egress", title: "Outbound Deepgram connection blocked", language: "powershell", framework: "Enterprise network", ide: "Operations terminal", operatingSystem: "Windows Server", symptoms: ["DNS may resolve but TLS connection times out", "Other internal endpoints work"], rootCause: "Outbound firewall/proxy policy blocks the required destination or WebSocket upgrade.", clue: "Network evidence fails before any HTTP/Deepgram response exists.", resolution: ["Validate DNS, TCP/TLS, proxy, and egress policy with network owners", "Do not retry indefinitely", "Communicate the failed layer clearly"], prevention: ["Preflight network requirements", "Health check from deployment environment", "Monitor connection-stage failures"], classification: "infrastructure" },
  { id: "infra-secret-rotation", title: "Deployment breaks after secret rotation", language: "csharp", framework: "Cloud service", ide: "Deployment console", operatingSystem: "Cloud runtime", symptoms: ["401 begins after scheduled rotation", "Some replicas still work"], rootCause: "Replicas cache or receive inconsistent secret versions and were not refreshed atomically.", clue: "Failures correlate with replica/config version rather than request payload.", resolution: ["Confirm secret version per replica without exposing value", "Roll/reload safely", "Revoke old credentials after verified cutover"], prevention: ["Document rotation procedure", "Use staged health checks", "Alert on auth failure by deployment version"], classification: "infrastructure", difficulty: "client-impact" },
];

function buildIncident(seed: IncidentSeed): ClientIncident {
  return {
    id: seed.id,
    title: seed.title,
    language: seed.language,
    framework: seed.framework,
    ide: seed.ide,
    operatingSystem: seed.operatingSystem,
    difficulty: seed.difficulty ?? "intermediate",
    status: "simulated",
    symptoms: seed.symptoms,
    evidence: [
      { label: "Visible symptom", type: "log", content: seed.symptoms.join(" | ") },
      { label: "Architecture clue", type: "architecture", content: seed.clue },
      { label: "Sanitized payload boundary", type: "payload", content: "Authorization: ***redacted***; preserve status, request/session ID when available, MIME, byte count, timing, and close code." },
    ],
    architecture: ["User-visible symptom", `${seed.framework} runtime`, "Customer trust/network boundary", "Deepgram or downstream dependency", "Sanitized evidence and fallback"],
    hiddenRootCause: seed.rootCause,
    misleadingClues: seed.misleading ?? ["The last edited code file", "A model/configuration toggle unrelated to the failing layer"],
    investigationSteps: ["Reproduce the user-visible symptom", "Locate the last confirmed-good boundary", "Inspect runtime/configuration and data type", "Follow status, timing, IDs, and cleanup evidence backward", "Change one variable and rerun the deterministic check"],
    resolution: seed.resolution,
    prevention: seed.prevention,
    clientFacingExplanation: `The failure was isolated to ${seed.rootCause.toLowerCase()} We confirmed it using ${seed.clue.toLowerCase()} The correction preserves credentials and adds a repeatable check so the same class of issue is visible earlier.`,
    classification: seed.classification,
  };
}

export const CLIENT_INCIDENTS: ClientIncident[] = SEEDS.map(buildIncident);

export function getClientIncident(id: string) {
  return CLIENT_INCIDENTS.find((incident) => incident.id === id) ?? CLIENT_INCIDENTS[0];
}
