import type { IdeTrack } from "@/types/questline";

export const IDE_TRACKS: IdeTrack[] = [
  {
    id: "vscodium-vscode",
    label: "VSCodium / VS Code",
    status: "executable",
    learnerContext: "Primary cross-language workspace for TypeScript, Python, PowerShell, and C++20 with an integrated terminal.",
    whatClientSees: "The editor may look correct while the terminal, debugger, language server, and running process use different interpreters, working directories, or environment scopes.",
    likelyMistakes: ["Wrong Python interpreter", "Opening a subfolder instead of the repository root", "Editing a browser file while expecting server-only environment access", "Build task uses a different CMake preset than the debugger"],
    confirmEnvironment: ["Inspect the status-bar interpreter/toolchain", "Run the language/runtime version in the integrated terminal", "Confirm the workspace root and current directory", "Inspect the actual launch/task configuration"],
    dependencyLocation: "package lock/node_modules, Python virtual environment, go.mod, .csproj/NuGet cache, or CMake build tree depending on the active track.",
    entryPoint: "Read package scripts, launch configuration, task definition, or project README before assuming the first open file is the entry point.",
    breakpointLocations: ["Trusted server route before provider fetch", "Response status check", "WebSocket open/message/close handlers", "Audio capture and cleanup boundaries"],
    evidenceLocations: ["Integrated terminal", "Debug Console", "Variables/Call Stack", "Browser Network/WebSocket frames", "Next.js server logs"],
    diagnosticCommands: ["Get-Location", "Get-Command node, python, cmake, ninja", "node --version", "python -c \"import sys; print(sys.executable)\"", "cmake --build build --verbose"],
  },
  {
    id: "visual-studio",
    label: "Visual Studio",
    status: "conceptual",
    learnerContext: "Enterprise .NET solution and ASP.NET execution model.",
    whatClientSees: "A solution may build locally but read different launchSettings, appsettings, user secrets, or dependency-injection registrations after deployment.",
    likelyMistakes: ["Wrong startup project", "Secret stored in committed appsettings", "Scoped service captured by a singleton", "CancellationToken omitted from controller-to-client calls"],
    confirmEnvironment: ["Confirm startup project and launch profile", "Inspect effective configuration providers", "Check target framework and NuGet restore", "Inspect service lifetimes"],
    dependencyLocation: ".csproj/package references, NuGet cache, solution projects, and deployment configuration providers.",
    entryPoint: "Program.cs and the selected launch profile compose configuration, dependency injection, middleware, and endpoints.",
    breakpointLocations: ["Controller action", "Injected Deepgram client wrapper", "HttpClient response mapping", "Stream disposal and exception handler"],
    evidenceLocations: ["Output window", "Exception Settings", "Locals/Watch/Call Stack", "ASP.NET logs", "Network trace"],
    diagnosticCommands: ["dotnet --info", "dotnet restore", "dotnet build", "dotnet run --launch-profile <PROFILE>"],
  },
  {
    id: "jetbrains",
    label: "JetBrains IDE concepts",
    status: "conceptual",
    learnerContext: "PyCharm, Rider, and GoLand share strong project/runtime awareness but use language-specific run configurations.",
    whatClientSees: "The IDE index can resolve code even when the selected run configuration points at the wrong interpreter, module, working directory, or environment file.",
    likelyMistakes: ["Wrong project interpreter/SDK", "Run configuration omits environment variables", "Test and application use different working directories", "Debugger attaches to the wrong process"],
    confirmEnvironment: ["Inspect Project Interpreter/SDK", "Open the active Run Configuration", "Confirm module and working directory", "Compare IDE terminal and run-process environments"],
    dependencyLocation: "Python environment, Go module cache, or NuGet/project model selected by the IDE.",
    entryPoint: "The active Run Configuration names the module, executable/script, arguments, and environment.",
    breakpointLocations: ["Request construction", "Concurrency/cancellation boundary", "Response decode", "Cleanup/finally/defer path"],
    evidenceLocations: ["Run/Debug tool windows", "Variables and async stack", "HTTP client/log console", "Profiler where available"],
    diagnosticCommands: ["python -c \"import sys; print(sys.executable)\"", "go env", "dotnet --info", "Print the process working directory without printing secrets"],
  },
  {
    id: "jupyter",
    label: "Jupyter notebooks",
    status: "not-installed",
    learnerContext: "Exploratory waveform analysis, transcript evaluation, and hypothesis testing before productionization.",
    whatClientSees: "Cells can succeed because hidden state exists from an earlier run, while a clean kernel or production process fails.",
    likelyMistakes: ["Out-of-order execution", "Large audio arrays retained in memory", "Notebook environment differs from service environment", "Exploration copied into production without timeouts or cleanup"],
    confirmEnvironment: ["Restart kernel and run all", "Print interpreter path and package versions", "Record fixture provenance", "Measure memory and execution time"],
    dependencyLocation: "The kernel’s Python environment, not necessarily the terminal’s environment.",
    entryPoint: "Notebook metadata selects a kernel; cell order is not a reliable program entry point.",
    breakpointLocations: ["Convert critical logic into functions", "Inspect inputs/outputs at cell boundaries", "Use debugger support only after a clean run"],
    evidenceLocations: ["Cell output", "Kernel logs", "Variables/memory", "Saved experiment record"],
    diagnosticCommands: ["import sys; print(sys.executable)", "%pip list", "Restart kernel and run all cells"],
  },
  {
    id: "terminal-cli",
    label: "Terminal / CLI",
    status: "executable",
    learnerContext: "PowerShell and Bash diagnostics for health, auth, files, ffmpeg, environment, and process behavior.",
    whatClientSees: "A copied command may fail because shell syntax, aliases, quoting, current directory, PATH, or environment-variable scope differs.",
    likelyMistakes: ["Bash syntax pasted into PowerShell", "PowerShell curl alias assumptions", "Command runs from System32", "Environment variable was set in a different terminal", "Binary response sent through a text-transforming pipe"],
    confirmEnvironment: ["Identify the shell and executable resolution", "Print current directory", "Confirm environment variable existence without printing its value", "Check CLI versions and exit codes"],
    dependencyLocation: "PATH-resolved executables, shell modules/functions, and the current process environment.",
    entryPoint: "The script file or exact command line; quoting is part of the program.",
    breakpointLocations: ["Split the pipeline", "Inspect exit code/status after each command", "Save sanitized headers/body separately"],
    evidenceLocations: ["stdout", "stderr", "exit code", "output file metadata", "PowerShell ErrorRecord"],
    diagnosticCommands: ["Get-Location", "Get-Command curl.exe, ffmpeg", "$PSVersionTable.PSVersion", "Test-Path -LiteralPath <PATH>", "curl.exe --version"],
  },
  {
    id: "cmake-ninja",
    label: "CMake and Ninja",
    status: "executable",
    learnerContext: "Current C++20 learning path for native audio buffers and performance-sensitive infrastructure.",
    whatClientSees: "Configure, compile, and link are separate stages; a header resolving in the editor does not prove the linker can find the matching library or ABI.",
    likelyMistakes: ["Stale build directory", "Debug/Release mismatch", "Header found but library not linked", "Wrong architecture/compiler", "Audio callback code blocks or references destroyed state"],
    confirmEnvironment: ["Inspect CMake generator/compiler/cache", "Build verbose", "Confirm target architecture/configuration", "Separate compile errors from linker errors"],
    dependencyLocation: "Source tree, generated build tree, compiler include paths, linked libraries, and runtime DLL search path.",
    entryPoint: "CMakeLists.txt defines targets; main() starts the process; audio callbacks may start on library-owned threads.",
    breakpointLocations: ["main and initialization", "Audio callback entry/exit", "Queue push/pop", "Shutdown/RAII destructors"],
    evidenceLocations: ["CMake configure output", "Ninja verbose commands", "Linker diagnostics", "Debugger threads/call stacks", "Audio timing counters"],
    diagnosticCommands: ["cmake -S . -B build -G Ninja", "cmake --build build --verbose", "cmake -LA -N build", "ninja -C build -t targets"],
  },
  {
    id: "containers",
    label: "Containers",
    status: "conceptual",
    learnerContext: "Deployment boundary for backend services and diagnostics; host audio-device access is intentionally not assumed.",
    whatClientSees: "localhost, files, ports, certificates, environment variables, and audio devices resolve inside a different process/network/filesystem namespace.",
    likelyMistakes: ["Container localhost mistaken for host localhost", "Secret baked into image", "Port exposed but not published", "Mounted file missing or wrong permissions", "Assuming host microphone exists inside container"],
    confirmEnvironment: ["Inspect effective environment without printing secrets", "Verify container DNS/egress", "Check mounts and port mapping", "Confirm certificate store and runtime user"],
    dependencyLocation: "Image layers, package lock/module files, mounted files, and runtime-injected configuration.",
    entryPoint: "Dockerfile ENTRYPOINT/CMD and orchestrator override determine the process.",
    breakpointLocations: ["Application startup", "Configuration load", "Outbound request", "Graceful shutdown signal handler"],
    evidenceLocations: ["Container logs", "Health/readiness endpoint", "Network/DNS probe", "Mount listing", "Process exit code"],
    diagnosticCommands: ["docker inspect <CONTAINER>", "docker logs <CONTAINER>", "docker exec <CONTAINER> <SAFE_DIAGNOSTIC>", "docker port <CONTAINER>"],
  },
];
