import type { LanguageTrack, QuestlineLanguageId, RuntimeModel } from "@/types/questline";

const runtimes: Record<QuestlineLanguageId, RuntimeModel> = {
  python: {
    executionModel: "The Python interpreter executes bytecode in a process; a virtual environment controls which interpreter and packages the project sees.",
    processModel: "Usually one server/worker process with optional worker processes for scale.",
    memoryModel: "Objects are managed by Python; bytes and str are distinct and audio must remain bytes.",
    concurrencyModel: "asyncio schedules coroutines cooperatively. `await` yields control; blocking I/O can freeze the event loop.",
    networkModel: "HTTP clients exchange request/response bodies; WebSocket clients keep one bidirectional connection open.",
    dependencyModel: "A virtual environment plus lock/requirements file determines import resolution.",
    dataMovement: ["audio URL/file bytes → HTTP client", "response bytes → JSON parser", "transcript path → application model"],
    cleanupResponsibilities: ["close files and responses", "cancel tasks", "close WebSockets", "shut down client sessions"],
  },
  typescript: {
    executionModel: "JavaScript runs in a browser or Node.js. TypeScript is checked/transpiled and its types do not exist at runtime.",
    processModel: "Browser tab, Node process, or serverless request runtime; client and server files have different trust boundaries.",
    memoryModel: "Garbage-collected objects plus explicit binary containers such as ArrayBuffer, Blob, and Uint8Array.",
    concurrencyModel: "The event loop runs callbacks; promises schedule continuations instead of creating a thread per request.",
    networkModel: "fetch handles HTTP; native WebSocket dispatches events and browsers cannot set arbitrary WebSocket headers.",
    dependencyModel: "package.json and a lockfile select npm packages; bundlers decide what enters client output.",
    dataMovement: ["MediaRecorder Blob → ArrayBuffer", "binary chunk → WebSocket", "event.data → JSON.parse", "state update → render"],
    cleanupResponsibilities: ["stop MediaStream tracks", "close sockets", "remove listeners", "revoke object URLs", "avoid updates after unmount"],
  },
  go: {
    executionModel: "Go compiles to a native binary with a runtime that schedules goroutines.",
    processModel: "A small service binary often owns many concurrent sessions.",
    memoryModel: "Slices reference backing arrays; reused audio buffers must not be mutated while another goroutine reads them.",
    concurrencyModel: "Goroutines run concurrent work, channels coordinate ownership, and context propagates cancellation/deadlines.",
    networkModel: "net/http streams bodies; WebSocket support requires a verified library and explicit read/write loops.",
    dependencyModel: "go.mod and go.sum define module versions.",
    dataMovement: ["io.Reader → request body", "[]byte → socket writer", "JSON decoder → typed struct", "context cancellation → all loops"],
    cleanupResponsibilities: ["defer response.Body.Close", "cancel contexts", "stop goroutines", "close channels only from the owning sender"],
  },
  csharp: {
    executionModel: "C# compiles to intermediate language and executes under the .NET runtime.",
    processModel: "ASP.NET hosts requests in one managed process with dependency-injected services.",
    memoryModel: "Managed objects and byte arrays are garbage collected; streams still have explicit disposal lifetimes.",
    concurrencyModel: "Task-based async/await releases threads during I/O; CancellationToken carries cancellation through calls.",
    networkModel: "HttpClient performs HTTP; ClientWebSocket owns framed send/receive operations.",
    dependencyModel: "NuGet packages and project files define dependencies; configuration providers merge settings.",
    dataMovement: ["Stream/byte[] → HttpContent", "HTTP body → JSON model or audio stream", "CancellationToken → nested operations"],
    cleanupResponsibilities: ["reuse HttpClient", "dispose streams/responses", "propagate cancellation", "complete WebSocket close"],
  },
  powershell: {
    executionModel: "PowerShell parses commands, expands quoting rules, and launches .NET APIs or child processes.",
    processModel: "An interactive host or script process owns environment scope and current working directory.",
    memoryModel: "Pipelines pass .NET objects; native-process pipelines pass text/bytes according to host behavior.",
    concurrencyModel: "Commands are sequential unless jobs/runspaces/processes are used explicitly.",
    networkModel: "Invoke-RestMethod parses JSON; Invoke-WebRequest exposes status, headers, and raw content.",
    dependencyModel: "Modules, PATH, installed executables, and execution policy affect availability.",
    dataMovement: ["PowerShell object → ConvertTo-Json", "HTTP response → PSCustomObject", "file bytes → request body"],
    cleanupResponsibilities: ["remove temporary files", "stop jobs/processes", "limit environment-variable lifetime", "do not print credentials"],
  },
  shell: {
    executionModel: "A shell parses quoting, expands variables, connects processes, and observes exit codes.",
    processModel: "Each pipeline stage is commonly a separate process with its own stdin/stdout/stderr.",
    memoryModel: "Shell variables are text; binary correctness depends on the programs connected by the pipe.",
    concurrencyModel: "Foreground pipelines block; background jobs and signals require explicit lifecycle handling.",
    networkModel: "curl.exe/curl sends HTTP; WebSockets normally require a separate verified CLI.",
    dependencyModel: "PATH and installed executables select tool versions.",
    dataMovement: ["file/stdin → curl request body", "response stdout → jq/file", "exit code → script decision"],
    cleanupResponsibilities: ["quote paths", "handle signals", "check exit codes", "avoid shell history secrets"],
  },
  sql: {
    executionModel: "SQL declares the result or mutation; the database optimizer chooses a physical query plan.",
    processModel: "A database server coordinates sessions, transactions, storage, indexes, and locks.",
    memoryModel: "Rows and pages live in storage/cache; JSON values are data rather than application control flow.",
    concurrencyModel: "Transactions and isolation rules coordinate concurrent readers/writers.",
    networkModel: "Applications use a database protocol and pooled connections, not Deepgram directly.",
    dependencyModel: "Schema migrations, extensions, and engine version define available behavior.",
    dataMovement: ["transcript JSON → normalized rows/JSON column", "index → filtered rows", "query result → application"],
    cleanupResponsibilities: ["commit/rollback transactions", "release connections", "enforce retention", "cascade or explicitly delete child records"],
  },
  cpp: {
    executionModel: "C++20 compiles to native code; CMake generates build files and Ninja runs compiler/linker commands.",
    processModel: "A native process owns audio callbacks, worker threads, queues, and network clients.",
    memoryModel: "Ownership is explicit. Stack, heap, references, pointers, spans, and vector capacity affect safety and latency.",
    concurrencyModel: "OS threads and lock-free/locked queues require strict ownership; audio callbacks must not block.",
    networkModel: "HTTP/WebSocket behavior comes from selected native libraries; no official Deepgram C++ SDK is assumed.",
    dependencyModel: "Headers, libraries, ABI, compiler configuration, and linker paths must agree.",
    dataMovement: ["device callback → int16 buffer", "buffer → bounded queue", "worker → encoded/network bytes", "event JSON → application state"],
    cleanupResponsibilities: ["RAII owns sockets/devices", "join threads", "stop callbacks before destroying state", "avoid dangling spans/pointers"],
  },
  "html-css": {
    executionModel: "The browser parses HTML into a semantic DOM and CSS into layout/paint rules.",
    processModel: "The document hosts controls; JavaScript supplies capture and network behavior.",
    memoryModel: "DOM nodes and styles are browser-managed; accessible semantics remain part of the interface contract.",
    concurrencyModel: "Rendering shares the main thread with JavaScript and must stay responsive.",
    networkModel: "Forms and script-driven requests cross explicit user and trust boundaries.",
    dependencyModel: "Browser standards and the project build system determine supported features.",
    dataMovement: ["user action → semantic control", "transcript state → DOM", "focus/status → assistive technology"],
    cleanupResponsibilities: ["remove obsolete status", "preserve focus", "avoid hidden active audio controls"],
  },
  php: {
    executionModel: "A web server invokes PHP for a request; PHP-FPM workers commonly run synchronous request lifecycles.",
    processModel: "Each request uses worker time until cURL/file/database work completes.",
    memoryModel: "Request-scoped values are released after response; uploaded files begin in a temporary path.",
    concurrencyModel: "Typical code is synchronous, so timeouts and long streaming loops can exhaust workers.",
    networkModel: "cURL performs REST requests; browser traffic should call the PHP server proxy, not Deepgram with a permanent key.",
    dependencyModel: "Composer packages, php.ini, web-server environment, and extensions define capability.",
    dataMovement: ["temporary upload → raw request bytes", "cURL response → json_decode", "transcript → application response"],
    cleanupResponsibilities: ["close cURL/file handles", "validate upload lifetime", "set bounded timeouts", "keep env configuration server-side"],
  },
  react: {
    executionModel: "React calculates UI from props/state; event handlers and effects synchronize with external browser systems.",
    processModel: "A component lives inside a browser render tree and may mount, update, suspend, and unmount.",
    memoryModel: "State triggers rendering; refs hold mutable resources without triggering a render.",
    concurrencyModel: "Effects run after commit. Never update another component during render; callbacks can otherwise capture stale state.",
    networkModel: "Client fetch calls trusted local routes; WebSocket and MediaStream resources belong in effects/handlers with cleanup.",
    dependencyModel: "React/Next versions and client/server boundaries define allowed APIs.",
    dataMovement: ["event → state update", "state → render", "ref → socket/recorder", "cleanup → close/stop resources"],
    cleanupResponsibilities: ["stop tracks", "close sockets", "clear timers", "cancel animation frames", "avoid render-phase state updates"],
  },
  "java-kotlin": {
    executionModel: "JVM bytecode runs under the managed Java runtime; Kotlin interoperability uses Java APIs.",
    processModel: "A service process owns thread pools and framework request lifecycles.",
    memoryModel: "Managed objects plus explicit byte buffers/streams.",
    concurrencyModel: "Threads, futures, reactive APIs, or Kotlin coroutines depend on the selected stack.",
    networkModel: "Official Java SDK patterns may apply; Kotlin-specific parity must be validated.",
    dependencyModel: "Maven/Gradle coordinates modules and versions.",
    dataMovement: ["stream → HTTP/WebSocket client", "JSON → typed model", "result → service response"],
    cleanupResponsibilities: ["close streams", "cancel async work", "shut down clients"],
  },
  rust: {
    executionModel: "Rust compiles to native code and uses ownership/borrowing for memory safety.",
    processModel: "A native service commonly runs an async executor.",
    memoryModel: "Ownership, lifetimes, slices, and Send/Sync rules make data-sharing explicit.",
    concurrencyModel: "Async tasks and channels depend on the selected runtime; feature parity must be verified.",
    networkModel: "An official crate exists, but Deepgram product support is not uniform across SDKs.",
    dependencyModel: "Cargo.toml and Cargo.lock select features and crate versions.",
    dataMovement: ["byte slice → client", "event bytes → JSON model", "owned result → application"],
    cleanupResponsibilities: ["drop/close resources", "cancel tasks", "bound channels"],
  },
};

const seeds: Array<Omit<LanguageTrack, "runtime">> = [
  { id: "python", label: "Python", shortLabel: "PY", category: "primary", learnerFit: "Backend, ML tooling, batch evaluation, and async service practice.", voiceStrengths: ["Fast experiments", "evaluation tooling", "FastAPI services"], focus: ["asyncio", "bytes", "HTTP/WebSocket", "audio processing", "pytest concepts"], supportedCore: true, docsStatus: "executable" },
  { id: "typescript", label: "JavaScript / TypeScript", shortLabel: "TS", category: "primary", learnerFit: "Existing web strengths become explicit client/server and event-loop mastery.", voiceStrengths: ["Browser audio", "Next.js routes", "event-driven UI"], focus: ["MediaRecorder", "ArrayBuffer", "WebSocket", "React state", "Node services"], supportedCore: true, docsStatus: "executable" },
  { id: "go", label: "Go", shortLabel: "GO", category: "primary", learnerFit: "Production streaming, cancellation, and high-concurrency service design.", voiceStrengths: ["Low-overhead services", "goroutines", "graceful shutdown"], focus: ["net/http", "[]byte", "channels", "context", "backpressure"], supportedCore: true, docsStatus: "docs-verification-required" },
  { id: "csharp", label: ".NET / C#", shortLabel: "C#", category: "primary", learnerFit: "Enterprise API, configuration, and contact-center integration patterns.", voiceStrengths: ["ASP.NET", "typed payloads", "dependency injection"], focus: ["HttpClient", "Stream", "async/await", "CancellationToken", "xUnit concepts"], supportedCore: true, docsStatus: "executable" },
  { id: "powershell", label: "PowerShell", shortLabel: "PS", category: "primary", learnerFit: "Windows-native diagnosis and rapid API evidence gathering.", voiceStrengths: ["Environment diagnosis", "HTTP smoke tests", "process orchestration"], focus: ["Invoke-RestMethod", "curl.exe", "ffmpeg", "PATH", "quoting"], supportedCore: true, docsStatus: "executable" },
  { id: "shell", label: "Shell / Bash", shortLabel: "SH", category: "primary", learnerFit: "Cross-platform CLI literacy and deployment debugging.", voiceStrengths: ["curl pipelines", "container entrypoints", "automation"], focus: ["stdin/stdout", "exit codes", "signals", "jq concepts", "ffmpeg"], supportedCore: true, docsStatus: "executable" },
  { id: "sql", label: "SQL", shortLabel: "SQL", category: "primary", learnerFit: "Transcript, trace, evaluation, and retention data modeling.", voiceStrengths: ["Searchable transcripts", "observability", "evaluation aggregation"], focus: ["sessions", "words", "turns", "JSON", "indexes", "retention"], supportedCore: true, docsStatus: "conceptual" },
  { id: "cpp", label: "C++20", shortLabel: "C++", category: "primary", learnerFit: "Current CMake/Ninja learning connects directly to low-latency audio ownership.", voiceStrengths: ["Native buffers", "audio callbacks", "performance-sensitive gateways"], focus: ["RAII", "std::vector<int16_t>", "threads", "ring buffers", "CMake/Ninja"], supportedCore: true, docsStatus: "docs-verification-required" },
  { id: "html-css", label: "HTML / CSS", shortLabel: "WEB", category: "bridge", learnerFit: "Certified foundations become accessible, calm voice controls and diagnostics.", voiceStrengths: ["Semantic mic controls", "transcript layouts", "accessible status"], focus: ["forms", "focus", "waveforms", "responsive consoles"], supportedCore: true, docsStatus: "conceptual" },
  { id: "php", label: "PHP", shortLabel: "PHP", category: "bridge", learnerFit: "Translate provider integration into legacy and shared-hosting customer reality.", voiceStrengths: ["Server proxy", "file uploads", "existing customer stacks"], focus: ["cURL", "PHP-FPM", "temp uploads", "timeouts", "environment"], supportedCore: true, docsStatus: "docs-verification-required" },
  { id: "react", label: "React specialization", shortLabel: "RX", category: "framework-specialization", learnerFit: "Build safe browser audio lifecycles without stale closures or render-phase updates.", voiceStrengths: ["Interactive voice UI", "resource lifecycle", "state visualization"], focus: ["state", "refs", "effects", "cleanup", "render purity"], supportedCore: true, docsStatus: "executable" },
  { id: "java-kotlin", label: "Java / Kotlin awareness", shortLabel: "JVM", category: "optional-awareness", learnerFit: "Recognize JVM customer stacks without blocking the core path.", voiceStrengths: ["Enterprise services", "official Java SDK awareness"], focus: ["Gradle/Maven", "threads/coroutines", "JVM interop"], supportedCore: false, docsStatus: "docs-verification-required" },
  { id: "rust", label: "Rust awareness", shortLabel: "RS", category: "optional-awareness", learnerFit: "Understand ownership-led native services without implying feature parity.", voiceStrengths: ["Memory-safe native services", "bounded concurrency"], focus: ["ownership", "async runtimes", "crate feature parity"], supportedCore: false, docsStatus: "docs-verification-required" },
];

export const LANGUAGE_TRACKS: LanguageTrack[] = seeds.map((track) => ({ ...track, runtime: runtimes[track.id] }));

export function getLanguageTrack(id: QuestlineLanguageId) {
  return LANGUAGE_TRACKS.find((track) => track.id === id) ?? LANGUAGE_TRACKS[1];
}
