import type { DebuggerScenario, DrillScenario, MasteryLevel, TestingQuest } from "@/types/questline";

const DISCLAIMER = "Local educational progress only; not an official Deepgram certification.";

export const MASTERY_LEVELS: MasteryLevel[] = [
  { level: 1, id: "api-reader", name: "API Reader", requirements: [req("trace-input", "Trace input, output, and response path", "code reading"), req("explain-auth", "Explain the server-only credential boundary", "security"), req("read-status", "Interpret HTTP status before parsing", "HTTP")], disclaimer: DISCLAIMER },
  { level: 2, id: "language-operator", name: "Language Operator", requirements: [req("run-rest", "Construct one raw REST request", "language runtime"), req("parse-transcript", "Extract transcript and request ID", "JSON"), req("handle-error", "Handle a non-2xx response", "error handling")], disclaimer: DISCLAIMER },
  { level: 3, id: "integration-builder", name: "Integration Builder", requirements: [req("project-structure", "Explain client/server file placement", "architecture"), req("binary-body", "Handle binary audio without text conversion", "audio data"), req("integration-test", "Define a mocked integration test", "testing")], disclaimer: DISCLAIMER },
  { level: 4, id: "streaming-debugger", name: "Streaming Debugger", requirements: [req("socket-lifecycle", "Explain open/send/receive/close lifecycle", "streaming"), req("cancellation", "Propagate cancellation and cleanup", "concurrency"), req("trace-evidence", "Diagnose from frames, timing, and close evidence", "debugging")], disclaimer: DISCLAIMER },
  { level: 5, id: "audio-systems-engineer", name: "Audio Systems Engineer", requirements: [req("audio-bytes", "Explain sample format, rate, channels, codec, and container", "audio"), req("detect-clipping", "Identify clipping/silence/mismatch evidence", "signal analysis"), req("latency-buffer", "Explain chunk and buffering tradeoffs", "latency")], disclaimer: DISCLAIMER },
  { level: 6, id: "applied-ml-engineer", name: "Applied ML Engineer", requirements: [req("representative-set", "Define a representative evaluation set", "evaluation"), req("segment-analysis", "Analyze failures by segment", "applied ML"), req("rollout", "Define production signal and rollback condition", "reliability")], disclaimer: DISCLAIMER },
  { level: 7, id: "client-solutions-architect", name: "Client Solutions Architect", requirements: [req("discovery", "Perform stack and business discovery", "client reasoning"), req("ownership", "Explain ownership and security boundaries", "architecture"), req("solution-brief", "Export an evidence-backed POC recommendation", "customer impact")], disclaimer: DISCLAIMER },
];

function req(id: string, label: string, skill: string) {
  return { id, label, skill };
}

export const TESTING_QUESTS: TestingQuest[] = [
  { id: "unit-payload", title: "Payload construction", kind: "unit", languages: ["python", "typescript", "go", "csharp", "php"], tool: "Language-native unit-test concept", installed: false, fixture: "Known URL/model/language/options", assertion: "URL, headers, body, and placeholders match the intended request contract", failureMeaning: "Coding/integration bug before the network boundary" },
  { id: "unit-response-path", title: "Transcript extraction", kind: "unit", languages: ["python", "typescript", "go", "csharp", "php"], tool: "Language-native unit-test concept", installed: false, fixture: "Deterministic prerecorded response JSON", assertion: "Extract transcript, words, and request ID only when present", failureMeaning: "Response parsing/schema assumption" },
  { id: "unit-redaction", title: "Credential redaction", kind: "unit", languages: ["typescript", "python", "go", "csharp", "php", "powershell", "shell"], tool: "Local sanitizer fixture", installed: false, fixture: "Authorization, token, credential-like fields, and placeholder examples", assertion: "Realistic secrets are redacted while DEEPGRAM_API_KEY placeholders remain instructional", failureMeaning: "Security defect; block persistence/export" },
  { id: "unit-retry", title: "Retry decision", kind: "unit", languages: ["python", "typescript", "go", "csharp"], tool: "Table-driven decision fixture", installed: false, fixture: "400, 401, 429, 500, timeout, and duplicate-business-action cases", assertion: "Only bounded safe failures are retried; destructive/tool actions require idempotency/confirmation", failureMeaning: "Reliability or business-safety bug" },
  { id: "integration-local-route", title: "Guarded local route", kind: "integration", languages: ["typescript"], tool: "Mocked upstream fetch concept", installed: false, fixture: "Browser request to /api/deepgram route plus mocked upstream response", assertion: "Credential stays server-side and returned inspector is sanitized", failureMeaning: "Trust-boundary integration bug" },
  { id: "integration-file", title: "File upload boundary", kind: "integration", languages: ["typescript", "python", "csharp", "php"], tool: "Multipart/binary fixture concept", installed: false, fixture: "Small WAV, empty file, oversized file, unsupported MIME", assertion: "Binary bytes and validated metadata reach the trusted adapter", failureMeaning: "Upload/body/MIME integration bug" },
  { id: "integration-tts", title: "TTS binary response", kind: "integration", languages: ["typescript", "python", "go", "csharp", "php"], tool: "Mocked audio response", installed: false, fixture: "Known audio bytes and content-type", assertion: "Response is treated as bytes and filename/playback agrees with encoding", failureMeaning: "Binary/content-type integration bug" },
  { id: "streaming-order", title: "Interim/final ordering", kind: "streaming", languages: ["typescript", "python", "go", "csharp"], tool: "Deterministic event fixture", installed: false, fixture: "Interim, duplicate interim, final, close", assertion: "Only final data becomes durable and ordering evidence is preserved", failureMeaning: "State-machine/event handling bug" },
  { id: "streaming-cancel", title: "Cancellation and cleanup", kind: "streaming", languages: ["typescript", "python", "go", "csharp", "cpp", "react"], tool: "Lifecycle simulation", installed: false, fixture: "Cancel during capture/send/receive", assertion: "All resources stop once without leaks or post-cancel updates", failureMeaning: "Concurrency/lifecycle bug" },
  { id: "audio-silence-clipping", title: "Silence and clipping", kind: "audio", languages: ["python", "typescript", "go", "csharp", "cpp"], tool: "Generated local fixtures", installed: false, fixture: "Silence, low gain, and clipped sine/noise", assertion: "Signal diagnostics identify the condition before blaming recognition", failureMeaning: "Audio capture/data problem" },
  { id: "audio-format", title: "Format mismatch", kind: "audio", languages: ["python", "typescript", "go", "csharp", "cpp", "php", "powershell", "shell"], tool: "Header/byte fixture", installed: false, fixture: "WAV bytes labeled raw PCM; wrong sample rate/channel metadata", assertion: "Mismatch is detected and corrected at the producer boundary", failureMeaning: "Audio contract bug" },
  { id: "sql-retention", title: "Transcript retention", kind: "integration", languages: ["sql"], tool: "Migration/query fixture", installed: false, fixture: "Sessions with words, turns, tools, traces, evaluations", assertion: "Retention removes the intended graph without cross-tenant or orphan errors", failureMeaning: "Data-governance/schema bug" },
];

export const DEBUGGER_SCENARIOS: DebuggerScenario[] = [
  debuggerScenario("typescript-live-stops", "Live microphone stops transcribing", "typescript", [
    watch("socket.readyState", "1", "The WebSocket was open at the breakpoint."),
    watch("chunkStats.totalBytesSent", "0", "Capture or recorder delivery failed before provider recognition."),
    watch("selectedMimeType", "audio/webm;codecs=opus", "Compare actual containerized bytes with request query; do not add raw PCM metadata."),
  ], "The socket is open but no chunks were produced; inspect permission, selected device, recorder state, and dataavailable before changing Deepgram options."),
  debuggerScenario("python-await", "Python coroutine never runs", "python", [watch("type(result)", "coroutine", "The async function was called but not awaited."), watch("event_loop_lag_ms", "0", "This is scheduling misuse, not a blocked loop.")], "The caller forgot await/create_task; fix ownership of coroutine execution and cancellation."),
  debuggerScenario("go-cancel", "Go session remains after disconnect", "go", [watch("ctx.Err()", "context canceled", "The cancellation signal exists."), watch("goroutines", "sendLoop waiting on audioCh", "The loop does not select on ctx.Done or the channel owner never closes.")], "A session goroutine ignores cancellation while blocked on a channel."),
  debuggerScenario("csharp-disposed-stream", "C# upload fails during send", "csharp", [watch("audio.CanRead", "false", "The stream was disposed before HttpClient consumed it."), watch("cancellationToken.IsCancellationRequested", "false", "This is not caller cancellation.")], "A using scope ends before the asynchronous send completes; keep the stream alive through response completion."),
  debuggerScenario("powershell-path", "PowerShell cannot find audio", "powershell", [watch("Get-Location", "C:\\Windows\\System32", "The relative path resolves in the wrong directory."), watch("Test-Path $AudioPath", "False", "Fail before issuing a network request.")], "The command runs from an unexpected working directory; resolve/validate the literal path."),
  debuggerScenario("cpp-shutdown", "C++ crashes during audio shutdown", "cpp", [watch("callback_active", "true", "The audio callback is still running."), watch("state_ptr", "destroyed", "The callback references state whose lifetime has ended.")], "Shutdown order violates ownership: stop callback/device before destroying shared state and joining workers."),
  debuggerScenario("php-upload", "PHP handler sees no file", "php", [watch("$_SERVER['CONTENT_LENGTH']", "31457280", "The request is large."), watch("ini_get('post_max_size')", "8M", "The web/PHP boundary rejects the body before normal upload handling.")], "The effective request/upload limit rejects the body before application logic."),
  debuggerScenario("sql-slow-query", "Transcript timeline query is slow", "sql", [watch("query_plan", "Seq Scan on transcript_words", "The engine cannot use an index for the filter/order."), watch("rows", "18000000", "Representative volume exposes the access-path problem.")], "The schema lacks an index matching tenant/session/time filtering and ordering."),
];

function debuggerScenario(id: string, title: string, language: DebuggerScenario["language"], watches: DebuggerScenario["watches"], diagnosis: string): DebuggerScenario {
  return {
    id,
    title,
    language,
    frames: [
      { function: "user_action", file: "client-or-entrypoint", line: 1, locals: { sessionId: "local-session-demo" } },
      { function: "integration_boundary", file: "adapter", line: 20, locals: { authorization: "***redacted***" } },
      { function: "failing_operation", file: "runtime-specific", line: 42, locals: { rawAudioIncluded: false } },
    ],
    watches,
    evidenceOrder: ["Start with the visible symptom", "Confirm runtime/process/configuration", "Inspect data type and resource state", "Inspect network/status/event evidence", "Verify cleanup and fallback"],
    correctDiagnosis: diagnosis,
  };
}

function watch(expression: string, value: string, implication: string) {
  return { expression, value, implication };
}

export const DRILL_SCENARIOS: DrillScenario[] = [
  drill("go-prod-60s", "Go production socket disconnects after 60 seconds", "go", ["browser/media ingress", "Go gateway", "reverse proxy", "Deepgram realtime"], ["Ask whether timing is deterministic", "Compare local and production network paths", "Inspect proxy upgrade/timeout logs", "Explain context/goroutine cleanup", "Propose a long-session synthetic test"], ["Connection duration histogram", "Proxy logs", "WebSocket close evidence", "Goroutine/session trace"], "Publish a streaming infrastructure preflight and long-session probe."),
  drill("python-loop-lag", "Python transcript latency spikes during analysis", "python", ["audio receive", "asyncio loop", "analysis work", "event delivery"], ["Separate recognition latency from local loop lag", "Inspect blocking CPU/file calls", "Test bounded worker offload", "Measure before/after"], ["Loop-lag metric", "Task stacks", "Latency waterfall"], "Add an async-path blocking-work checklist and loop-lag telemetry."),
  drill("typescript-secret", "Customer pasted a key into React", "typescript", ["browser bundle", "Next.js route", "Deepgram auth"], ["Contain and rotate the key", "Trace client import graph", "Move call to server route", "Use temporary grant only where verified"], ["Bundle search", "Network headers", "Environment variable names"], "Add bundle secret scanning and a safe starter route."),
  drill("csharp-cancel", "ASP.NET work continues after callers leave", "csharp", ["controller", "injected client", "stream", "provider/tool"], ["Inspect token at every boundary", "Distinguish cancellation from failure", "Verify disposal", "Test disconnected request"], ["CancellationToken watches", "Active request count", "Outbound trace"], "Adopt a cancellation-propagation contract and test fixture."),
  drill("cpp-crackle", "Native stream produces crackle and poor transcripts", "cpp", ["device callback", "sample conversion", "queue", "network worker"], ["Inspect clipping/underruns before model choice", "Verify signedness/endianness/rate", "Measure callback/queue timing", "Use a generated known signal"], ["Peak/RMS", "Queue underrun count", "Sample dump metadata", "Thread timing"], "Add a deterministic signal and buffer-integrity diagnostic mode."),
  drill("php-large-upload", "PHP call recordings fail above eight megabytes", "php", ["browser", "reverse proxy", "PHP upload boundary", "provider adapter"], ["Find every body-size limit", "Confirm application handler is reached", "Define POC limit or worker/object-storage path", "Explain synchronous worker risk"], ["Content-Length", "Proxy/PHP logs", "php.ini effective values"], "Publish an upload-limit matrix and large-recording architecture decision."),
  drill("sql-duplicates", "Final words appear twice in analytics", "sql", ["stream event handler", "ingestion", "word schema", "report query"], ["Check interim/final semantics", "Find idempotency key", "Inspect uniqueness constraints", "Repair and prevent separately"], ["Raw sanitized event trace", "Duplicate-key query", "Schema constraints"], "Standardize final-event idempotency and a duplicate audit query."),
  drill("powershell-auth", "PowerShell auth works only in one window", "powershell", ["terminal process", "environment scope", "local app process", "server route"], ["Identify when each process started", "Check key existence without outputting it", "Restart with correct configuration", "Avoid shell history secrets"], ["Process start times", "Environment existence", "Health route inspector"], "Add a safe environment-scope diagnostic to the runbook."),
  drill("browser-mime", "Browser sends audio but receives no useful transcript", "typescript", ["device", "MediaRecorder", "WebSocket query", "Deepgram listen"], ["Capture actual MIME", "Inspect bytes/chunk count", "Remove raw PCM metadata for containerized audio", "Run upload fallback"], ["MediaRecorder MIME", "Chunk bytes", "Sanitized query", "Fallback result"], "Create a browser MIME compatibility probe and evidence bundle."),
  drill("container-localhost", "Container cannot reach the host media gateway", "shell", ["container namespace", "host", "service DNS", "firewall"], ["Explain localhost per process namespace", "Probe from inside container", "Use deployment-appropriate service address", "Document port mapping"], ["docker inspect", "DNS/connection probe", "Service logs"], "Add a container networking diagram and preflight."),
  drill("telephony-codec", "Phone audio quality is poor despite clean browser tests", "csharp", ["PSTN/provider", "media bridge", "encoding/channel mapping", "speech recognition"], ["Inventory telephony codec/rate/channels", "Compare browser and phone distributions", "Inspect bridge transformations", "Evaluate with representative calls"], ["Media negotiation", "Sample metadata", "Segmented transcript errors"], "Add telephony-native fixtures and codec/channel checks."),
  drill("hardware-clipping", "Studio microphone clips only for loud speakers", "cpp", ["microphone/interface gain", "ADC", "capture buffer", "recognition"], ["Measure peak and clipped-sample ratio", "Inspect gain/AGC", "Record representative loud speech safely", "Separate audio correction from model evaluation"], ["Waveform", "Peak/RMS", "Clipped sample count", "Interface settings"], "Add a capture calibration and clipping warning flow."),
];

function drill(id: string, title: string, language: DrillScenario["language"], layers: string[], reasoning: string[], evidence: string[], reusableImprovement: string): DrillScenario {
  return { id, title, prompt: `You are joining a customer call: ${title}. Ask discovery questions, choose evidence, propose a bounded test/fix, explain it to the client, and identify a reusable improvement.`, language, layers, expectedReasoning: reasoning, evidenceChoices: evidence, reusableImprovement };
}
