"use client";

import { useRef, useState } from "react";
import { CASE_ITEM_KINDS, addCaseRelation, archiveCaseItem, auditCaseExport, buildCaseMarkdown, captureCaseItem, captureQuestionAnswer, deriveCoverage, evaluateClaimSafety, exportSolutionCase, importSolutionCase, searchCase, updateQuestionStatus, type CaptureInput, type ExportProfile } from "@/lib/live-solution-case";
import type { CaseItem, SolutionCaseBundle } from "@/types/live-solution-case";

const button="rounded-md border border-white/10 bg-white/[.04] px-2.5 py-2 text-[11px] font-semibold text-slate-200 hover:border-cyan-200/30 focus-visible:outline-2 focus-visible:outline-cyan-200 disabled:opacity-40";
const primary=`${button} border-cyan-200/30 bg-cyan-200/[.12] text-cyan-50`;
const labels:Partial<Record<CaseItem["kind"],string>>={"customer-statement":"Customer Said","observed-technical-evidence":"Evidence","open-question":"Question","validation-result":"Validation"};

export function CaseIntelligenceWorkspace({bundle,onChange,onNotice}:{bundle:SolutionCaseBundle;onChange:(next:SolutionCaseBundle)=>void;onNotice:(message:string)=>void}){
  const [kind,setKind]=useState<CaseItem["kind"]>("customer-statement");const [body,setBody]=useState("");const [visibility,setVisibility]=useState<CaseItem["visibility"]>("internal");const [confidence,setConfidence]=useState<CaseItem["confidence"]>("Unknown");const [tab,setTab]=useState("ledger");const [query,setQuery]=useState("");const [answer,setAnswer]=useState("");const [profile,setProfile]=useState<ExportProfile>("internal-technical-brief");const fileRef=useRef<HTMLInputElement>(null);
  const active=bundle.items.filter(i=>!i.isArchived&&!i.supersededAt);const top=bundle.questionCandidates[0];const results=query?searchCase(bundle,query):active;const coverage=deriveCoverage(bundle);const audit=auditCaseExport(bundle,profile);const contradictions=active.filter(i=>i.kind==="unresolved-conflict"&&!i.resolvedAt);const risks=active.filter(i=>i.kind==="risk"&&i.structuredData.mitigationStatus!=="completed");const actions=active.filter(i=>i.kind==="action"&&i.structuredData.status!=="completed");
  const safety=active.map(item=>({item,...evaluateClaimSafety(item)}));
  function capture(){try{onChange(captureCaseItem(bundle,{kind,body,visibility,confidence,statementMode:kind==="customer-statement"?"user-paraphrase":undefined}));setBody("");onNotice(`${labels[kind]??kind.replaceAll("-"," ")} captured in the Evidence & Decision Ledger.`);}catch(error){onNotice(error instanceof Error?error.message:"Capture failed.");}}
  function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
  async function importFile(file:File){const raw=await file.text();const result=importSolutionCase(raw);if(result.ok){onChange(result.bundle);onNotice("Validated case imported. No content was executed.");}else onNotice(result.error);}
  return <section className="rounded-xl border border-cyan-200/15 bg-[#071016] p-3" aria-label="Live Solution Case intelligence">
    <div className="flex flex-wrap items-start justify-between gap-2 border-b border-white/10 pb-3"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-cyan-300">Live Solution Case Graph</p><h2 className="mt-1 text-sm font-semibold text-white">{bundle.case.displayName}</h2><p className="mt-1 text-[10px] text-slate-500">{bundle.case.sessionStage} · {bundle.case.status} · {bundle.case.activeModule} · revision {bundle.case.revision} · local save</p></div><div className="flex flex-wrap gap-1 text-[9px]"><span className="rounded-full border border-amber-200/20 px-2 py-1">{contradictions.length} contradictions</span><span className="rounded-full border border-rose-200/20 px-2 py-1">{risks.filter(i=>i.structuredData.blocking).length} blocking risks</span><span className="rounded-full border border-white/10 px-2 py-1">{actions.length} actions</span><span className="rounded-full border border-white/10 px-2 py-1">sources {bundle.case.sourceFreshness.state}</span></div></div>
    <p className="mt-3 rounded-md border border-white/8 bg-black/15 p-2 text-[10px] leading-4 text-slate-400">Customer statements, observed evidence, official sources, assumptions, and recommendations remain separate so the studio does not present an inference as an agreed fact.</p>
    {top?<article className="mt-3 rounded-lg border border-cyan-200/20 bg-cyan-200/[.04] p-3" aria-live="polite"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-cyan-200">Next-Best-Question Copilot · {top.priorityBand}</p><p className="mt-2 text-sm font-semibold leading-5 text-white">{top.questionText}</p><p className="mt-2 text-[10px] text-slate-400"><strong>Why ask now:</strong> {top.whyNow.join(" ")}</p><p className="mt-1 text-[10px] text-slate-400"><strong>What it unlocks:</strong> {top.unlocks.join(", ")}</p><p className="mt-2 text-[9px] text-amber-100/70">Next-Best-Question suggestions are decision aids. Review the wording and relevance before asking.</p><div className="mt-2 flex flex-wrap gap-1"><button className={primary} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"asked"))}>Ask Now</button><button className={button} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"ask-later"))}>Ask Later</button><button className={button} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"answered"))}>Already Answered</button><button className={button} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"skipped"))}>Skip</button><button className={button} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"not-relevant"))}>Not Relevant</button><button className={button} onClick={()=>onChange(updateQuestionStatus(bundle,top.id,"parking-lot"))}>Parking Lot</button></div><div className="mt-2 flex gap-1"><input aria-label="Capture answer" value={answer} onChange={e=>setAnswer(e.target.value)} className="min-w-0 flex-1 rounded-md border border-white/10 bg-black/20 px-2 text-xs" placeholder="Capture an answer without converting it to a requirement"/><button className={button} disabled={!answer.trim()} onClick={()=>{onChange(captureQuestionAnswer(bundle,top.id,answer));setAnswer("");}}>Capture Answer</button></div></article>:null}
    <div className="mt-3 rounded-lg border border-white/10 p-3"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-400">Quick capture</p><div className="mt-2 flex flex-wrap gap-1">{(["customer-statement","requirement","constraint","observed-technical-evidence","assumption","hypothesis","risk","open-question","decision","action","validation-result"] as CaseItem["kind"][]).map(value=><button key={value} aria-pressed={kind===value} className={kind===value?primary:button} onClick={()=>setKind(value)}>{labels[value]??value.replaceAll("-"," ")}</button>)}</div><textarea aria-label="Quick capture text" value={body} onChange={e=>setBody(e.target.value)} maxLength={12000} className="mt-2 min-h-20 w-full rounded-md border border-white/10 bg-black/20 p-2 text-xs" placeholder="Capture a redacted statement, requirement, evidence, risk, decision, or action…"/><div className="mt-2 flex flex-wrap gap-2"><label className="text-[10px] text-slate-500">Confidence <select value={confidence} onChange={e=>setConfidence(e.target.value as CaseItem["confidence"])} className="ml-1 rounded bg-[#071016] p-1">{["High","Medium","Low","Unknown"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[10px] text-slate-500">Visibility <select value={visibility} onChange={e=>setVisibility(e.target.value as CaseItem["visibility"])} className="ml-1 rounded bg-[#071016] p-1">{["internal","customer","private"].map(x=><option key={x}>{x}</option>)}</select></label><button className={primary} disabled={!body.trim()} onClick={capture}>Save capture</button></div></div>
    <nav className="mt-3 flex gap-1 overflow-x-auto" aria-label="Case intelligence panels">{[["ledger","Evidence & Decision Ledger"],["graph","Case Graph"],["coverage","Coverage"],["claims","Claim Safety"],["registers","Decisions · Risks · Actions"],["export","Export"]].map(([id,label])=><button key={id} className={tab===id?primary:button} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="ledger"?<div className="mt-3"><label className="block text-[10px] text-slate-500">Local case search<input value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 w-full rounded-md border border-white/10 bg-black/20 p-2 text-xs" placeholder="Search SDK, runtime, model, endpoint, decision…"/></label><ul className="mt-2 space-y-2" aria-label="Evidence ledger">{results.slice(0,50).map(item=><li key={item.id} className="rounded-md border border-white/8 p-2"><div className="flex items-start justify-between gap-2"><div><p className="text-[9px] uppercase text-cyan-200">{item.kind} · {item.verificationState} · {item.confidence}</p><p className="mt-1 text-xs font-semibold text-white">{item.title}</p><p className="mt-1 text-[10px] text-slate-400">{item.body}</p><p className="mt-1 text-[9px] text-slate-600">{item.moduleOrigin} · {item.visibility} · {item.claimSafety} · {item.updatedAt}</p></div><div className="flex flex-col gap-1"><button className={button} onClick={()=>{const target=active.find(x=>x.id!==item.id);if(target)onChange(addCaseRelation(bundle,{fromItemId:item.id,toItemId:target.id,type:"supports"}));}}>Add support</button><button className={button} onClick={()=>onChange(archiveCaseItem(bundle,item.id))}>Archive</button></div></div></li>)}</ul></div>:null}
    {tab==="graph"?<div className="mt-3 grid gap-2 md:grid-cols-2"><div><h3 className="text-xs font-semibold text-white">Inspectable relationships</h3><ul className="mt-2 space-y-2" aria-label="Semantic case relationships">{bundle.relations.slice(0,100).map(r=>{const from=bundle.items.find(i=>i.id===r.fromItemId),to=bundle.items.find(i=>i.id===r.toItemId);return <li key={r.id} className="rounded-md border border-white/8 p-2 text-[10px] text-slate-400"><strong className="text-slate-200">{from?.title??r.fromItemId}</strong> <span className="text-cyan-200">{r.type}</span> <strong className="text-slate-200">{to?.title??r.toItemId}</strong><span className="block text-slate-600">{r.note||"No note"} · {r.confidence}</span></li>})}</ul></div><div><h3 className="text-xs font-semibold text-white">Unanswered questions and contradictions</h3>{contradictions.map(i=><div key={i.id} className="mt-2 rounded-md border border-rose-200/20 p-2 text-[10px]"><p className="font-semibold text-rose-100">{i.title}</p><p className="mt-1 text-slate-400">{i.body}</p></div>)}</div></div>:null}
    {tab==="coverage"?<div className="mt-3 grid gap-2 sm:grid-cols-2">{coverage.map(c=><article key={c.domain} className="rounded-md border border-white/8 p-2"><div className="flex justify-between gap-2"><p className="text-[10px] font-semibold text-white">{c.domain}</p><span className="text-[9px] text-cyan-200">{c.state}</span></div><p className="mt-1 text-[9px] text-slate-500">{c.supportingItemIds.length} supporting · {c.contradictionIds.length} contradictions</p><p className="mt-1 text-[9px] text-slate-600">{c.suggestedNextAction}</p></article>)}</div>:null}
    {tab==="claims"?<div className="mt-3 grid gap-2 lg:grid-cols-3">{(["safe-to-say","needs-qualification","do-not-claim"] as const).map(state=><section key={state} className="rounded-md border border-white/8 p-2"><h3 className="text-[10px] font-bold uppercase text-cyan-200">{state==="do-not-claim"?"Do not claim yet":state.replaceAll("-"," ")}</h3>{safety.filter(x=>x.state===state).slice(0,10).map(x=><article key={x.item.id} className="mt-2 border-t border-white/8 pt-2 text-[9px]"><p className="font-semibold text-white">{x.saferWording}</p><p className="mt-1 text-slate-500">{x.reason}</p><p className="mt-1 text-slate-600">Supporting: {x.item.sourceRefs.join(", ")||x.item.id} · freshness {x.item.structuredData.freshnessState as string||"unknown"}</p></article>)}</section>)}</div>:null}
    {tab==="registers"?<div className="mt-3 grid gap-2 lg:grid-cols-3">{(["decision","risk","action"] as const).map(k=><section key={k} className="rounded-md border border-white/8 p-2"><h3 className="text-[10px] font-bold uppercase text-cyan-200">{k} ledger</h3>{active.filter(i=>i.kind===k).map(i=><article key={i.id} className="mt-2 border-t border-white/8 pt-2"><p className="text-[10px] font-semibold text-white">{i.title}</p><p className="mt-1 text-[9px] text-slate-500">Status: {String(i.structuredData.decisionStatus??i.structuredData.mitigationStatus??i.structuredData.status)} · Owner: {String(i.structuredData.decisionOwner??i.structuredData.mitigationOwner??i.structuredData.owner)}</p></article>)}</section>)}</div>:null}
    {tab==="export"?<div className="mt-3"><div className="flex flex-wrap gap-2"><label className="text-[10px] text-slate-500">Export profile <select value={profile} onChange={e=>setProfile(e.target.value as ExportProfile)} className="ml-1 rounded bg-[#071016] p-2">{["customer-handoff","internal-technical-brief","poc-brief","support-escalation"].map(x=><option key={x}>{x}</option>)}</select></label><button className={button} onClick={()=>void navigator.clipboard.writeText(buildCaseMarkdown(bundle,profile))}>Copy Markdown</button><button className={button} onClick={()=>download(`${bundle.case.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.md`,buildCaseMarkdown(bundle,profile),"text/markdown")}>Download Markdown</button><button className={button} onClick={()=>download(`${bundle.case.id}.solution-case.json`,exportSolutionCase(bundle),"application/json")}>Export case JSON</button><button className={button} onClick={()=>fileRef.current?.click()}>Import case</button><input ref={fileRef} type="file" accept=".json,.solution-case.json" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.currentTarget.value="";}}/><button className={button} onClick={()=>window.print()}>Print / Save PDF</button></div><div className="mt-2 grid gap-2 sm:grid-cols-3 text-[10px]"><div className="rounded-md border border-emerald-200/15 p-2">Ready<br/><strong>{audit.ready.length}</strong></div><div className="rounded-md border border-amber-200/15 p-2">Needs qualification<br/><strong>{audit.needsQualification.length}</strong></div><div className="rounded-md border border-rose-200/15 p-2">Excluded for safety<br/><strong>{audit.excluded.length}</strong></div></div><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-md border border-white/8 bg-black/20 p-3 text-[9px] leading-4 text-slate-400">{buildCaseMarkdown(bundle,profile)}</pre></div>:null}
    <div className="sr-only" aria-live="polite">Case revision {bundle.case.revision}; best next question {top?.questionText??"none"}.</div>
  </section>;
}
