import type {
  EcosystemNode,
  PipelineLayer,
  ResponsibilityMatrixRow,
} from "@/types/applied-voice";

export const PIPELINE_LAYERS: PipelineLayer[] = [
  {
    id: "audio-source",
    name: "Audio source",
    purpose: "Capture speech from a microphone, recording, media stream, or telephony system.",
    ownership: ["customer", "third-party"],
    deepgramBoundary: "Deepgram receives audio after the customer establishes an input source.",
    customerBoundary: "Choose the device/provider, obtain consent, and capture usable audio.",
    inputs: ["Air pressure / existing recording", "Device or provider configuration"],
    outputs: ["Digital audio frames or file bytes"],
    protocols: ["MediaRecorder", "Web Audio", "PSTN", "SIP/RTP", "WebRTC", "file I/O"],
    failureModes: ["Permission denied", "Muted device", "Clipping", "Echo", "Incorrect channel selection"],
    configurationChoices: ["Microphone", "channel layout", "capture sample rate", "recording consent"],
    payloadExample: { source: "browser microphone", provenance: "architectural concept" },
    relevantDeepgramModule: "Live Mic or STT Upload",
    relevantCodeFiles: ["src/components/browser-mic-card.tsx"],
    provenance: "working",
  },
  {
    id: "transport",
    name: "Transport",
    purpose: "Move bounded audio and control events between the source, application, and speech service.",
    ownership: ["shared", "customer", "third-party"],
    deepgramBoundary: "Deepgram terminates documented HTTPS or WebSocket requests.",
    customerBoundary: "Open, authenticate, monitor, and recover the connection; bridge third-party media where needed.",
    inputs: ["Audio frames", "request parameters", "temporary credential or server authorization"],
    outputs: ["Ordered frames", "socket lifecycle", "request/response metadata"],
    protocols: ["HTTPS", "WebSocket", "SIP/RTP", "WebRTC"],
    failureModes: ["Network loss", "close 1006", "expired token", "out-of-order application events", "backpressure"],
    configurationChoices: ["REST versus WebSocket", "chunk cadence", "retry policy", "server proxy versus temporary browser token"],
    payloadExample: { event: "socket-open", authorization: "***redacted***" },
    relevantDeepgramModule: "Auth, Live Mic, API Studio",
    relevantCodeFiles: ["src/lib/live-mic", "src/app/api/deepgram/token/route.ts"],
    provenance: "working",
  },
  {
    id: "audio-preprocessing",
    name: "Audio preprocessing",
    purpose: "Produce audio bytes whose encoding, container, channels, and sample rate match the declared request.",
    ownership: ["customer", "third-party"],
    deepgramBoundary: "Deepgram decodes supported input when the request declaration matches the bytes.",
    customerBoundary: "Resample/transcode when needed and avoid lying about the media format.",
    inputs: ["PCM or compressed audio", "container headers", "device metadata"],
    outputs: ["Supported, correctly described audio stream"],
    protocols: ["linear PCM", "Opus", "WAV/container metadata", "media codecs"],
    failureModes: ["Wrong encoding", "wrong sample rate", "unsupported MIME type", "stereo/mono mismatch", "silence"],
    configurationChoices: ["PCM versus compressed", "container versus encoding", "sample rate", "channel count", "echo cancellation"],
    payloadExample: { encoding: "linear16", sample_rate: 16000, channels: 1, note: "example only" },
    relevantDeepgramModule: "STT, Live Mic",
    relevantCodeFiles: ["src/components/browser-mic-card.tsx"],
    provenance: "concept",
  },
  {
    id: "speech-recognition",
    name: "Speech recognition",
    purpose: "Convert audio into transcript text and, where returned, word timing and recognition metadata.",
    ownership: ["deepgram", "customer"],
    deepgramBoundary: "Deepgram runs the selected documented speech-recognition capability and returns events/results.",
    customerBoundary: "Choose an appropriate model/configuration, supply representative audio, and evaluate output by segment.",
    inputs: ["Audio", "model/language and supported options"],
    outputs: ["Transcript", "word/timing metadata", "request metadata"],
    protocols: ["REST JSON plus audio bytes/URL", "WebSocket audio and JSON events"],
    failureModes: ["Language/model mismatch", "domain-term errors", "speaker confusion", "unstable interim text"],
    configurationChoices: ["Batch versus realtime", "Nova family", "language", "smart formatting", "diarization", "keyterms where supported"],
    payloadExample: { results: { channels: [{ alternatives: [{ transcript: "Example transcript" }] }] }, metadata: { request_id: "example" } },
    relevantDeepgramModule: "STT, Live Mic, API Studio, Model Lab",
    relevantCodeFiles: ["src/app/api/deepgram/transcribe-url/route.ts", "src/app/api/deepgram/transcribe-file/route.ts"],
    provenance: "working",
  },
  {
    id: "turn-detection",
    name: "Turn detection",
    purpose: "Decide whether a speaker is beginning, pausing, resuming, or finishing a conversational turn.",
    ownership: ["deepgram", "customer"],
    deepgramBoundary: "Documented conversational capabilities may emit turn lifecycle signals.",
    customerBoundary: "Define interruption policy and decide when downstream generation should start or cancel.",
    inputs: ["Streaming audio", "speech/activity evidence", "turn configuration"],
    outputs: ["Turn events", "interim/final text", "end-of-turn decisions"],
    protocols: ["WebSocket JSON events"],
    failureModes: ["False endpoint", "long wait", "speaking over user", "wasted downstream call after resumed speech"],
    configurationChoices: ["Endpointing/pause behavior", "eager versus final decision", "timeout", "barge-in policy"],
    payloadExample: { type: "EndOfTurn", note: "Recorded simulation; verify event contract in official docs." },
    relevantDeepgramModule: "Turn-Taking Lab (simulation)",
    relevantCodeFiles: ["src/lib/applied-voice/labs.ts"],
    provenance: "simulated",
  },
  {
    id: "orchestration",
    name: "Conversation orchestration / LLM",
    purpose: "Manage state, instructions, context, generation, cancellations, and policy around each turn.",
    ownership: ["customer", "deepgram", "third-party"],
    deepgramBoundary: "Voice Agent can provide an integrated documented orchestration path; otherwise Deepgram supplies voice primitives.",
    customerBoundary: "Own policy, prompts, business truth, model/provider choices, fallback, and outcome validation.",
    inputs: ["Transcript/turn event", "conversation state", "customer context", "tool policy"],
    outputs: ["Response text", "tool request", "handoff/cancellation decision"],
    protocols: ["Application events", "LLM provider API", "state machine"],
    failureModes: ["Hallucinated claim", "late response", "lost context", "incorrect tool selection", "uncancelled generation"],
    configurationChoices: ["Integrated agent versus cascaded pipeline", "prompt scope", "memory", "model", "guardrails"],
    payloadExample: { phase: "llm-request", context: "sanitized customer context", provenance: "concept" },
    relevantDeepgramModule: "Voice Agent concept, Tool Calling Lab",
    relevantCodeFiles: ["src/lib/applied-voice/labs.ts"],
    provenance: "concept",
  },
  {
    id: "tools-business-systems",
    name: "Tools and business systems",
    purpose: "Turn an understood request into a validated, authorized business-system operation.",
    ownership: ["customer", "third-party"],
    deepgramBoundary: "Deepgram may emit or carry documented function-call events; it does not grant access to customer systems.",
    customerBoundary: "Authenticate, authorize, validate, execute, audit, retry safely, and require confirmation for sensitive actions.",
    inputs: ["Tool name", "structured arguments", "caller/session authorization"],
    outputs: ["Validated result or bounded failure", "audit/business event"],
    protocols: ["JSON Schema", "HTTPS", "database/CRM SDK", "queues"],
    failureModes: ["Invalid arguments", "timeout", "duplicate mutation", "unauthorized action", "malformed result"],
    configurationChoices: ["Client/server execution boundary", "allowlist", "confirmation", "idempotency key", "human approval"],
    payloadExample: { name: "lookup_order", arguments: { order_id: "ORDER-DEMO-42" }, provenance: "local simulation" },
    relevantDeepgramModule: "Tool Calling Lab",
    relevantCodeFiles: ["src/lib/applied-voice/labs.ts"],
    provenance: "simulated",
  },
  {
    id: "text-to-speech",
    name: "Text-to-speech",
    purpose: "Convert approved response text into audio bytes for playback or transport return.",
    ownership: ["deepgram", "customer"],
    deepgramBoundary: "Deepgram synthesizes audio using a documented voice/model and supported output configuration.",
    customerBoundary: "Choose voice/language, send safe text, handle audio bytes, and evaluate intelligibility and timing.",
    inputs: ["Text", "voice/model", "supported audio output options"],
    outputs: ["Audio bytes", "content type", "request metadata where available"],
    protocols: ["REST", "WebSocket where documented"],
    failureModes: ["Unsupported model/option", "empty text", "slow first byte", "audio format mismatch"],
    configurationChoices: ["Voice", "streaming versus single request", "encoding/container/sample rate where supported"],
    payloadExample: { text: "Your appointment is confirmed.", authorization: "***redacted***" },
    relevantDeepgramModule: "TTS, API Studio",
    relevantCodeFiles: ["src/app/api/deepgram/tts/route.ts"],
    provenance: "working",
  },
  {
    id: "audio-return",
    name: "Audio playback or telephony return",
    purpose: "Buffer and deliver synthesized audio without clipping, excessive delay, echo, or speaking over the user.",
    ownership: ["customer", "third-party"],
    deepgramBoundary: "Deepgram returns audio; the consuming application/provider controls delivery and playback.",
    customerBoundary: "Decode, buffer, play/bridge, cancel on interruption, and manage echo.",
    inputs: ["Audio bytes/chunks", "playback/cancellation state"],
    outputs: ["Audible response", "playback telemetry"],
    protocols: ["Web Audio", "HTMLAudioElement", "RTP", "provider media stream"],
    failureModes: ["Buffer underrun", "echo feedback", "clipped start", "late cancellation", "wrong codec"],
    configurationChoices: ["Buffer target", "object URL versus stream", "barge-in", "jitter handling"],
    payloadExample: { event: "playback-start", buffer_ms: 120, provenance: "example" },
    relevantDeepgramModule: "TTS",
    relevantCodeFiles: ["src/components"],
    provenance: "concept",
  },
  {
    id: "analytics-observability",
    name: "Analytics, storage, and observability",
    purpose: "Explain what happened, measure system behavior, protect data, and connect voice events to business outcomes.",
    ownership: ["customer", "shared", "third-party"],
    deepgramBoundary: "Deepgram returns request IDs, response data, and service-side signals documented for the selected product.",
    customerBoundary: "Create local trace IDs, sanitize logs, choose retention, measure outcome, and alert on failures.",
    inputs: ["Sanitized events", "latency timestamps", "request IDs", "business outcomes"],
    outputs: ["Trace", "latency waterfall", "quality evaluation", "alerts", "audit record"],
    protocols: ["Structured logs", "OpenTelemetry concept", "metrics", "event store"],
    failureModes: ["Secret leakage", "missing correlation IDs", "PII over-retention", "subjective metrics treated as objective"],
    configurationChoices: ["Redaction", "sampling", "retention", "trace schema", "human review"],
    payloadExample: { session_id: "local-session-demo", request_id: "example", authorization: "***redacted***" },
    relevantDeepgramModule: "Payload Inspector, Flight Recorder, Evaluation Lab",
    relevantCodeFiles: ["src/lib/inspection.ts", "src/lib/applied-voice/academy.ts"],
    provenance: "working",
  },
];

const ingress = (id: string, name: string, protocol: string): EcosystemNode => ({
  id,
  category: "audio-ingress",
  name,
  role: "Provide audio to the application boundary.",
  interfaceProtocol: [protocol],
  dataIn: ["User or recorded speech"],
  dataOut: ["Audio frames or bytes"],
  ownership: "customer",
  deepgramDependency: "None until audio is sent to a Deepgram API.",
  customerDependency: "Capture permissions, consent, audio quality, and transport implementation.",
  integrationRisk: "Format mismatch, missing consent, or unstable media delivery.",
  sampleArchitecture: [name, "Customer application", "Deepgram speech capability"],
  provenance: "concept",
});

const toolNode = (id: string, name: string): EcosystemNode => ({
  id,
  category: "tools",
  name,
  role: "Supply bounded business data or perform an explicitly authorized operation.",
  interfaceProtocol: ["Customer-defined HTTPS/SDK", "JSON Schema concept"],
  dataIn: ["Validated arguments", "authorized identity/context"],
  dataOut: ["Structured result or bounded error"],
  ownership: "customer",
  deepgramDependency: "No connector is installed; an orchestrator may pass a documented function call to customer code.",
  customerDependency: "Credentials, authorization, schema validation, audit, timeout, and idempotency.",
  integrationRisk: "Unauthorized, duplicated, stale, or malformed operations.",
  sampleArchitecture: ["Voice orchestration", name, "Validated result", "Response/handoff"],
  provenance: "concept",
});

export const ECOSYSTEM_NODES: EcosystemNode[] = [
  ingress("browser-microphone", "Browser microphone", "Web Audio / MediaRecorder"),
  ingress("native-mobile", "Native mobile app", "Platform audio APIs"),
  ingress("pstn", "PSTN", "Telephony provider"),
  ingress("sip", "SIP", "SIP signaling + media"),
  ingress("rtp", "RTP", "RTP media"),
  ingress("webrtc", "WebRTC", "WebRTC media"),
  ingress("recorded-files", "Recorded files", "HTTPS upload / hosted URL"),
  ingress("streaming-media", "Streaming media", "Provider/application stream"),
  ...["Twilio", "Amazon Connect", "AudioCodes", "Generic SIP/contact-center provider", "Bot media gateway"].map(
    (name, index): EcosystemNode => ({
      id: `telephony-${index + 1}`,
      category: "telephony-contact-center",
      name,
      role: "Bridge calls/contact-center media and events to customer voice orchestration.",
      interfaceProtocol: ["Provider-specific API", "SIP/RTP or media streaming concept"],
      dataIn: ["Call events", "caller audio"],
      dataOut: ["Media stream", "call control events"],
      ownership: "third-party",
      deepgramDependency: "Architecture concept only; no third-party account or connector is installed.",
      customerDependency: "Provider account, credentials, media bridge, consent, and call-control policy.",
      integrationRisk: "Provider event semantics, codecs, latency, retries, and billing.",
      sampleArchitecture: [name, "Customer media/orchestration service", "Deepgram"],
      provenance: "concept",
    }),
  ),
  ...[
    ["nova", "Nova transcription", "Speech recognition", "speech-to-text"],
    ["flux", "Flux conversational turn detection", "Conversational recognition and turn signals", "flux"],
    ["voice-agent", "Voice Agent API", "Integrated listen-think-speak session", "voice-agent"],
    ["aura", "Aura TTS", "Speech synthesis", "text-to-speech"],
    ["intelligence", "Text/Audio Intelligence", "Post-recognition analysis; verify selected capability", "text-intelligence"],
    ["self-hosted", "Self-hosted deployment", "Enterprise-controlled deployment option", "self-hosted"],
  ].map(([id, name, role, docsMetadataId]): EcosystemNode => ({
    id,
    category: "voice-intelligence",
    name,
    role,
    interfaceProtocol: ["Official Deepgram API/product contract"],
    dataIn: ["Capability-specific audio, text, settings, or events"],
    dataOut: ["Capability-specific results/events"],
    ownership: "deepgram",
    deepgramDependency: "Uses the named Deepgram capability.",
    customerDependency: "Correct integration, request selection, evaluation, and surrounding workflow.",
    integrationRisk: "Assuming feature/model compatibility without checking current official docs.",
    sampleArchitecture: ["Customer input", name, "Customer application"],
    provenance: id === "flux" || id === "voice-agent" || id === "self-hosted" ? "concept" : "working",
    docsMetadataId,
  })),
  ...[
    ["dg-agent", "Deepgram Voice Agent", "deepgram"],
    ["cascaded", "Cascaded STT → LLM → TTS", "customer"],
    ["pipecat", "Framework-driven pipeline such as Pipecat", "third-party"],
    ["customer-orchestrator", "Customer-owned orchestration service", "customer"],
    ["multi-agent", "Multi-agent handoff", "customer"],
  ].map(([id, name, ownership]): EcosystemNode => ({
    id,
    category: "orchestration",
    name,
    role: "Coordinate conversation state, generation, tools, cancellation, and handoff.",
    interfaceProtocol: ["Event/state machine", "provider APIs"],
    dataIn: ["Turn events", "transcript", "context"],
    dataOut: ["Response text", "tool calls", "state transition"],
    ownership: ownership as EcosystemNode["ownership"],
    deepgramDependency: id === "dg-agent" ? "Uses Voice Agent API; verify current settings/events." : "Uses Deepgram voice components where selected.",
    customerDependency: "Policy, business context, tool safety, fallback, and evaluation.",
    integrationRisk: "State drift, excessive latency, unsafe tool access, or failed cancellation.",
    sampleArchitecture: ["STT/turn event", name, "Tool or TTS"],
    provenance: "concept",
  })),
  ...["LLM", "RAG / knowledge base", "Conversation memory", "Customer profile", "Policy engine", "State machine"].map(
    (name, index): EcosystemNode => ({
      id: `context-${index + 1}`,
      category: "reasoning-context",
      name,
      role: "Provide reasoning, bounded knowledge, policy, or session state.",
      interfaceProtocol: ["Customer/provider-specific API or in-process state"],
      dataIn: ["Sanitized conversation context"],
      dataOut: ["Grounded response context or decision"],
      ownership: name === "LLM" ? "third-party" : "customer",
      deepgramDependency: "No third-party reasoning connector is installed.",
      customerDependency: "Data governance, retrieval quality, access policy, and evaluation.",
      integrationRisk: "Stale context, prompt injection, unsupported claims, or excessive data exposure.",
      sampleArchitecture: ["Transcript", name, "Orchestrator"],
      provenance: "concept",
    }),
  ),
  toolNode("crm", "CRM"),
  toolNode("ticketing", "Ticketing"),
  toolNode("order-lookup", "Order lookup"),
  toolNode("scheduling", "Scheduling"),
  toolNode("identity-verification", "Identity verification"),
  toolNode("payments", "Payments"),
  toolNode("internal-apis", "Internal APIs"),
  toolNode("human-handoff", "Human handoff"),
  ...["Spoken response", "Transcript", "Summary", "Structured JSON", "CRM record", "Alert", "Search index", "Quality review"].map(
    (name, index): EcosystemNode => ({
      id: `output-${index + 1}`,
      category: "outputs",
      name,
      role: "Deliver a user-visible or business-consumable result.",
      interfaceProtocol: ["Audio, JSON, database record, or review UI"],
      dataIn: ["Approved workflow result"],
      dataOut: [name],
      ownership: "customer",
      deepgramDependency: "Deepgram supplies voice/intelligence output only where selected.",
      customerDependency: "Validation, authorization, storage, presentation, and retention.",
      integrationRisk: "Incorrect output reaching a person/system without review or provenance.",
      sampleArchitecture: ["Voice workflow", name],
      provenance: "concept",
    }),
  ),
  ...["Event trace", "Latency", "Tool-call result", "Errors/retries", "Audio quality", "Task outcome", "Human escalation"].map(
    (name, index): EcosystemNode => ({
      id: `observability-${index + 1}`,
      category: "observability",
      name,
      role: "Make system behavior diagnosable without leaking secrets.",
      interfaceProtocol: ["Sanitized structured events/metrics"],
      dataIn: ["Timestamps", "status", "redacted identifiers", "business result"],
      dataOut: ["Trace, metric, alert, or audit signal"],
      ownership: "customer",
      deepgramDependency: "Use Deepgram request IDs/metadata only when actually returned.",
      customerDependency: "Correlation, redaction, retention, dashboards, and incident response.",
      integrationRisk: "Missing evidence or logging sensitive payloads.",
      sampleArchitecture: ["All components", name, "Operations/review"],
      provenance: "concept",
    }),
  ),
];

export const RESPONSIBILITY_MATRIX: ResponsibilityMatrixRow[] = [
  { area: "Speech service availability", deepgram: "Operate the selected managed API according to the applicable service terms.", customer: "Design graceful degradation and client-side health handling.", shared: "Define and test SLO expectations.", thirdParty: "Maintain upstream network/provider availability." },
  { area: "Audio capture and consent", deepgram: "Process submitted audio for the selected capability.", customer: "Capture lawfully, disclose use, and control source quality.", shared: "Validate supported input contracts.", thirdParty: "Device/telephony provider delivers media." },
  { area: "Authentication and secrets", deepgram: "Validate Deepgram credentials and grants.", customer: "Store keys server-side, rotate, redact, and constrain access.", shared: "Respond to credential incidents.", thirdParty: "Secret manager/runtime enforces access." },
  { area: "Model and request selection", deepgram: "Document supported capabilities and operate models.", customer: "Choose and evaluate configuration against representative data.", shared: "Investigate service/integration regressions with evidence.", thirdParty: "No default responsibility." },
  { area: "Tools and business actions", deepgram: "Carry documented function-call events where applicable.", customer: "Authorize, validate, execute, confirm, audit, and make mutations idempotent.", shared: "Define the event boundary.", thirdParty: "Operate CRM/helpdesk/payment/scheduling systems." },
  { area: "PII, retention, and compliance", deepgram: "Provide applicable product controls/documentation.", customer: "Define lawful basis, minimization, access, retention, and review.", shared: "Validate architecture with legal/security/compliance teams.", thirdParty: "Honor configured data obligations." },
  { area: "Observability and incident response", deepgram: "Expose documented service/request evidence.", customer: "Create sanitized traces, alerts, runbooks, and customer communications.", shared: "Coordinate incidents across the boundary.", thirdParty: "Provide their service telemetry/support." },
  { area: "Self-hosted operations", deepgram: "Responsibilities depend on the enterprise agreement and deployment documentation.", customer: "Own infrastructure, capacity, access, upgrades, and operations as assigned.", shared: "Agree support, version, and escalation boundaries.", thirdParty: "Cloud/hardware/platform availability." },
];
