import { z } from "zod";

export const LIVE_SOLUTION_CASE_SCHEMA_VERSION = "live-solution-case-v1" as const;
export const CASE_ITEM_KINDS = ["customer-statement","observed-technical-evidence","official-deepgram-evidence","external-public-evidence","requirement","constraint","assumption","hypothesis","decision","architecture-option","risk","open-question","answer","validation-result","action","success-criterion","stakeholder","business-outcome","technical-artifact","diagnosis","release-finding","unresolved-conflict","note","milestone"] as const;
export const CASE_RELATION_TYPES = ["supports","contradicts","derived-from","answers","raises-question","validates","invalidates","depends-on","blocks","mitigates","creates-risk","resolves-risk","informs","selected-over","supersedes","requires","owned-by","affects","implements","measured-by","tested-by","associated-with","caused-by","possibly-caused-by","documented-by","fixed-by-release","relevant-to"] as const;
export const CASE_VERIFICATION_STATES = ["customer-confirmed","customer-stated-unverified","artifact-observed","officially-sourced","locally-validated","API-Lab-validated","manually-validated","inferred","AI-assisted","unverified","contradicted","rejected","superseded"] as const;
export const CLAIM_SAFETY_STATES = ["safe-to-say","needs-qualification","do-not-claim","private-only","not-applicable"] as const;
export const CASE_LEDGER_EVENTS = ["case-created","case-updated","item-created","item-updated","item-confirmed","item-rejected","item-superseded","item-archived","item-purged","relation-created","relation-updated","relation-removed","question-generated","question-asked","question-answered","question-skipped","decision-proposed","decision-accepted","decision-rejected","decision-superseded","validation-attached","risk-created","risk-mitigated","action-created","action-completed","export-generated","source-refreshed","contradiction-detected","contradiction-resolved"] as const;

const id = z.string().min(1).max(160);
const iso = z.string().datetime();
const provenanceSchema = z.object({ mode:z.enum(["user","artifact","deterministic","AI-assisted","imported","module"]), sourceLabel:z.string().max(240).optional(), sourceItemIds:z.array(id).max(100).default([]) }).passthrough();
export const solutionCaseSchema = z.object({
  id, schemaVersion:z.literal(LIVE_SOLUTION_CASE_SCHEMA_VERSION), applicationVersion:z.string().max(40).optional(), title:z.string().min(1).max(200), displayName:z.string().min(1).max(200), optionalCustomerDisplayName:z.string().max(200).optional(), optionalAccountId:z.string().max(160).optional(),
  caseType:z.enum(["customer-discovery","technical-diagnosis","architecture-design","proof-of-concept","guided session-preparation","internal-review","support-escalation","demo","other"]), status:z.enum(["active","paused","awaiting-customer","awaiting-internal","validation-in-progress","decision-pending","completed","archived"]), sessionStage:z.enum(["orientation","business-outcome","current-state","technical-environment","requirements","constraints-and-risks","solution-options","evaluation-plan","decision","next-steps"]),
  owner:z.string().max(160), participants:z.array(z.string().max(160)).max(50), tags:z.array(z.string().max(80)).max(50), summary:z.string().max(4000), businessOutcome:z.string().max(2000), currentStateSummary:z.string().max(2000), desiredStateSummary:z.string().max(2000), defaultVisibility:z.enum(["customer","internal","private"]), createdAt:iso, updatedAt:iso, lastOpenedAt:iso, lastMigratedAt:iso.optional(), sourceFreshness:z.object({state:z.enum(["current","stale","mixed","unknown"]), lastVerifiedAt:iso.optional()}).passthrough(), revision:z.number().int().min(1), redactionStatus:z.enum(["redacted","review-required","synthetic"]), activeModule:z.string().max(120), activeQuestionId:id.optional(), pinnedItemIds:z.array(id).max(500), archivedAt:iso.optional(), migrationHistory:z.array(z.string().max(200)).max(20).default([]), exportVisibilityDefaults:z.object({customer:z.boolean(),internal:z.boolean()}).passthrough(),
}).passthrough();

const commonItem = z.object({ id, caseId:id, kind:z.enum(CASE_ITEM_KINDS), title:z.string().min(1).max(300), body:z.string().max(12000), structuredData:z.record(z.string(),z.unknown()), status:z.string().max(80), confidence:z.enum(["High","Medium","Low","Unknown"]), verificationState:z.enum(CASE_VERIFICATION_STATES), claimSafety:z.enum(CLAIM_SAFETY_STATES), sourceRefs:z.array(id).max(100), moduleOrigin:z.string().max(120), createdBy:z.string().max(120), createdAt:iso, updatedAt:iso, confirmedAt:iso.optional(), resolvedAt:iso.optional(), supersededAt:iso.optional(), supersededById:id.optional(), tags:z.array(z.string().max(80)).max(50), sensitivity:z.enum(["public","internal","sensitive","secret"]), visibility:z.enum(["customer","internal","private"]), exportPolicy:z.enum(["include","review","exclude"]), includeInCustomerExport:z.boolean(), includeInInternalExport:z.boolean(), isPinned:z.boolean(), isArchived:z.boolean(), redactionStatus:z.enum(["redacted","review-required","contains-secret","synthetic"]), provenance:provenanceSchema, revision:z.number().int().min(1) }).passthrough();
const customerStatement = commonItem.extend({ kind:z.literal("customer-statement"), structuredData:z.object({statementMode:z.enum(["verbatim","user-paraphrase","AI-summary"]),verbatimText:z.string().max(8000).optional(),normalizedSummary:z.string().max(4000),speakerLabel:z.string().max(120).optional(),capturedAt:iso,transcriptTimestamp:z.string().max(80).optional(),sourceArtifactId:id.optional()}).passthrough() });
const decision = commonItem.extend({kind:z.literal("decision"),structuredData:z.object({decisionStatus:z.enum(["proposed","under-review","accepted","rejected","deferred","superseded"]),decisionStatement:z.string().max(4000),rationale:z.string().max(4000),supportingEvidenceIds:z.array(id).default([]),contradictoryEvidenceIds:z.array(id).default([]),decisionOwner:z.string().max(160).default("Unknown"),reversible:z.boolean().default(true),validationRequired:z.boolean().default(true)}).passthrough()});
const risk = commonItem.extend({kind:z.literal("risk"),structuredData:z.object({riskCategory:z.enum(["product-fit","SDK","release-regression","architecture","runtime","media-path","security","privacy","compliance","performance","latency","accuracy","scalability","deployment","commercial","timeline","stakeholder","unknown"]),likelihood:z.enum(["High","Medium","Low","Unknown"]),impact:z.enum(["High","Medium","Low","Unknown"]),severity:z.enum(["High","Medium","Low","Unknown"]),description:z.string().max(4000),mitigation:z.string().max(4000).default(""),mitigationOwner:z.string().max(160).default("Unknown"),mitigationStatus:z.string().max(80).default("open"),blocking:z.boolean().default(false)}).passthrough()});
const action = commonItem.extend({kind:z.literal("action"),structuredData:z.object({actionText:z.string().max(4000),owner:z.string().max(160).default("Unknown"),ownerType:z.enum(["customer","Deepgram/internal","joint"]),status:z.enum(["open","in-progress","blocked","waiting","completed","cancelled"]),customerVisible:z.boolean().default(false)}).passthrough()});
const official = commonItem.extend({kind:z.literal("official-deepgram-evidence"),structuredData:z.object({canonicalSourceUrl:z.string().url(),sourceTitle:z.string().max(300),sourceType:z.string().max(100),conciseParaphrase:z.string().max(2000),retrievedAt:iso,lastVerifiedAt:iso,freshnessState:z.enum(["current","stale","unknown"]),authorityLevel:z.literal("official-deepgram"),citationIdentifier:z.string().max(160)}).passthrough()});
const genericKinds = CASE_ITEM_KINDS.filter((kind)=>!["customer-statement","decision","risk","action","official-deepgram-evidence"].includes(kind));
export const caseItemSchema = z.union([customerStatement,decision,risk,action,official,...genericKinds.map((kind)=>commonItem.extend({kind:z.literal(kind)}))] as [typeof customerStatement,typeof decision,typeof risk,typeof action,typeof official,...z.ZodTypeAny[]]);

export const caseRelationSchema=z.object({id,caseId:id,fromItemId:id,toItemId:id,type:z.enum(CASE_RELATION_TYPES),direction:z.enum(["directed","bidirectional"]),note:z.string().max(2000),confidence:z.enum(["High","Medium","Low","Unknown"]),sourceRefs:z.array(id).max(100),createdBy:z.string().max(120),createdAt:iso,updatedAt:iso,status:z.enum(["active","resolved","rejected"]),visibility:z.enum(["customer","internal","private"]),provenance:provenanceSchema}).passthrough();
export const caseLedgerEventSchema=z.object({id,caseId:id,eventType:z.enum(CASE_LEDGER_EVENTS),targetType:z.enum(["case","item","relation","question","export"]),targetId:id,changedFields:z.record(z.string(),z.string().max(500)),previousRevision:z.number().int().min(0),nextRevision:z.number().int().min(1),actorType:z.enum(["user","system","module","AI"]),actorLabel:z.string().max(120),moduleOrigin:z.string().max(120),reason:z.string().max(500),createdAt:iso,redactionStatus:z.literal("redacted"),visibility:z.enum(["customer","internal","private"]),provenance:provenanceSchema}).passthrough();
export const questionCandidateSchema=z.object({id,caseId:id,category:z.string().max(100),questionIntentId:z.string().max(160),questionText:z.string().max(1000),shortText:z.string().max(300),whyNow:z.array(z.string().max(500)).max(5),unlocks:z.array(z.string().max(120)).max(10),expectedAnswerType:z.string().max(120),suggestedAnswerOptions:z.array(z.string().max(240)).max(10),derivedFromItemIds:z.array(id),evidenceGapIds:z.array(id),blockingDecisionIds:z.array(id),relatedRiskIds:z.array(id),relatedRequirementIds:z.array(id),relatedModule:z.string().max(120),priorityBand:z.enum(["Ask now","Ask soon","Ask later","Parking lot"]),safetyLevel:z.enum(["normal","sensitive-review"]),sensitivity:z.enum(["public","internal","sensitive"]),status:z.enum(["candidate","ask-now","ask-later","asked","answered","skipped","not-relevant","parking-lot","superseded"]),askedAt:iso.optional(),answeredAt:iso.optional(),answerItemId:id.optional(),skippedReason:z.string().max(500).optional(),generationMode:z.enum(["deterministic","AI-rewrite"]),generatedAt:iso,sourceFreshness:z.enum(["current","stale","unknown"]),provenance:provenanceSchema}).passthrough();
export const caseModuleContributionSchema=z.object({moduleId:z.string().min(1).max(120),caseId:id,createdItems:z.array(caseItemSchema).max(100),updatedItems:z.array(caseItemSchema).max(100),proposedRelations:z.array(caseRelationSchema).max(200),questionCandidates:z.array(questionCandidateSchema).max(50),claimWarnings:z.array(z.string().max(1000)).max(50),validationResults:z.array(caseItemSchema).max(50),sourceRefs:z.array(id).max(100),suggestedActions:z.array(caseItemSchema).max(50),generatedAt:iso,provenance:provenanceSchema}).strict();
export const solutionCaseBundleSchema=z.object({schemaVersion:z.literal(LIVE_SOLUTION_CASE_SCHEMA_VERSION),case:solutionCaseSchema,items:z.array(caseItemSchema).max(2000),relations:z.array(caseRelationSchema).max(5000),ledger:z.array(caseLedgerEventSchema).max(10000),questionCandidates:z.array(questionCandidateSchema).max(100),savedAt:iso}).passthrough();

export type SolutionCase=z.infer<typeof solutionCaseSchema>;
export type CaseItem={id:string;caseId:string;kind:(typeof CASE_ITEM_KINDS)[number];title:string;body:string;structuredData:Record<string,unknown>;status:string;confidence:"High"|"Medium"|"Low"|"Unknown";verificationState:(typeof CASE_VERIFICATION_STATES)[number];claimSafety:(typeof CLAIM_SAFETY_STATES)[number];sourceRefs:string[];moduleOrigin:string;createdBy:string;createdAt:string;updatedAt:string;confirmedAt?:string;resolvedAt?:string;supersededAt?:string;supersededById?:string;tags:string[];sensitivity:"public"|"internal"|"sensitive"|"secret";visibility:"customer"|"internal"|"private";exportPolicy:"include"|"review"|"exclude";includeInCustomerExport:boolean;includeInInternalExport:boolean;isPinned:boolean;isArchived:boolean;redactionStatus:"redacted"|"review-required"|"contains-secret"|"synthetic";provenance:{mode:"user"|"artifact"|"deterministic"|"AI-assisted"|"imported"|"module";sourceLabel?:string;sourceItemIds:string[];[key:string]:unknown};revision:number};
export type CaseRelation=z.infer<typeof caseRelationSchema>; export type CaseLedgerEvent=z.infer<typeof caseLedgerEventSchema>; export type QuestionCandidate=z.infer<typeof questionCandidateSchema>;
export type CaseModuleContribution={moduleId:string;caseId:string;createdItems:CaseItem[];updatedItems:CaseItem[];proposedRelations:CaseRelation[];questionCandidates:QuestionCandidate[];claimWarnings:string[];validationResults:CaseItem[];sourceRefs:string[];suggestedActions:CaseItem[];generatedAt:string;provenance:CaseItem["provenance"]};
export type SolutionCaseBundle={schemaVersion:typeof LIVE_SOLUTION_CASE_SCHEMA_VERSION;case:SolutionCase;items:CaseItem[];relations:CaseRelation[];ledger:CaseLedgerEvent[];questionCandidates:QuestionCandidate[];savedAt:string;[key:string]:unknown};
