import { z } from "zod";

export const DELIVERABLES_SCHEMA_VERSION="solution-deliverables-v1" as const;
export const deliverableProfileSchema=z.enum(["customer-solution-pack","internal-solution-review","poc-kickoff-pack","executive-takeaway"]);
export const deliverableManualEditsSchema=z.object({
  title:z.string().max(160).optional(),
  executiveSummary:z.string().max(1200).optional(),
  sectionWording:z.string().max(1800).optional(),
  slideTitles:z.array(z.string().max(160)).max(8).optional(),
  slideTakeaways:z.array(z.string().max(500)).max(8).optional(),
  openQuestions:z.array(z.string().max(500)).max(10).optional(),
  nextActions:z.array(z.string().max(500)).max(10).optional(),
}).strict();
export const readinessStateSchema=z.enum(["exploratory","draft","reviewable","customer-ready","blocked"]);
const provenance=z.object({sourceItemIds:z.array(z.string()),sourceReferenceIds:z.array(z.string()),generationMode:z.enum(["deterministic","AI-polished","user-edited"]),generatedAt:z.string().datetime()}).passthrough();
export const deliverableSourceReferenceSchema=z.object({id:z.string(),caseSourceRefId:z.string(),title:z.string(),canonicalUrl:z.string().url().optional(),authority:z.enum(["customer-stated","observed-artifact","official-deepgram","approved-public","deterministic-validation","AI-assisted","user-edited"]),sourceType:z.string(),conciseRelevance:z.string(),retrievedAt:z.string().datetime().optional(),lastVerifiedAt:z.string().datetime().optional(),freshnessState:z.enum(["current","stale","unknown"]),artifactIds:z.array(z.string()),claimIds:z.array(z.string())}).passthrough();
export const deliverableSectionSchema=z.object({id:z.string(),artifactId:z.string(),sectionType:z.string(),heading:z.string(),content:z.string(),structuredContent:z.record(z.string(),z.unknown()),priority:z.enum(["critical","high","normal","low"]),sourceItemIds:z.array(z.string()),sourceReferenceIds:z.array(z.string()),claimSafety:z.enum(["safe-to-say","needs-qualification","do-not-claim","private-only","not-applicable"]),visibility:z.enum(["customer","internal","private"]),included:z.boolean(),exclusionReason:z.string().optional(),userEdited:z.boolean(),provenance}).passthrough();
export const deliverableArtifactSchema=z.object({id:z.string(),projectId:z.string(),artifactType:z.enum(["mermaid","svg","brief-markdown","brief-pdf","presentation-pptx","presentation-storyboard","speaker-notes","source-manifest","internal-reviewer-brief","solution-pack"]),title:z.string(),status:z.enum(["unavailable","draft","valid","invalid","blocked"]),version:z.number().int().positive(),audience:z.string(),outputFormat:z.string(),fileName:z.string(),mimeType:z.string(),byteSize:z.number().int().nonnegative(),sha256:z.string(),sourceCaseRevision:z.number().int().positive(),sourceItemIds:z.array(z.string()),sourceReferenceIds:z.array(z.string()),privateItemIdsExcluded:z.array(z.string()),warnings:z.array(z.string()),validationResults:z.array(z.object({name:z.string(),passed:z.boolean(),detail:z.string()})),createdAt:z.string().datetime(),updatedAt:z.string().datetime(),generatorVersion:z.string(),userEdited:z.boolean(),userEditTimestamp:z.string().datetime().optional(),redactionStatus:z.enum(["redacted","review-required","blocked"]),claimAuditStatus:z.enum(["passed","qualified","blocked"]),provenance}).passthrough();
export const deliverableProjectSchema=z.object({id:z.string(),caseId:z.string(),schemaVersion:z.literal(DELIVERABLES_SCHEMA_VERSION),title:z.string(),customerDisplayName:z.string(),audience:z.string(),artifactProfile:deliverableProfileSchema,readinessState:readinessStateSchema,sourceCaseRevision:z.number().int().positive(),generatedAt:z.string().datetime(),updatedAt:z.string().datetime(),generatedBy:z.enum(["deterministic","AI-polished"]),redactionState:z.enum(["redacted","review-required","blocked"]),sourceFreshness:z.enum(["current","stale","mixed","unknown"]),claimAuditStatus:z.enum(["passed","qualified","blocked"]),artifactIds:z.array(z.string()),provenance}).passthrough();
const sourcedNarrativeEntrySchema=z.object({text:z.string().max(12_000),sourceItemIds:z.array(z.string()).max(100),status:z.string().max(120).optional()}).strict();
export const solutionNarrativeSchema=z.object({customerOutcome:z.array(sourcedNarrativeEntrySchema),currentProblem:z.array(sourcedNarrativeEntrySchema),currentWorkflow:z.array(sourcedNarrativeEntrySchema),desiredExperience:z.array(sourcedNarrativeEntrySchema),proposedSolution:z.array(sourcedNarrativeEntrySchema),architectureComponents:z.array(sourcedNarrativeEntrySchema),architectureConnections:z.array(sourcedNarrativeEntrySchema),customerJourney:z.array(sourcedNarrativeEntrySchema),dataFlow:z.array(sourcedNarrativeEntrySchema),deepgramProducts:z.array(sourcedNarrativeEntrySchema),sdksAndRuntimes:z.array(sourcedNarrativeEntrySchema),deployment:z.array(sourcedNarrativeEntrySchema),authentication:z.array(sourcedNarrativeEntrySchema),mediaPath:z.array(sourcedNarrativeEntrySchema),securityPrivacy:z.array(sourcedNarrativeEntrySchema),scaleResilience:z.array(sourcedNarrativeEntrySchema),validationEvidence:z.array(sourcedNarrativeEntrySchema),successCriteria:z.array(sourcedNarrativeEntrySchema),architectureDecisions:z.array(sourcedNarrativeEntrySchema),risks:z.array(sourcedNarrativeEntrySchema),openQuestions:z.array(sourcedNarrativeEntrySchema),pocPlan:z.array(sourcedNarrativeEntrySchema),nextActions:z.array(sourcedNarrativeEntrySchema),officialSources:z.array(sourcedNarrativeEntrySchema),publicSources:z.array(sourcedNarrativeEntrySchema),assumptions:z.array(sourcedNarrativeEntrySchema),exclusions:z.array(sourcedNarrativeEntrySchema)}).strict();
export type DeliverableProfile=z.infer<typeof deliverableProfileSchema>;export type DeliverableManualEdits=z.infer<typeof deliverableManualEditsSchema>;export type ReadinessState=z.infer<typeof readinessStateSchema>;export type DeliverableProject=z.infer<typeof deliverableProjectSchema>;export type DeliverableArtifact=z.infer<typeof deliverableArtifactSchema>;export type DeliverableSection=z.infer<typeof deliverableSectionSchema>;export type DeliverableSourceReference=z.infer<typeof deliverableSourceReferenceSchema>;export type SolutionNarrative=z.infer<typeof solutionNarrativeSchema>;
