"use client";

import { useState } from "react";

import { studioInput, studioPrimaryButton } from "@/components/architecture-studio/StudioPrimitives";
import type { PocAcceptanceCriterion, ProofOfConceptPlanModel } from "@/types/architecture-studio-handoff";

export function PocPlanView({ plan, disabled, onSaveCriterion }: { plan: ProofOfConceptPlanModel; disabled: boolean; onSaveCriterion: (criterion: PocAcceptanceCriterion) => void }) {
  return <div className="space-y-4"><section className="rounded-xl border border-cyan-200/15 bg-cyan-200/[0.04] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-100/65">Proof-of-concept decision plan</p><h2 className="mt-2 text-xl font-semibold text-white">Objective</h2><p className="mt-3 text-sm leading-6 text-slate-300">{plan.objective}</p></section><div className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(340px,.8fr)]"><div className="space-y-4"><section className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><h3 className="text-xs font-semibold text-white">Scope</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(plan.scope).map(([key, value]) => <div key={key} className="rounded-lg border border-white/[0.07] p-3"><dt className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{key.replaceAll(/([A-Z])/g, " $1")}</dt><dd className="mt-1 text-[11px] leading-5 text-slate-300">{value}</dd></div>)}</dl></section><section className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><h3 className="text-xs font-semibold text-white">Test scenarios</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{plan.testScenarios.map((test) => <details key={test.id} className="rounded-lg border border-white/[0.07] p-3"><summary className="cursor-pointer text-[12px] font-semibold text-white focus-visible:outline-2 focus-visible:outline-cyan-200">{test.title}</summary><p className="mt-2 text-[11px] leading-5 text-slate-400">{test.method}</p><p className="mt-2 text-[10px] leading-4 text-slate-500">Evidence: {test.reason}</p></details>)}</div></section></div><aside className="space-y-4"><ListBlock title="Inputs required" items={plan.inputsRequired} /><ListBlock title="Unresolved prerequisites" items={plan.prerequisites} tone="amber" /><ListBlock title="Exit criteria" items={plan.exitCriteria} /></aside></div><section className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Acceptance criteria</h3><p className="mt-1 text-[11px] text-slate-400">Unknown targets remain explicitly labeled placeholders; the Studio does not invent benchmark values.</p></div><span className="text-[10px] font-bold uppercase tracking-wider text-amber-100">Synthetic owners and dates</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{plan.acceptanceCriteria.map((criterion) => <CriterionCard key={criterion.id} criterion={criterion} disabled={disabled} onSave={onSaveCriterion} />)}</div></section></div>;
}

function CriterionCard({ criterion, disabled, onSave }: { criterion: PocAcceptanceCriterion; disabled: boolean; onSave: (criterion: PocAcceptanceCriterion) => void }) {
  const [draft, setDraft] = useState(criterion);
  const set = <K extends keyof PocAcceptanceCriterion>(key: K, value: PocAcceptanceCriterion[K]) => setDraft((current) => ({ ...current, [key]: value }));
  return <article className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4"><div className="flex items-start justify-between gap-3"><h4 className="text-[12px] font-semibold text-white">{criterion.metric}</h4><select aria-label={`Status for ${criterion.metric}`} value={draft.status} onChange={(event) => set("status", event.target.value as PocAcceptanceCriterion["status"])} className="rounded border border-white/10 bg-[#03080d] px-2 py-1 text-[10px] text-slate-200"><option value="placeholder">Placeholder</option><option value="draft">Draft</option><option value="agreed">Agreed</option><option value="passed">Passed</option><option value="failed">Failed</option></select></div><div className="mt-3 grid gap-2"><Input label="Target" value={draft.target} onChange={(value) => set("target", value)} /><Input label="Comparison baseline" value={draft.comparisonBaseline} onChange={(value) => set("comparisonBaseline", value)} /><Input label="Measurement method" value={draft.measurementMethod} onChange={(value) => set("measurementMethod", value)} multiline /><div className="grid grid-cols-2 gap-2"><Input label="Sample size" value={draft.sampleSize} onChange={(value) => set("sampleSize", value)} /><Input label="Owner" value={draft.owner} onChange={(value) => set("owner", value)} /></div><Input label="Notes" value={draft.notes} onChange={(value) => set("notes", value)} multiline /><button type="button" disabled={disabled} onClick={() => onSave(draft)} className={studioPrimaryButton}>Save criterion</button></div></article>;
}

function Input({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) { return <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500"><span className="mb-1 block">{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} className={`${studioInput} min-h-20`} /> : <input value={value} onChange={(event) => onChange(event.target.value)} className={studioInput} />}</label>; }
function ListBlock({ title, items, tone = "slate" }: { title: string; items: string[]; tone?: "slate" | "amber" }) { return <section className={`rounded-xl border p-4 ${tone === "amber" ? "border-amber-200/15 bg-amber-200/[0.035]" : "border-white/[0.08] bg-black/15"}`}><h3 className="text-xs font-semibold text-white">{title}</h3><ul className="mt-3 space-y-2 text-[11px] leading-5 text-slate-400">{items.length ? items.map((item) => <li key={item}>— {item}</li>) : <li>None recorded</li>}</ul></section>; }
