import { expect,test } from "@playwright/test";
import { CASE_ITEM_KINDS,CASE_RELATION_TYPES,addCaseRelation,archiveCaseItem,auditCaseExport,buildCaseMarkdown,captureCaseItem,captureQuestionAnswer,createNorthstarDemoCase,createSolutionCaseBundle,deriveCoverage,detectContradictions,evaluateClaimSafety,exportSolutionCase,importSolutionCase,rankNextQuestions,redactCaseText,searchCase,supersedeCaseItem,updateQuestionStatus } from "../../src/lib/live-solution-case";
import { LIVE_SOLUTION_CASE_SCHEMA_VERSION,caseItemSchema,caseLedgerEventSchema,caseRelationSchema,questionCandidateSchema,solutionCaseBundleSchema,solutionCaseSchema } from "../../src/types/live-solution-case";

const NOW="2026-07-28T12:00:00.000Z";
test.describe("Live Solution Case schemas and deterministic intelligence",()=>{
 test("validates the versioned case, bundle, ledger, and questions",()=>{const b=createSolutionCaseBundle("Test",NOW);expect(solutionCaseSchema.safeParse(b.case).success).toBe(true);expect(solutionCaseBundleSchema.safeParse(b).success).toBe(true);expect(caseLedgerEventSchema.safeParse(b.ledger[0]).success).toBe(true);expect(questionCandidateSchema.safeParse(b.questionCandidates[0]).success).toBe(true);expect(b.schemaVersion).toBe(LIVE_SOLUTION_CASE_SCHEMA_VERSION);});
 test("supports every required item kind and relation type",()=>{expect(CASE_ITEM_KINDS).toHaveLength(24);expect(CASE_ITEM_KINDS).toEqual(expect.arrayContaining(["customer-statement","assumption","hypothesis","decision","risk","action","validation-result","unresolved-conflict"]));expect(CASE_RELATION_TYPES).toEqual(expect.arrayContaining(["supports","contradicts","answers","validates","supersedes","possibly-caused-by"]));});
 test("preserves customer statement modes without fabricating quotes",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"customer-statement",body:"We need low latency",statementMode:"user-paraphrase"},NOW);expect(b.items[0].structuredData.statementMode).toBe("user-paraphrase");expect(b.items[0].structuredData.verbatimText).toBeUndefined();b=captureCaseItem(b,{kind:"customer-statement",body:"Exact words",statementMode:"verbatim"},NOW);expect(b.items[1].structuredData.verbatimText).toBe("Exact words");b=captureCaseItem(b,{kind:"customer-statement",body:"Generated summary",statementMode:"AI-summary",verificationState:"AI-assisted"},NOW);expect(b.items[2].structuredData.verbatimText).toBeUndefined();});
 test("keeps confidence separate from verification",()=>{const b=captureCaseItem(createSolutionCaseBundle("Test",NOW),{kind:"hypothesis",body:"SDK generation mismatch",confidence:"High",verificationState:"inferred"},NOW);expect(b.items[0]).toMatchObject({confidence:"High",verificationState:"inferred",claimSafety:"needs-qualification"});});
 test("applies deterministic claim safety",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"customer-statement",body:"Need streaming",statementMode:"user-paraphrase"},NOW);expect(evaluateClaimSafety(b.items[0])).toMatchObject({state:"safe-to-say"});b=captureCaseItem(b,{kind:"assumption",body:"Browser runtime"},NOW);expect(evaluateClaimSafety(b.items[1]).state).toBe("needs-qualification");b=captureCaseItem(b,{kind:"note",body:"Internal deal note",visibility:"private"},NOW);expect(evaluateClaimSafety(b.items[2]).state).toBe("private-only");b=captureCaseItem(b,{kind:"decision",body:"Use streaming"},NOW);expect(evaluateClaimSafety(b.items[3]).state).toBe("needs-qualification");});
 test("scopes validation language to the tested environment",()=>{const b=captureCaseItem(createSolutionCaseBundle("Test",NOW),{kind:"validation-result",body:"Handshake succeeded",structuredData:{testEnvironment:"local mocked fixture"},verificationState:"API-Lab-validated"},NOW);expect(evaluateClaimSafety(b.items[0]).saferWording).toContain("local mocked fixture");});
 test("validates relationships, rejects missing targets, and deduplicates",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"requirement",body:"Streaming"},NOW);b=captureCaseItem(b,{kind:"observed-technical-evidence",body:"WebSocket endpoint observed"},NOW);b=addCaseRelation(b,{fromItemId:b.items[1].id,toItemId:b.items[0].id,type:"supports"},NOW);expect(caseRelationSchema.safeParse(b.relations[0]).success).toBe(true);expect(addCaseRelation(b,{fromItemId:b.items[1].id,toItemId:b.items[0].id,type:"supports"},NOW).relations).toHaveLength(1);expect(()=>addCaseRelation(b,{fromItemId:"missing",toItemId:b.items[0].id,type:"supports"},NOW)).toThrow(/does not exist/);});
 test("supersedes without rewriting history and archives safely",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"requirement",body:"Use batch"},NOW);const old=b.items[0];b=supersedeCaseItem(b,old.id,{kind:"requirement",body:"Use streaming"},"Customer correction",NOW);expect(b.items.find(i=>i.id===old.id)).toMatchObject({verificationState:"superseded"});expect(b.relations.some(r=>r.type==="supersedes")).toBe(true);b=archiveCaseItem(b,b.items.at(-1)!.id,NOW);expect(b.items.at(-1)!.isArchived).toBe(true);});
 test("detects structured conflicts but accepts scoped browser and server roles",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"observed-technical-evidence",body:"Browser",structuredData:{runtime:"browser"}},NOW);b=captureCaseItem(b,{kind:"observed-technical-evidence",body:"Server",structuredData:{runtime:"Next.js route handler"}},NOW);expect(detectContradictions(b).some(c=>c.field==="runtime")).toBe(true);expect(b.items.some(i=>i.kind==="unresolved-conflict")).toBe(true);let scoped=createSolutionCaseBundle("Scoped",NOW);scoped=captureCaseItem(scoped,{kind:"observed-technical-evidence",body:"Browser",structuredData:{runtime:"browser",scope:"browser-client"}},NOW);scoped=captureCaseItem(scoped,{kind:"observed-technical-evidence",body:"Server",structuredData:{runtime:"Next.js",scope:"backend-api"}},NOW);expect(detectContradictions(scoped)).toHaveLength(0);});
 test("ranks one explainable best question without AI and deduplicates answered intent",()=>{let b=createSolutionCaseBundle("Test",NOW);const questions=rankNextQuestions(b,NOW);expect(questions).toHaveLength(4);expect(questions[0].priorityBand).toBe("Ask now");expect(questions[0].generationMode).toBe("deterministic");const id=questions[0].id;b={...b,questionCandidates:questions};b=updateQuestionStatus(b,id,"asked",NOW);expect(b.questionCandidates.find(q=>q.id===id)?.status).toBe("asked");b=captureQuestionAnswer(b,id,"Improve completed calls", "note",NOW);expect(b.items.some(i=>i.kind==="answer")).toBe(true);expect(b.ledger.some(e=>e.eventType==="question-answered")).toBe(true);expect(b.questionCandidates.some(q=>q.id===id)).toBe(false);});
 test("gives contradiction confirmation priority",()=>{const b=createNorthstarDemoCase(NOW);const q=rankNextQuestions(b,NOW)[0];expect(q.questionText).toMatch(/Confirm codec/i);expect(q.whyNow.join(" ")).toMatch(/Conflicting/i);});
 test("derives named coverage states without percentages",()=>{const coverage=deriveCoverage(createNorthstarDemoCase(NOW));expect(coverage).toHaveLength(13);expect(coverage.map(c=>c.state)).toEqual(expect.arrayContaining(["Partial","Validated"]));expect(JSON.stringify(coverage)).not.toMatch(/%|percent/i);});
 test("provides deterministic local structured search",()=>{const b=createNorthstarDemoCase(NOW);expect(searchCase(b,"codec").length).toBeGreaterThan(0);expect(searchCase(b,"nonexistent term")).toHaveLength(0);});
 test("redacts secrets in items, ledger, persistence, and machine export",()=>{const secret="dg_abcdefghijklmnopqrstuvwxyz";const b=captureCaseItem(createSolutionCaseBundle("Test",NOW),{kind:"note",body:`Authorization: Token ${secret}`},NOW);const exported=exportSolutionCase(b);expect(exported).not.toContain(secret);expect(exported).toContain("REDACTED_SECRET");expect(JSON.stringify(b.ledger)).not.toContain(secret);expect(redactCaseText(`<script>x</script> ${secret}`)).not.toMatch(/script|abcdefghijklmnopqrstuvwxyz/);});
 test("validates import, retains unknown fields, and rejects future or malformed files",()=>{const b=createSolutionCaseBundle("Test",NOW) as typeof createSolutionCaseBundle extends (...args:never[])=>infer R?R:never;(b as unknown as Record<string,unknown>).futureSafeField={preserve:true};const ok=importSolutionCase(JSON.stringify(b));expect(ok.ok).toBe(true);if(ok.ok)expect((ok.bundle as unknown as Record<string,unknown>).futureSafeField).toEqual({preserve:true});expect(importSolutionCase("not json").ok).toBe(false);expect(importSolutionCase(JSON.stringify({...b,schemaVersion:"live-solution-case-v99"}))).toMatchObject({ok:false});});
 test("runs customer export preflight and excludes unsafe/private/proposed content",()=>{let b=createSolutionCaseBundle("Test",NOW);b=captureCaseItem(b,{kind:"assumption",body:"Likely browser"},NOW);b.items[0].includeInCustomerExport=true;b=captureCaseItem(b,{kind:"note",body:"Private",visibility:"private"},NOW);b.items[1].includeInCustomerExport=true;b=captureCaseItem(b,{kind:"decision",body:"Use Nova"},NOW);b.items[2].includeInCustomerExport=true;const audit=auditCaseExport(b,"customer-handoff");expect(audit.needsQualification).toHaveLength(1);expect(audit.excluded).toHaveLength(2);const markdown=buildCaseMarkdown(b,"customer-handoff",NOW);expect(markdown).not.toContain("Private");expect(markdown).toContain("Draft—review before sharing");});
 test("Northstar fixture is explicitly synthetic and contains required ledgers",()=>{const b=createNorthstarDemoCase(NOW);expect(b.case.redactionStatus).toBe("synthetic");expect(b.case.displayName).toContain("synthetic");expect(b.items.some(i=>i.kind==="decision"&&i.structuredData.decisionStatus==="accepted")).toBe(true);expect(b.items.some(i=>i.kind==="risk"&&i.structuredData.blocking===true)).toBe(true);expect(b.items.some(i=>i.kind==="action")).toBe(true);expect(b.items.some(i=>i.kind==="validation-result")).toBe(true);});
});
